### ISSUE TITLE
Multiple Slack Generators / Buses

### ISSUE THREAD

**Issue by ulfmueller** [PyPSA/PyPSA#10]
Is there a trick to introduce more than one bus with slack generator behaviour?
When I modelled in SINCAL I sometimes used more than one slack bus for e.g. modelling the connection to other countries in a very abstract and ideal way.
I am asking in context of performing the lpf() and pf(). 
When introducing a storage or store/link component the p_set would define the dispatch right up front by the input data. So is there a way to trick the components towards a slack bahaviour?

**Comment by nworbmot** [comment]
Hi Ulf, at the moment there is only one slack per synchronous zone in PyPSA.
It's on our TODO list to allow distributed slack, probably following PowerFactory (which can distribute the slack proportional to what generators are set to dispatch or what remaining capacity they have available). We could probably also make this user-defined. However, it's not a priority for us in the next few months.
As an interim measure, you can see how much active power is landing at the single slack and then manually redistribute it by adjusting the p_set of the generators.

**Comment by ulfmueller** [comment]
Thanks Tom for your explanation. The interim measure is an interesting idea!
I totally understand that that is not an priority-issue. But hey its open source, maybe one of us will implement something ;)
Shall I close this issue or do you want it to leave as an reminder/part of the todo list?

**Comment by nworbmot** [comment]
Hey Ulf, let's leave it open as a reminder - the discussion may be useful to other people too.

**Comment by nworbmot** [comment]
Note to future self/others: the equations for distributed slack are in Section 4.1.3 of the PSAT documentation http://www.slideserve.co.uk/psat-1-3-4.
