### ISSUE TITLE
SciGrid German Network example. Error on importing cvs's

### ISSUE THREAD

**Issue by c-dejesus** [PyPSA/PyPSA#100]
Hi

I am trying to run the example of Linear OPF then non-linear PF on the SciGRID German network. But everytime I run this:

#You may have to adjust this path to where 
#you downloaded the github repository
#https://github.com/PyPSA/PyPSA

csv_folder_name = os.path.dirname(pypsa.__file__) + "C:/Users/Cesar_De_Jesus/Documents/PDE/PDE_3/Master_Thesis/Open_source_models/Open_energy_system_models/PyPSA-master/examples/scigrid-de/scigrid-with-load-gen-trafos/"

network = pypsa.Network(csv_folder_name=csv_folder_name)

I get this error:

The argument csv_folder_name for initiating Network() is deprecated, please use import_name instead.
Traceback (most recent call last):

  File "<ipython-input-2-4cda07b00e2a>", line 17, in <module>
    network = pypsa.Network(csv_folder_name=csv_folder_name)

  File "C:\Users\Cesar_De_Jesus\Anaconda3\lib\site-packages\pypsa\components.py", line 299, in __init__
    self.import_from_csv_folder(import_name)

  File "C:\Users\Cesar_De_Jesus\Anaconda3\lib\site-packages\pypsa\io.py", line 392, in import_from_csv_folder
    with ImporterCSV(csv_folder_name, encoding=encoding) as importer:

  File "C:\Users\Cesar_De_Jesus\Anaconda3\lib\site-packages\pypsa\io.py", line 78, in __init__
    assert os.path.isdir(csv_folder_name), "Directory {} does not exist.".format(csv_folder_name)

AssertionError: Directory C:\Users\Cesar_De_Jesus\Anaconda3\lib\site-packages\pypsaC:/Users/Cesar_De_Jesus/Documents/PDE/PDE_3/Master_Thesis/Open_source_models/Open_energy_system_models/PyPSA-master/examples/scigrid-de/scigrid-with-load-gen-trafos/ does not exist.

Any suggestion on how to procede

**Comment by FabianHofmann** [comment]
Hey @c-dejesus, 

I think you are wrong about setting the path like this  
>csv_folder_name = os.path.dirname(pypsa.file) + "C:/Users/Cesar_De_Jesus/Documents/PDE/PDE_3/Master_Thesis/Open_source_models/Open_energy_system_models/PyPSA-master/examples/scigrid-de/scigrid-with-load-gen-trafos/"

could you please only use 
```
csv_folder_name = "C:\Users\Cesar_De_Jesus\Documents\PDE\PDE_3\Master_Thesis\Open_source_models\Open_energy_system_models\PyPSA-master\examples\scigrid-de\scigrid-with-load-gen-trafos\"
```

and make sure this path really exists (this is what the error tells you). And watch out, I think windows wants backslashes instead of slaches for a path

**Comment by c-dejesus** [comment]
Thank's!!
