### ISSUE TITLE
Adding 'nice_name' and 'color' column to network.carriers

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#103]
This is rather a question whether it is sensible to introduce two new columns in network.carriers

1.`nice_name`: giving the full name of the carrier
2. `color`: color specification for plotting

The two columns could then be used as default (if existent) when plotting pie charts with `network.plot`. Like this it would not be necessary to carry the color dict and a name translation dict always beside the network object.

**Comment by fneum** [comment]
I really like this idea!
