### ISSUE TITLE
Import grid topology from csv

### ISSUE THREAD

**Issue by birgits** [PyPSA/PyPSA#104]
I have grid topology data without time series information that I want to import using the `import_from_csv_folder` method. This produces the error `FileNotFoundError: [Errno 2] File b'.../snapshots.csv' does not exist`. I would think that this is not the desired behaviour when importing only topology data. Before the refactoring of the csv import it was checked if the snapshots.csv file existed before importing it. I guess adapting the [get_snapshots](https://github.com/PyPSA/PyPSA/blob/master/pypsa/io.py#L85-L87) function as follows would fix it?

```
def get_snapshots(self):
        fn = os.path.join(self.csv_folder_name, "snapshots.csv")
        if not os.path.isfile(fn): return None
        return pd.read_csv(fn, index_col=0, encoding=self.encoding, parse_dates=True)
```

**Comment by fneum** [comment]
yes, thanks for spotting this!
