### ISSUE TITLE
Naming issue in the country file

### ISSUE THREAD

**Issue by ene23033** [PyPSA/PyPSA#1048]
### Version Checks (indicate both or one)

- [X] I have confirmed this bug exists on the lastest [release](https://github.com/pypsa/pypsa/releases) of PyPSA.

- [ ] I have confirmed this bug exists on the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch of PyPSA.

### Issue Description

On running the model for India by configuring the **config.yaml** file and putting IN in countries and setting enable to:
enable:
  retrieve_databundle: false
  retrieve_cost_data: true 
  download_osm_data: true 
  build_natura_raster: true
  build_cutout: false

and running the model using code **snakemake -j  1 solve_all_networks**
Now in the \pypsa-earth\resources\shapes\country_shapes.geojson I am getting India's map. But there is another file named africa_shape.geojson in the same folder but shows India's map with the country's offshore shape. This is a name issue as the map in the picture is of India's, but the filename is africa_shape.geojson. Figure has been attached below:
![Screenshot 2024-09-27 235116](https://github.com/user-attachments/assets/0b24f8ba-9d25-4408-a230-9cb673282d04)

### Installed Versions

<details>

Replace this line.

</details>

**Comment by fneum** [comment]
Please open an issue in the PyPSA-Earth repository.
