### ISSUE TITLE
Bug in power flow for pandas >=0.25.0

### ISSUE THREAD

**Issue by birgits** [PyPSA/PyPSA#105]
When running a power flow with pypsa 0.14.1 and pandas >0.25.0 I get the following error:

```
../../../lib/python3.6/site-packages/pypsa/pf.py:152: in network_pf
    return _network_prepare_and_run_pf(network, snapshots, skip_pre, linear=False, x_tol=x_tol, use_seed=use_seed)
../../../lib/python3.6/site-packages/pypsa/pf.py:122: in _network_prepare_and_run_pf
    itdf[sub_network.name], difdf[sub_network.name], cnvdf[sub_network.name] = sub_network_pf_fun(sub_network, snapshots=snapshots, skip_pre=True, **kwargs)
../../../lib/python3.6/site-packages/pypsa/pf.py:241: in sub_network_pf
    for c in sub_network.iterate_components(network.controllable_one_port_components)])
../../../lib/python3.6/site-packages/pypsa/pf.py:241: in <listcomp>
    for c in sub_network.iterate_components(network.controllable_one_port_components)])
../../../lib/python3.6/site-packages/pandas/core/groupby/groupby.py:1382: in f
    result[col] = self._try_cast(result[col], self.obj[col])
../../../lib/python3.6/site-packages/pandas/core/frame.py:2975: in __getitem__
    indexer = self.columns.get_loc(key)
../../../lib/python3.6/site-packages/pandas/core/indexes/base.py:2892: in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
pandas/_libs/index.pyx:107: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/index.pyx:131: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/hashtable_class_helper.pxi:1607: in pandas._libs.hashtable.PyObjectHashTable.get_item
    ???
_ _ _ _ _ _ _ _
```
With pandas 0.24.2 everything works fine. As there were [enhancements to groupby in pandas 0.25.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html#groupby-aggregation-with-relabeling) I guess it has something to do with that. Do you get the same error or does the problem lie somewhere else?

**Comment by FabianHofmann** [comment]
hey @birgits 

I cannot reproduce the error (having pypsa 0.14.1 and pandas 0.25). Have you tried running the [scigrid example](https://github.com/PyPSA/PyPSA/blob/master/examples/scigrid-de/scigrid-lopf-then-pf.py)?
It also includes a pf calculation. And, is there a last line of the error message? Or is this the whole output?

**Comment by birgits** [comment]
@FabianHofmann thanks for replying so quickly! The scigrid example works so the problem must be on my side. Just weird that it works with pandas <0.25.0. I will have a closer look at it tomorrow. Thanks again!
