### ISSUE TITLE
Issue creating model with CPLEX

### ISSUE THREAD

**Issue by NathanDeMatos** [PyPSA/PyPSA#1057]
### Version Checks (indicate both or one)

- [X] I have confirmed this bug exists on the lastest [release](https://github.com/pypsa/pypsa/releases) of PyPSA.

- [X] I have confirmed this bug exists on the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch of PyPSA.

### Issue Description

There is an issue with creating the model in CPLEX on the current version of pypsa. Before starting to solve, cplex gives error 1615. The issue does not occur when using HIGHS, or when using CPLEX with version 0.30.3

### Installed Versions

<details>

Replace this line.

</details>

**Comment by lkstrp** [comment]
xref: https://github.com/PyPSA/linopy/issues/362
