### ISSUE TITLE
Remove non-existing "-call" argument from snakemake command examples 

### ISSUE THREAD

**Issue by fhg-isi** [PyPSA/PyPSA#1060]
For the tutorials commands like

`snakemake -call results/test-elec/networks/base_s_6_elec_lcopt_.nc --configfile config/test/config.electricity.yaml`

The argument "-call" does not seem to exist in snakemake. 

=> Please remove the argument or explain its meaning.

**Comment by fneum** [comment]
The option does exist: `snakemake -c all` which can also be written as `snakemake -call`.

(The issue would fit better in the PyPSA-Eur repository).
