### ISSUE TITLE
Make consistency check optionally strict

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#1109]
For some pypsa functions we need input that is already checked in the consistency checks. Therefore it would be good to have the consistency checks optionally in strict mode to raise an error instead of a warning. 

For example, for generalized plotting functions we need colors for all carriers defined. In the context of a soft consistency check this in `n.consistency_check()` would only lead to a warning. But for more complex plotting routines this should be a hard check and would raise an error. The trigger, could be an optional argument `strict`. I then would imagine to run code like  `n.consistency.check_carrier_colors(strict=True)`.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the consistency_check method to include a strict mode and add a new check_carrier_colors method in a new consistency module.

You can review changes in this commit: https://github.com/mnmnk43434/PyPSA-PyPSA-1109/commit/eebaf3214948d0290d4348301268e71ce440da09.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
