### ISSUE TITLE
LOPF with pyomo=False should also return shadow prices for fixed branches

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/PyPSA#119]
One inconsistency between nomopyomo and pyomo formulations is that pyomo also reads out the `mu_lower` and `mu_upper` shadow prices for non-extendable / fixed lines, transformers and links, whereas nomopyomo doesn't. The pyomo formulation does this by generating constraints for the fixed branches, see e.g.
https://github.com/PyPSA/PyPSA/blob/98f53ffa7fb02fae7172df3b61c86eab676fce11/pypsa/opf.py#L972
nomopyomo doesn't see these shadow prices, because the upper and lower limits are defined with the variable, rather than as extra constraints.

**Comment by FabianHofmann** [comment]
I see, I have a look at this soon.
