### ISSUE TITLE
Warn about limits of nomopyomo customizability

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/PyPSA#121]
In nomopyomo it's not possible to alter the objective function or existing constraints in extra_functionality, like it is in pyomo. To alter the objective function, one would have to set different marginal_costs everywhere to start with. We should provide guidance in the documentation.

**Comment by FabianHofmann** [comment]
Yes, altering existing objective or constraints does not really work. One suggestion for what one could do:

- add a keyword argument `skip_objective` (default `False`) which if `True` will lead to skip writing the default objective in the `prepare_lopf` but will require to add one's own objective in `extra_functionality`
- add a function `write_objective` in the `lopt` module (corresponding to `write_constraint`) which facilitates to write objective terms. This can also be used together with `skip_objective=False` if one simply wants to add terms to the default objective.

**Comment by fneum** [comment]
I second that the possibility to provide a custom objective (e.g. for my MGA stuff) would be really useful!

**Comment by FabianHofmann** [comment]
okay, if @nworbmot  does not oppose the suggestion, I would create a PR on this. @fneum you agree with the argument name?

**Comment by nworbmot** [comment]
Sounds good! I also want to alter the objective for some decomposition applications (well tell more next week).

**Comment by fneum** [comment]
@FabianHofmann `skip_objective=False` sounds reasonable.
