### ISSUE TITLE
Addition of Control strategies as attributes of Load and Storage_unit components

### ISSUE THREAD

**Issue by yama519** [PyPSA/PyPSA#122]
I think it is a nice idea to implement some Reactive Power Control strategies in pypsa. 

 Because as renewable energy utilization is increasing, number of inverters being integrated to the grid is also increasing through integration of renewable energy power plants, electric vehicle's, chp plants and maybe many more devices containing inverters in the future, which will cause voltage and current violations in the grid. Ex: if more renewable is comming to the grid voltage at the connection point will go higher than the normal range or in case of electric vehicles vice versa and same case for current.

To avoid such issues some inverter control strategies are considered to support the grid by providing reactive power or consuming reactive power in inverters in order to keep the voltage/current  in the allowed range. 

Currently, application of these strategies are done manually in pypsa by making a for loop and iterating for each snapshot and applying control strategy in each snapshot manually which takes time and also slows down the simulation. If they can be implemented in pypsa network main code, it helps alot in reducing the simulations time and code sizes.

idea:

My idea is to apply the control strategies as attributes in load and storage_units components. Because  renewable energy integration can come under load with negative p and also chp plants and electric vehicles come under load or storage_units. So if control strategies are implemented in load and storage unit components, they will consider the chosen control strategy in each snapshot be default and there is no need for further "for loops and iterations" after the power flow.

I have coded the control strategies and they are working fine. If you also think that it is a good idea, i am interested to implement them in pypsa main code. Any hint or examples regarding on how to do it in the main pypsa code would be appreciated.

**Comment by fneum** [comment]
@yama519 thanks for sharing your idea! If you have an initial concept of how this could be implemented cleanly in PyPSA, we'd be happy to review a [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) of yours. I think it's hard to give good hints before having seen a first issue, other than writing modular code and changing few lines of existing code.

Possibly related issues are #11, #43, and #76. Have a look whether you feel this is relevant and whether you can pick up some of the ideas.

**Comment by yama519** [comment]
@fneum 
Thanks from your reply and the hints provided. I will work on it.

**Comment by yama519** [comment]
@fneum 
Thank you for the provided hints,

Sofar i have applied some inverter based control strategies in pf.py file based on modular code. I applied the controller function  inside the for loop between lines 503 - 517 of pf.py flie.
 After applying my controller function i needed to rerun the already built in function namely " _calculate_controllable_nodal_power_balance" after my controller function, inorder to take the new p_set and q_set  and finally new p and q as inputs to the power flow. Withou running the function "_calculate_controllable_nodal_power_balance" after controller function changes due to controller reaction is not considered since p and q has their old values and are not updated, running this function updates them to their new values.

i need your hints for  OLTC transformer application in pf.py file. 
Since it is also expected that OLTC should react at each snapshot according to the input voltage, therefore I want to apply it in the same for loop of pf.py  file as other controllers are. 

But Applying OLTC in that for loop does not have any effect. It only changes the tap position in network.transformers data frame but has no effect on v_mag_pu of the buses which it must have. 

From my understanding there should be another built in function like the one i used for other controllers (_calculate_controllable_nodal_power_balance).
Please provide me some hints. 


here is the first three line of the for loop which i am talking about for your reference:

# starting from line 503 of pf.py file in github
for i, now in enumerate(snapshots): 
            # here comes my controller function and i want to apply oltc here as well
            p = network.buses_t.p.loc[now,buses_o]
            q = network.buses_t.q.loc[now,buses_o]
            ss[i] = s = p + 1j*q . . .

**Comment by yama519** [comment]
#185 
Hi @fneum 
I have completed some of the controllers which i proposed in this issue and created a pull request, so i close this issue, and continue following your feedbacks in my pull request.

Thanks from your cooperations :)

**Comment by fneum** [comment]
We can keep this open, until the linked PR is merged.
