### ISSUE TITLE
Add Binder support

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#143]
I am not sure if we already had the discussion but I think if would be very nice to add a binder badge to the readme for accessing interactive jupyter notebooks in a [binder project](https://mybinder.org/) (this is ready to use remote client with everything installed, so very nice for trying out examples). Here is an [example](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb).

**First of all**: what do you think of it?  

**Second** (if the resonance is positive): I would go for converting the [pypsa-examples](https://github.com/PyPSA/PyPSA/tree/master/examples) py files into jupyter notebooks. When no extensive plots are produced, it should be fine from the file size perspective.

**Comment by fneum** [comment]
I like it!

Most examples are already available as jupyter notebooks at https://pypsa.org/examples/index.html

**Comment by FabianHofmann** [comment]
Alright, then I set up a PR during the next days. Good that you point that out to me, those notebooks should definitely be included

**Comment by nworbmot** [comment]
Hi all, I'm just reopening this because the repo has got a bit messy:
- Some of the Jupyter notebooks are in the wrong folders (e.g. scigrid notebooks not in scigrid folder, similar for ac-de-meshed)
- What is "scigrid-lopf-then-pf.ipynb.1"?
- Do we need the folder "binder" with only one file in it?
In general, I think at least two people should review PRs before they're merged.

**Comment by FabianHofmann** [comment]
Hey, true it got a bit messy. Couple of suggestions:

* create an folder 'notebooks' in example which contains all the nbs which can be used via binder
* rename binder -> .binder ; unfortunately there is no other way for making the a proper installation without an extra folder, except for adding an environment.yml (not .yaml) which is parsed by the binder machine but then you end up with two different environment files 
* delete scigrid-lopf-then-pf.ipynb.1 which seems to be an artefact

**Comment by nworbmot** [comment]
Hey, no worries, these things happen.
- I'm fine with separate folder.
- If there has to be a directory, keeping "binder" is fine.
- Yes, delete that.
What do you thing @fneum?

**Comment by FabianHofmann** [comment]
Hey, I made the suggested changes. I think we can close this now

**Comment by fneum** [comment]
Just one more question: where can I get an `.rst` binder badge?
