### ISSUE TITLE
Separate line and link arguments in plot

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#144]
For new users, it is inconvenient and not very clear how to use the `line_colors` and `line_widths` argument in the plot function, when links or transformers are also plotted. It would be better to have separate arguments `line_colors` only for lines and `link_colors` for links and `transformer_colors`, same for `*_widhts`. 

**Optional**
One could have a `branch_colors` as an argument for containing colors for all branches in a mutliindexed Series

It is very hard to keep the backward compatibility for this change and might lead to some breaking cases...

**Comment by fneum** [comment]
I second that such a feature would make handling line plotting much easier and convenient!
I don't think the `branch_colors` / `branch_widths` would be necessary.
For backward compatibility, couldn't you check whether `line_colors`/`line_widths` is a `pd.MultiIndex`?

On the other hand don't we already have breaking changes for the next release (no `basemap`)?

**Comment by FabianHofmann** [comment]
> I don't think the `branch_colors` / `branch_widths` would be necessary.

Yes indeed.

> For backward compatibility, couldn't you check whether `line_colors`/`line_widths` is a `pd.MultiIndex`?

I'd say at least an error has to be raised which explains what has changed. So checking for Mutliindex makes definitely sense, also the case that `line_*`  is a dict with keys 'Link', 'Line'. 

> On the other hand don't we already have breaking changes for the next release (no `basemap`)?

Yes but there was an deprecation warning in former versions, in this case it would be really breaking. But I think it should be fine... let's see where it's heading

**Comment by fneum** [comment]
@nworbmot is planning a release this week. @FabianHofmann do you want this to be part of it or skip it for another version?

**Comment by FabianHofmann** [comment]
Alright, I'm taking care of this now :)
