### ISSUE TITLE
need version 0.17.0, so I can use 'skip_objective=True' ^^

### ISSUE THREAD

**Issue by tutu329** [PyPSA/PyPSA#151]
## Describe the feature you'd like to see

*Please give a clear and concise description and provide context why the feature would be useful.*
*Also, we'd appreciate any implementation ideas and references you already have.*

**Comment by fneum** [comment]
We‘ll do this soon. In the meantime you can instead install from the master branch: `git+https://github.com/PyPSA/pypsa.git#egg=pypsa`

**Comment by tutu329** [comment]
> We‘ll do this soon. In the meantime you can instead install from the master branch: `pip install git+https://github.com/PyPSA/pypsa.git#egg=pypsa`

thanks so much ^^
