### ISSUE TITLE
generator or link needs follow 2 or more types of loads

### ISSUE THREAD

**Issue by tutu329** [PyPSA/PyPSA#153]
i am simulating a CCHP optimise project with PyPSA which is really awesome. now i can not resume. because real cchp or heat pump can supply heat in winter and cold in summer，which may be better than boiler and air condition. but PyPSA gen or link does not support 2 or more types of loads, and link with 2 output also can not follow 2 buses load independently.need your help now.thanks a lot!

**Comment by fneum** [comment]
@tutu329 there might be a workaround.

So I assume you have three buses `electricity` (that connects to the grid, electrical generators, etc.), `heat` (with a heating demand time series), and `cold` (with a cooling demand time series).

You add two links which together will form your switchable heat pump, named `heatpump-heat` and `heatpump-cold`. Both connect to the `electricity` bus and their "load bus" (`heat` or `cold`).

One gets `capital_cost=0` while the other is assigned the actual capital cost.

Using the `extra_functionality` (see https://pypsa.readthedocs.io/en/latest/optimal_power_flow.html#overview and there has been repeated discussion on the mailing list https://groups.google.com/forum/#!forum/pypsa), you tie the investment variables for `p_nom` of `heatpump-heat` and `heatpump-cold` together. You can also add further constraints if you wish.

The drawback with this is that the model would allow you to supply heat and cold simultaneously. But if your demands for heat and cold are -- as likely is -- separated in time it shouldn't be a big issue.

This is just a sketch / a rough idea. You will have to see whether it is suitable for your application.

**Comment by tutu329** [comment]
thanks a lot. i have tried some methods like your suggest without extrafunc.




| |
陶佳
|
|
邮箱：jack.seaver@163.com
|

签名由 网易邮箱大师 定制

On 03/16/2020 03:48, Fabian Neumann wrote:

@tutu329 there might be a workaround.

So I assume you have three buses electricity (that connects to the grid, electrical generators, etc.), heat (with a heating demand time series), and cold (with a cooling demand time series).

You add two links which together will form your switchable heat pump, named heatpump-heat and heatpump-cold. Both connect to the electricity bus and their "load bus" (heat or cold).

One gets capital_cost=0 while the other is assigned the actual capital cost.

Using the extra_functionality (see https://pypsa.readthedocs.io/en/latest/optimal_power_flow.html#overview and there has been repeated discussion on the mailing list https://groups.google.com/forum/#!forum/pypsa), you tie the investment variables for p_nom of heatpump-heat and heatpump-cold together. You can also add further constraints if you wish.

The drawback with this is that the model would allow you to supply heat and cold simultaneously. But if your demands for heat and cold are -- as likely is -- separated in time it shouldn't be a big issue.

This is just a sketch / a rough idea. You will have to see whether it is suitable for your application.
