### ISSUE TITLE
bug when solving LOPF with unit_committment=False, but with defined ramping constraints

### ISSUE THREAD

**Issue by karolmitraszewski** [PyPSA/PyPSA#159]
Hi,

I've encountered a problem when trying to solve LOPF for my network.
I had `unit_committment = False` for all generators. 
However, for some of them I defined ramping constraints.
To simplify solution I followed an approach suggested in the German SciGrid example, namely to solve in a loop, each time for a small subset of snapshots.  

this resulted in an errors raised in 
line 355 & 409 [they are identical] of `opf.py`:
`status_prev = network.generators_t.status.at[network.snapshots[start_i-1],gen]`

The bottomline of the error was that `network.generators_t.status` was empty, not initialized [because unit_committment was not considered] and, consequently, the expression could not resolve properly.

Moving these these two lines inside the two `else ` clauses that follow right after solved the problem.

I don't feel confident enought to commit the bug fix myself. 
Please let me know whether signalling the issue here is enough, or should I make a pull request and commit the fix?

Karol

**Comment by fneum** [comment]
Thanks, your observation is correct. `status_prev` should be moved into the `else` clause, as it is only used for committable generators. See fix in PR #161.
