### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'real'

### ISSUE THREAD

**Issue by DaltonA123** [PyPSA/PyPSA#171]
## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate: yes

## The Script for: _Minimal 3-node example of PyPSA power flow_, the  _network.pf()_ function is unable to run, though the rest of the example script runs fine.

import pypsa

import numpy as np

network = pypsa.Network()

#add three buses
n_buses = 3

for i in range(n_buses):
    network.add("Bus","My bus {}".format(i),
                v_nom=20.)

print(network.buses)

#add three lines in a ring
for i in range(n_buses):
    network.add("Line","My line {}".format(i),
                bus0="My bus {}".format(i),
                bus1="My bus {}".format((i+1)%n_buses),
                x=0.1,
                r=0.01)

print(network.lines)

#add a generator at bus 0
network.add("Generator","My gen",
            bus="My bus 0",
            p_set=100,
            control="PQ")

print(network.generators)

print(network.generators.p_set)

#add a load at bus 1
network.add("Load","My load",
            bus="My bus 1",
            p_set=100)

print(network.loads)

print(network.loads.p_set)

network.loads.q_set = 100.

#Do a Newton-Raphson power flow
network.pf()

## Error Message
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['now'], dtype='object')
Traceback (most recent call last):

  File "C:\Users\22506381\Documents\Python\PyPSA-master\examples\minimal_example_pf.py", line 53, in <module>
    network.pf()

  File "C:\Users\22506381\AppData\Local\Continuum\anaconda3\lib\site-packages\pypsa\pf.py", line 153, in network_pf
    return _network_prepare_and_run_pf(network, snapshots, skip_pre, linear=False, x_tol=x_tol, use_seed=use_seed)

  File "C:\Users\22506381\AppData\Local\Continuum\anaconda3\lib\site-packages\pypsa\pf.py", line 122, in _network_prepare_and_run_pf
    itdf[sub_network.name], difdf[sub_network.name], cnvdf[sub_network.name] = sub_network_pf_fun(sub_network, snapshots=snapshots, skip_pre=True, **kwargs)

  File "C:\Users\22506381\AppData\Local\Continuum\anaconda3\lib\site-packages\pypsa\pf.py", line 327, in sub_network_pf
    roots[i], n_iter, diff, converged = newton_raphson_sparse(f,guess,dfdx,x_tol=x_tol)

  File "C:\Users\22506381\AppData\Local\Continuum\anaconda3\lib\site-packages\pypsa\pf.py", line 165, in newton_raphson_sparse
    F = f(guess)

  File "C:\Users\22506381\AppData\Local\Continuum\anaconda3\lib\site-packages\pypsa\pf.py", line 262, in f
    F = r_[mismatch.real[1:],mismatch.imag[1+len(sub_network.pvs):]]

  File "C:\Users\22506381\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'real'

**Comment by DaltonA123** [comment]
When Running the Minimal 3-node example of PyPSA linear optimal power flow I similarly get the following error:
  File "C:\Users\22506381\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\solver\shellcmd.py", line 118, in available
    raise ApplicationError(msg % self.name)

ApplicationError: No executable found for solver 'glpk'

**Comment by fneum** [comment]
`n.lopf()` requires an installed solver, see https://pypsa.readthedocs.io/en/latest/installation.html#getting-a-solver-for-linear-optimisation

What's your `pandas` version? `conda list pandas`.

**Comment by fneum** [comment]
@DaltonA123 you are not using the current master branch, but a version before #107 (which belongs to the release v0.16.0).

The line where your error occurs was changed in #107 to account for then upcoming breaking changes with `pandas==1.0.0`.

Please re-install pypsa in your activated environment. Hints at https://pypsa.readthedocs.io/en/latest/installation.html#installing-pypsa-with-conda

**Comment by spapaio** [comment]
'IndexedConstraint' object has no attribute '_index'
this error is coming out if i don't set the pyomo=False
any suggestion?

**Comment by fneum** [comment]
Please update to the latest PyPSA version, which is compatible with the latest pyomo version.

**Comment by spapaio** [comment]
still does not work even if i did update pypsa to the latest version(PyPSA
0.20.0).
It runs only if i set pyomo=False
e.g network.lopf(network.snapshots,pyomo=False)
otherwise i get the following error:

'IndexedConstraint' object has no attribute '_index'


Στις Πέμ 4 Αυγ 2022 στις 3:15 μ.μ., ο/η Fabian Neumann <
***@***.***> έγραψε:

**Comment by spapaio** [comment]
Hi Fabian, sorry for asking so many questions but could you help me out
with another error?

def extra_functionality(network,snapshots):
    gens_with_steps=[]
    step_0_gen_dict={}

    for gen in plants_list.keys():
        if plants_list[gen] is not None:
            for gen_step in plants_list[gen]:
                gens_with_steps.append(gen_step)
                step_0_gen_dict[gen_step]=plants_list[gen][0]

    step_status={(gen_step,sn) :
LConstraint(LExpression([(1,network.model.generator_status[gen_step,
sn]),(-1,network.model.generator_status[step_0_gen_dict[gen_step],
sn])]),"<=") for gen_step in gens_with_steps for sn in snapshots}

    l_constraint(network.model, "step_status", step_status,
                    list(gens_with_steps), snapshots)

after calling this function i get the following error:

name 'LConstraint' is not defined


Στις Τετ 10 Αυγ 2022 στις 12:31 μ.μ., ο/η sotiris pap ***@***.***>
έγραψε:

**Comment by FabianHofmann** [comment]
@spapaio please try not to mix topics in the GH issues, this makes it hard to keep the structure. 

As for the original problem. I cannot reproduce with the current master branch of `pypsa` and `Pyomo` `v6.4.1`, I am therefore keep the issue closed. Please only reopen if the *same* error reoccurs. 

As for the latest question (@spapaio), I think you haven't imported `LConstraint`. Just a general hint, always look at error messages and try to understand them. If the issue is really pypsa-related please open a new GH issue.
