### ISSUE TITLE
Unable to import pypsa from v0.16.0 to v0.17.0

### ISSUE THREAD

**Issue by ldemattos** [PyPSA/PyPSA#173]
#169  Checklist

- The error happen from releases 0.16.0 to 0.17.0. The release 0.15.0 is working fine.
- Python: 2.7.17
- OS: Ubuntu 18.04 over WSL
- Installation from pip

## Describe the Bug

When trying to import pypsa errors are returned:

## Error Message

Error for release 0.16.0:
```
$ python2 comp.py
Traceback (most recent call last):
  File "comp.py", line 19, in <module>
    import pypsa
  File "/home/leonardo/.local/lib/python2.7/site-packages/pypsa/__init__.py", line 29, in <module>
    from . import pf, opf, opt, plot, networkclustering, io, contingency, geo, stats
  File "/home/leonardo/.local/lib/python2.7/site-packages/pypsa/stats.py", line 29
    mc[c] = c.df @ c.pnl['p']
                 ^
SyntaxError: invalid syntax
```

Error for releases 0.16.1 and 0.17.0:
```
$ python2 comp.py
Traceback (most recent call last):
  File "comp.py", line 19, in <module>
    import pypsa
  File "/home/leonardo/.local/lib/python2.7/site-packages/pypsa/__init__.py", line 25, in <module>
    from . import components, descriptors
  File "/home/leonardo/.local/lib/python2.7/site-packages/pypsa/components.py", line 45, in <module>
    from .io import (export_to_csv_folder, import_from_csv_folder,
  File "/home/leonardo/.local/lib/python2.7/site-packages/pypsa/io.py", line 749
    logger.warning(f"Components {diff} for attribute {attr} of {cls_name} "
                                                                          ^
SyntaxError: invalid syntax
```

**Comment by fneum** [comment]
You are using Python 2.7. We have officially dropped support for Python 2 in release 0.16.1 as it retired 1 January 2020 https://www.python.org/doc/sunset-python-2/. If you are eager to continue in Python 2.7 you can still use PyPSA versions up to 0.16.0. However, I would recommend switching to Python 3.

**Comment by ldemattos** [comment]
Ok! Thanks for the heads-up. Is there anyway to prevent install releases after 0.15.0 from pip2? It would prevent cases like the ones I have reached.

**Comment by ldemattos** [comment]
Maybe something like this could be done on setup.py:

setup(
    ...
    python_requires='>=3',
    ...
)

https://stackoverflow.com/questions/42238484/prevent-package-from-being-installed-on-old-python-versions

**Comment by FabianHofmann** [comment]
good point

**Comment by FabianHofmann** [comment]
Closing this in the favour of #174
