### ISSUE TITLE
specify python version in setup.py

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#174]
As mentioned in #173 the python version should be specified in the `setup.py`

```python 
setup(
...
python_requires='>=3',
...
)
```

**Comment by coroa** [comment]
and all releases since 0.16.0 will have to be re-released with the flag, so that `pip install pypsa` on python 2 will correctly install 0.15.

**Comment by fneum** [comment]
Does anyone know how to re-release re. conda and pip and github?

**Comment by FabianHofmann** [comment]
closing due to the realistic conception that re-releasing takes longer on our side than the fixing this rare issue on the user side...
