### ISSUE TITLE
linopt: change find_spec of gurobi to gurobipy

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#175]
As discussed shortly in the mail list, it might be 'saver' to check for the package 'gurobipy' in the `linopt.py` module 

Thus change the `find_spec` in 
https://github.com/PyPSA/PyPSA/blob/7ece53e087df984f84c5a34917fe9a09cc5d8246/pypsa/linopt.py#L737

to 
```python 
find_spec('gurobipy')
```

So the question would be if there is any possible downsides to this.

**Comment by fneum** [comment]
I tend to agree. I still didn't quite get difference between `gurobi` and `gurobipy` fully.

You can import both (when using the conda package)
```
import gurobi
import gurobipy
```
And als `find_spec` finds both.

**Comment by lukasnacken** [comment]
My addition to that issue: I installed gurobi on a windows machine in two ways: (1)  using conda and (2) downloading from the gurobi site and running python setup.py. In both cases I can only import gurobipy. 
(For the command line there is also the executable gurobi.bat in the system path of gurobi. Apart from that, i have no idea why you can import gurobi within python.)

**Comment by lukasnacken** [comment]
Hi, again. On a linux machine I have seen that the "gurobi" python package simply consists of an init file with "from gurobipy import *"... :)

**Comment by fneum** [comment]
Sounds convincing to me.
