### ISSUE TITLE
add sklearn to package requirements

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#177]
As the kmeans clustering is pretty often used, we should enable it by default. However it requires the scikit-learn package to be available, which in not in the pip nor in the conda requirements nor in the environment.yaml. It would probably make sense to add the dependency there.

**Comment by fneum** [comment]
Or make it an optional dependency? Like the solvers? It's only used for network clustering.

```py
if find_spec('sklearn') is None:
    raise ModuleNotFoundError("Optional dependency 'sklearn' not found."
           "Install via 'conda install -c conda-forge scikit-learn' "
           "or 'pip install scikit-learn'")
import sklearn....
```

**Comment by fneum** [comment]
Also here the question: should this be part of 0.17.1?
