### ISSUE TITLE
add shadow prices for fix generators

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#180]
`pypsa` does not give back shadow prices for non-extendable generators, however for non-extendable branches. One could generalize this behaviour to all components by defining the `define_dispatch_for_non_extendable_variables` function as 

```python 
def define_dispatch_for_non_extendable_variables(n, sns, c, attr):
    fix_i = get_non_extendable_i(n, c)
    if c == 'Generator':
        fix_i = fix_i.difference(n.generators.query('committable').index)
    if fix_i.empty: return
    nominal_fix = n.df(c)[nominal_attrs[c]][fix_i]
    min_pu, max_pu = get_bounds_pu(n, c, sns, fix_i, attr)
    lower = min_pu.mul(nominal_fix)
    upper = max_pu.mul(nominal_fix)
    axes = [sns, fix_i]
    dispatch = define_variables(n, -inf, inf, c, attr, axes=axes, spec='non_ext')
    dispatch = linexpr((1, dispatch))
    define_constraints(n, dispatch, '>=', lower, c, 'mu_lower', spec='non_ext')
    define_constraints(n, dispatch, '<=', upper, c, 'mu_upper', spec='non_ext')

```
in the nomopyomo setting 

This is useful for understanding the composition of the market price at a given bus.

**Comment by fneum** [comment]
I think the consistency would definitely make sense! The idea is to just omit this if/else right?

https://github.com/PyPSA/PyPSA/blob/f21b81d62e08f2730e3f17498b79423a47eb4296/pypsa/linopf.py#L111-L118

**Comment by fneum** [comment]
@FabianHofmann due to #190 we should do a new release soon. If this is an easy TODO we can consider putting it in.
