### ISSUE TITLE
CPLEX n.ilopf() with non-basic solution

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#182]
## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

Reposted from mailing list "Using the CPLEX solver".

The function `n.ilopf()` requires the solver settings to produce a basis (or at least not error when trying)

https://github.com/PyPSA/PyPSA/blob/d48f78db9f485c94b941b8656a862ca73d88e726/pypsa/linopf.py#L1015

For CPLEX this produces the error message below (will try to get line references).

Would probably make sense to check if `m.solution.basis` exists in `run_and_read_cplex()`, before writing?

https://github.com/PyPSA/PyPSA/blob/d48f78db9f485c94b941b8656a862ca73d88e726/pypsa/linopt.py#L712-L714

The `run_and_read_gurobi()` funciton handles this error.

https://github.com/PyPSA/PyPSA/blob/d48f78db9f485c94b941b8656a862ca73d88e726/pypsa/linopt.py#L762-L768

What do you think @FabianHofmann? This should work analogous for CPLEX, right?

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
cplex.exceptions.errors.CplexSolverError: CPLEX Error  1262: No basis exists.
```

**Comment by FabianHofmann** [comment]
Right! I somehow assumed that Cplex algorithms always produce a basis. But it seems that this [is not the case](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.7.1/ilog.odms.cplex.help/CPLEX/Parameters/topics/SolutionType.html). We should handle it the same way as in `run_and_read_gurobi`

**Comment by fneum** [comment]
Ok, I'll quickly do the PR.
