### ISSUE TITLE
kmeans clustering with different lines.s_max_pu values

### ISSUE THREAD

**Issue by ClaraBuettner** [PyPSA/PyPSA#187]
I want to use the line-attribute 's_max_pu' to represent n-1 factor. The grid contains lines from hv- and ehv-level, which have different n-1 factors. This causes an error when I try to apply kmeans clustering: 

`AssertionError: In Bus cluster s_max_pu the values of attribute s_max_pu do not agree:`

I think it would be possible to consider s_max_pu in line aggregation by adding 
`s_max_pu=(l['s_max_pu']* _normed(l['s_nom'])).sum()`
to the aggregatelinegroup function here:
https://github.com/PyPSA/PyPSA/blob/fa63e72dc14969bed48fe480c99a76518d822942/pypsa/networkclustering.py#L182-L198

**Comment by fneum** [comment]
Sounds plausible. I'll add it soon for Release 0.17.1.
