### ISSUE TITLE
MILP OPF objective function value

### ISSUE THREAD

**Issue by jdedecca** [PyPSA/PyPSA#20]
For MILP problems the lower bound of the problem is the relaxed/best bound, at least in CPLEX. Thus the objective value of network.results["Problem"][0]["Lower bound"] for unit commitment problems is lower than the integer objective value. For MILP problems network.results["Problem"][0]["Upper bound"] can retrieve the correct value.
This can be verified in the unit-commitment test file by disabling any problem presolve and introducing a large enough optimality gap tolerance, in order to generate different upper and lower bounds. e.g. for CPLEX:

nu.lopf(nu.snapshots, solver_name='cplex', solver_options={'mip_tolerances_mipgap': 0.5,'preprocessing_presolve':'no'})

With tee=True in the opf.py file there will be a difference in the upper and lower bounds.

[opf.txt](https://github.com/FRESNA/PyPSA/files/1246265/opf.txt)
[unit-commitment.txt](https://github.com/FRESNA/PyPSA/files/1246266/unit-commitment.txt)

**Comment by nworbmot** [comment]
Sorry for delay. Is your suggestion then to replace "Lower bound" with "Upper bound"? We have no problem with this, we did all the testing on continuous problems where it was not so important...

**Comment by jdedecca** [comment]
Indeed, that is the suggestion - it would be necessary for UC problems.

**Comment by nworbmot** [comment]
This was fixed in commit https://github.com/PyPSA/PyPSA/commit/51fda3d66114c6160edd0212fd627d06fd9a6bf2

Sorry it took so long...
