### ISSUE TITLE
Make documentation of p_set clear

### ISSUE THREAD

**Issue by Brytni-Johnston** [PyPSA/PyPSA#202]
Hello,

First, thanks for this project!

I was wondering if it would be possible to use generator p_set in opf (currently only used in pf). This seems to me like something not that hard to do considering state_of_charge_set is used in opf and it's a similar set of equations. It would be very useful to be able to fix the output of certain generators. (The other constraints would still serve to ensure that the p_set is within operating limits). 

At the very least, make a note in the [opf documentation](https://pypsa.readthedocs.io/en/latest/optimal_power_flow.html) that p_set is not considered for generators because I spent way too long not understanding why my code wasn't working :( 

Thanks,
Brytni

**Comment by fneum** [comment]
@Brytni-Johnston apologies that the documentation was not clear for you. The attribute `p_set` is indeed only used for power flow and not for optimal power flow as noted at https://pypsa.readthedocs.io/en/latest/components.html#generator. You can achieve the same functionality by setting p_max_pu = p_min_pu; e.g. if your generator capacity is 100 MW and your output should be 80 MW, set p_min_pu = 0.8 and p_max_pu = 0.8.

**Comment by Brytni-Johnston** [comment]
Of course this is possible, I just think it would be nice to have a more intuitive and streamlined method. :)

**Comment by FabianHofmann** [comment]
I agree, the `pyomo=False` code foresees this structure in https://github.com/PyPSA/PyPSA/blob/fdaf7460b7e31bc9c4b6cc83d6236d37b61530a3/pypsa/linopf.py#L621
however, we did not enable it so far, as this would break with the implementation of the pyomo-based solving. However, I think future versions will very likely set pyomo to `False'. Then diverging from the old default might is not an issue anymore, if well documented.

**Comment by fneum** [comment]
`p_set` is now enforced as fixed profile:

https://github.com/PyPSA/PyPSA/blob/1f353f8ca8f4b23dd79b5f196cf4b959b40f2767/pypsa/optimization/optimize.py#L275
