### ISSUE TITLE
set_snapshots replaces all time dependent data with the default value (wheather they are NaNs or not)

### ISSUE THREAD

**Issue by OriolRaventos** [PyPSA/PyPSA#203]
Using PyPSA version 0.17.0 (with pip install in a new enviorment), the function network.set_snapshtos fills all time dependent data with the default value (wheather they are NaNs or not). You can reproduce the issue with the following code:

```
import pypsa
import os
import pandas as pd

csv_folder_name = os.path.dirname(pypsa.__file__) + "/../examples/scigrid-de/scigrid-with-load-gen-trafos/"

network = pypsa.Network(csv_folder_name=csv_folder_name)

print(network.loads_t.p_set['1'])

network.set_snapshots(pd.date_range(start=str(2016)+'-01-01 00:00:00',periods=24,freq='H'))

print(network.loads_t.p_set['1'])
```

The issue is the use of reindex here:

https://github.com/PyPSA/PyPSA/blob/fdaf7460b7e31bc9c4b6cc83d6236d37b61530a3/pypsa/components.py#L385

and

https://github.com/PyPSA/PyPSA/blob/fdaf7460b7e31bc9c4b6cc83d6236d37b61530a3/pypsa/components.py#L392

which has the expected but undesired behavior:

https://stackoverflow.com/questions/35108046/python-reindex-producing-nan

https://pypsa.readthedocs.io/en/latest/api_reference.html?highlight=set_snapthots#pypsa.Network.set_snapshots

and could be solved **assuming that the new and old snapshots have the same length** by changing the lines into

```
network.snapshot_weightings.index = network.snapshots
network.snapshots_weightings = network.snapshot_weightings.fillna(1.)
```
and
```
pnl[k].index = network.snapshots
pnl[k] = pnl[k].fillna(default)
```
respectively.

**Comment by FabianHofmann** [comment]
@OriolRaventos thank you for the detailed description. 
You're proposition assumes that the new snapshots are of the same length as the old, and the user only wants to overwrite them. This breaks as soon as the user wants to select a subset of the network.snapshots. Also, the behavior of pandas's `reindex` in that case is not as undesired as one might think. The fact that data entries are assigned to fixed data indeces, allows for a transparent handling/tracking of missing data.

**Comment by OriolRaventos** [comment]
I agree that the proposed solution does not cover all the features one would like to have (like crop or extend the given snapshots) and that the ```set_snapshots```  descriptions states that _all pandas will be reindex_ (so in the pandas context it states precisely what it does). Hence, I'm close the issue. Nevertheless, changing the year of the snapshots might be a desirable feature for the function ```set_snapshots``` (or maybe introduce another function, since the current function just crops or extends-by-default-values the current snapshots).

**Comment by FabianHofmann** [comment]
Yes, this is a good idea. Perhaps something like a `shift_snapshots` or a `overwrite_snapshots` function would be nice
