### ISSUE TITLE
Problem with error module 'pypsa' has no attribute 'Network'

### ISSUE THREAD

**Issue by agaa2** [PyPSA/PyPSA#207]
Hello, I'm starting with pypsa and I can solve the problem with AttributeError: module 'pypsa' has no attribute 'Network_module'

Did someone struggled with the same issue? 
Best Regards
Agnieszka 

## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
<paste here>
```

**Comment by pz-max** [comment]
Hi Agi,
A bit more of the code from the jupyter/terminal would help. :)
I assume you have some problems with the workflow.
Fabian shared a great video here: [https://www.youtube.com/watch?v=mAwhQnNRIvs&t=182s](https://www.youtube.com/watch?v=mAwhQnNRIvs&t=182s)
Hopefully that helps you to get the model run.

**Comment by agaa2** [comment]
Hi!
I have already solved it, thanks a lot. I didn't downloaded necessary data
bundle to execute network snakemake.
Thank you a lot!


sob., 12 gru 2020 o 00:28 Max Parzen <notifications@github.com> napisał(a):
