### ISSUE TITLE
Preprocessing for SciGrid (gas) data

### ISSUE THREAD

**Issue by stefaneidelloth** [PyPSA/PyPSA#214]
There is an example notebook using **SciGrid electricity data**:
https://www.pypsa.org/examples/scigrid-lopf-then-pf.html

Instead of using the SciGrid data directly, the example notebook reads csv files from following directory as input:
https://github.com/PyPSA/PyPSA/tree/master/examples/scigrid-de/scigrid-with-load-gen-trafos

=> A **preprocessing** step is required to convert the SciGrid data.
The script [add_load_gen_trafos_to_scigrid.py](https://github.com/PyPSA/PyPSA/blob/master/examples/scigrid-de/add_load_gen_trafos_to_scigrid.py) seems to be responsible for reading [scigrid-151109](https://github.com/PyPSA/PyPSA/tree/master/examples/scigrid-de/scigrid-151109) and
converting it to [scigrid-with-load-gen-trafos](https://github.com/PyPSA/PyPSA/tree/master/examples/scigrid-de/scigrid-with-load-gen-trafos).

The script includes following warning:
**WARNING: This script is no longer supported, since the libraries and data no longer exist in their former versions**

=> Could you please provide an **up to date preprocessing script** for SciGid electricity data, that is able to handle
the current version (e.g. scigrid\data\03_network\links_de_power_160718.csvdata, available from `git clone http://git.scigrid.de scigrid`) ? 

=> Could you please also provide some similar preprocessing script for **SciGrid gas data** and a notebook demonstrating how to use it ( https://www.gas.scigrid.de/downloads.html ) with PyPSA?

**Comment by fneum** [comment]
Yes, the SciGrid electricity network data has not been touched in years. While we still use it as an example and for testing (no problem here if the data is quite not up to date), for modelling the European electricity transmission network we have switched to using PyPSA-Eur: https://github.com/pypsa/pypsa-eur, https://pypsa-eur.readthedocs.io. This is also suitable for studying the German system alone.

Was there any particular reason you wanted to use the SciGrid electricity data? It seems the newest version is also almost 5 years old. If you need it, we can't do this work for you, but you may ask us about some specific errors you encounter while trying to adapt the scripts.

Regarding the SciGrid gas data, we are currently in the process of assessing the data quality as the project comes to a close, but it will surely be incorporated in our models one way or the other. You will find updates on this here: https://github.com/PyPSA/pypsa-eur-sec, https://pypsa-eur-sec.readthedocs.io/en/latest/release_notes.html, https://github.com/PyPSA/pypsa-eur-sec/issues/6. In principle, we will initially build the gas network as `links` with gas `buses`.

**Comment by stefaneidelloth** [comment]
Thank you for clarifying the situation and linking the corresponding pypsa-eur-sec ticket.
