### ISSUE TITLE
Solve using lopf, invalid value encountered in sub_network.

### ISSUE THREAD

**Issue by eschrad** [PyPSA/PyPSA#218]
## Checklist

I am using the latest release: 0.17.1

## Describe the Bug

I'm trying to solve my network with network.lopf(), but I'm getting a long list of errors (see below). It goes on a lot longer, but this part repeats itself. In my network I have buses (v_nom, v_min), generators (carrier, marginal cost, p_nom), loads (p_set) and lines (bus0, bus1, s_nom, length, num_parallel). 

As for as I know, I'm not using any subnetwork, so I'm unsure what the errors is referring to. Any help on what I'm doing wrong would be greatly appreciated. 

## Error Message

```
home/XXX/.local/lib/python3.9/site-packages/pypsa/pf.py:852: RuntimeWarning: divide by zero encountered in true_divide
  b = 1./np.concatenate([(c.df.loc[c.ind, attribute]).values \
/home/XXX/.local/lib/python3.9/site-packages/pypsa/pf.py:869: RuntimeWarning: invalid value encountered in multiply
  sub_network.p_branch_shift = -b*np.concatenate([(c.df.loc[c.ind, "phase_shift"]).values*np.pi/180. if c.name == "Transformer"
...
```

**Comment by fneum** [comment]
This looks like your line impedances are not given. They default to zero (hence divide by zero encountered) but must be non-zero for AC branches in linear power flow settings.

Sub-networks are automatically generated. Sub-networks are subsets of buses and passive branches (i.e. lines and transformers) that are connected. https://pypsa.readthedocs.io/en/latest/components.html#sub-network
