### ISSUE TITLE
Remove pypsa.stats module and move parts into unit testing

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#234]
But how about removing the `stats` module? It was only introduced due to counter-testing the linopf module.

_Originally posted by @FabianHofmann in https://github.com/PyPSA/PyPSA/issues/230#issuecomment-831124267_

Sounds good! Maybe we could reuse some of the functions from stats for unit tests?

_Originally posted by @fneum in https://github.com/PyPSA/PyPSA/issues/230_

**Comment by FabianHofmann** [comment]
already done
