### ISSUE TITLE
error using  import_from_csv_folder (network, csv_folder_name)

### ISSUE THREAD

**Issue by pimanc** [PyPSA/PyPSA#238]
Hello, I am using the latest release 0.17.1

I have two bugs using the  import_from_csv_folder function. 
Here is the code I wrote to call the function: 
`network = pypsa.Network` 
` csv_folder_name = 'csv_pypsa'` 
` network.import_from_csv_folder(network, csv_folder_name)` 

I created several csv files following the example of ac-dc-meshed example given in your github
1) the first one is while importing the newtork.csv: the file is attached
I receive the error: 
`line 557, in _import_from_importer
    current_pypsa_version = [int(s) for s in network.pypsa_version.split(".")]
AttributeError: type object 'Network' has no attribute 'pypsa_version'`

I managed to fix this bug, by adding in the io.py file before line 556 the following: 
`network.pypsa_version = '0.17.1'`
Which is not the cleanest way I must admit! but it works.

2) the second problem is right after this one was fixed, I receive the error: 
`line 585, in _import_from_importer
    network.set_snapshots(df.index)
TypeError: set_snapshots() missing 1 required positional argument: 'snapshots'`

the CSV snapshots is attached
I tried to fix the issue by changing the line 585 in io.py:
`network.set_snapshots(snapshots=df.index)` instead of `network.set_snapshots(df.index)`
which gives the following error: 

`line 584, in _import_from_importer
    network.set_snapshots(snapshots=df.index)
TypeError: set_snapshots() missing 1 required positional argument: 'self'`

Maybe is there something that I am missing? 

thank you for your help! 
Grüße
[network.csv](https://github.com/PyPSA/PyPSA/files/6452228/network.csv)
[snapshots.csv](https://github.com/PyPSA/PyPSA/files/6452229/snapshots.csv)

**Comment by fneum** [comment]
Instantiating the network will solve your problem:

```py
network = pypsa.Network() # you forgot the ()
csv_folder_name = 'csv_pypsa'
network.import_from_csv_folder(network, csv_folder_name)
```

BTW, you can also use

```py
network = pypsa.Network('csv_pypsa')
```

to do the same.
