### ISSUE TITLE
pyomo=False

### ISSUE THREAD

**Issue by csaiedu** [PyPSA/PyPSA#239]
Using the tutorial example with pyomo=False the optimization fails systematically with 'cbc' or 'glpk' solvers.

import pypsa
import numpy as np

network = pypsa.Network()

for i in range(3):
    network.add("Bus","My bus {}".format(i))

for i in range(3):
    network.add("Line","My line {}".format(i),
                bus0="My bus {}".format(i),
                bus1="My bus {}".format((i+1)%3),
                x=0.0001,
                s_nom=60)

network.add("Generator","My gen 0",
            bus="My bus 0",
            p_nom=100,
            marginal_cost=50)

#add a generator at bus 1
network.add("Generator","My gen 1",
            bus="My bus 1",
            p_nom=100,
            marginal_cost=25)

network.add("Load","My load",
            bus="My bus 2",
            p_set=100)

network.lopf(pyomo=False,solver_name='cbc')

**Comment by fneum** [comment]
Do you have an error message?

**Comment by fneum** [comment]
Code runs correctly for me:

```
INFO:pypsa.linopf:Prepare linear problem
INFO:pypsa.linopf:Total preparation time: 0.1s
INFO:pypsa.linopf:Solve linear problem using Cbc solver
INFO:pypsa.linopf:Optimization successful. Objective value: 3.00e+03
Out[3]: ('ok', 'optimal')
```

Did you install the solver?

`conda install -c conda-forge coincbc`

**Comment by fneum** [comment]
Please reopen if not solved.
