### ISSUE TITLE
Doc: Use autodocsumm or automodapi for api references

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#248]
There are functions in the doc who are referenced in the doc texts using `automethod`.  This makes the texts a bit hard to read. I suggest to move all function references to the "api references" section and make a link to those at places where they are referred to. 

Any opposing opinions?

**Comment by fneum** [comment]
Yes, we can use `autosummary` instead. I found a nice sphinx extension `autodocsumm` to make the API Reference prettier, too.

**Comment by fneum** [comment]
superseded by work of @lkstrp
