### ISSUE TITLE
unable to turn of lopf logging 

### ISSUE THREAD

**Issue by tharwan** [PyPSA/PyPSA#25]
I have an issue with the logging output generated from lopf. It also reproduces In the logging demo (https://pypsa.org/examples/logging-demo.html). 

If I change input 5 to: 
`pypsa.opf.logger.setLevel(logging.ERROR)`

I would expect no output after input 6. However I get the same output as when the warning level was set. 

Only setting it to logging.NOTSET will surpress the output again.

**Comment by nworbmot** [comment]
I confirm the issue but have no solution. The output there is from Pyomo (or GLPK?), not PyPSA, so it's probably some bad interaction between Pyomo and the logger.
