### ISSUE TITLE
Rename io.py to _io.py

### ISSUE THREAD

**Issue by fleimgruber** [PyPSA/PyPSA#250]
## Describe the feature you'd like to see

When trying to debug PyPSA in PyCharm, I hit the errors described [here](https://stackoverflow.com/questions/51950533/fatal-python-error-init-sys-streams-cant-initialize-sys-standard-streams-attr) (see also comments to OP).

Renaming `pypsa/io.py` to `pypsa/_io.py` would solve this.

**Comment by fneum** [comment]
The solutions seem to suggest that the issue was not the file name but the PYTHONPATH, no?

**Comment by fleimgruber** [comment]
Thanks for pointing this out and sorry for the noise, seems I did not read all of it. I think I hit https://stackoverflow.com/questions/26569828/pycharm-py-initialize-cant-initialize-sys-standard-streams, will check that - closing predictively.

**Comment by fneum** [comment]
No worries!
