### ISSUE TITLE
Fixed cost parameter for power plants

### ISSUE THREAD

**Issue by samarthiith** [PyPSA/PyPSA#276]
Dear pyPSA team,
I am working with pyPSA for modelling investment and dispatch. Currently, generators do not have a fixed cost parameter. So to model endogenous dis-investment we are modelling it by creating two separate kinds of power plants (legacy and new) and provide different capital costs (fixed and capital cost). Would be very useful to have a fixed cost attribute in the generators in addition to capital_cost. 
thanks,

**Comment by fneum** [comment]
I think working with two generators is a good way of doing it here. This gives you the flexibility to also tune other techno-economic parameters; e.g. a new generator might have higher efficiency etc.

A fixed cost ($ not $/MW) would also introduce binary variables.
