### ISSUE TITLE
Add missing qutation marks in lines.csv 

### ISSUE THREAD

**Issue by phil-fzj** [PyPSA/PyPSA#280]
## Checklist

- [ x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

There are missing quotation marks in the [lines.csv](https://github.com/PyPSA/PyPSA/blob/master/pypsa/component_attrs/lines.csv) file.
Lines **6 and 7** (for x and r) don´t have the part for the description column in quotation marks. 
This moves most of the description in to the next column ('status' column). Instead of _**"Input (required)"**_ the status column now starts with _**"must be non-zero for AC branch in ..."**_ (also visible in the documentation. see [Line](https://pypsa.readthedocs.io/en/latest/components.html#line))

This causes e.g. problems when using the functions in [networkclustering.py](https://github.com/PyPSA/PyPSA/blob/master/pypsa/networkclustering.py), specifically 

>def aggregatelines(network, buses, interlines, line_length_factor=1.0):
> [...]
> columns = set(attrs.index[attrs.static & attrs.status.str.startswith('Input')]).difference(('name', 'bus0', 'bus1'))

The reactance (x) and resistance (s) are not added to the columns variable since their attribute status does not start with "Input".
As a consequence the reactance is not calculated for the aggregated lines.

## Error Message

none

**Comment by martacki** [comment]
Thanks for pointing that out! Do you want to make a separate pull request to fix this issue? If not, I will go ahead.

**Comment by martacki** [comment]
we'll need a pull request for that commit, can't merge a commit to your fork ...

**Comment by phil-fzj** [comment]
yes, sorry. I did not have the time earlier to finish this
