### ISSUE TITLE
Add a network attribute `n.meta` to store e.g. configs in dictionary

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#291]
It would be useful to have an `n.meta` attribute that is initialised with an empty dictionary.

This could for example store information on whether the network was solved successfully or the `config.yaml` from PyPSA-Eur(-Sec).

Question to solve: How good can dictionaries be stored in NetCDF format.

**Comment by fneum** [comment]
Let’s checkout how xarray does it (x.attrs)

**Comment by FabianHofmann** [comment]
Good idea. Should we add this to the milestone 0.19? First start could be:

```python
@property
def meta(self):
    return self._meta

@meta.setter(self, new):
    if not isinstance(new, (dict, Dict)):
       raise TypeError(f"Meta must be a dictionary, received a {type(new)}")
    self._meta = new
```
but we have to check that dict values are actually writable to netcdf. Same accounts for setting values directly: 
```
n.meta["series"] = pd.Series([])
```
which should for example raise an error.
