### ISSUE TITLE
readthedocs build fails with Excess Memory error with current .conda install

### ISSUE THREAD

**Issue by henri-chat-noir** [PyPSA/PyPSA#305]
Since this not a bug in PyPSA operation per se, I'll post as feature request.  (My fork is such a mess that I don't think it's realistic to try to execute incremental changes via PR, so trying this route.)

I'd recommend we a) switch to PIP for rtd build (not conda), and b) reduce the import packages in a requirements_docs.txt file to 'bare minimum' as follows:
1.  Might as well change .readthedocs.yml to .readthedocs.yaml.  (Previous file extension has been deprecated by rtd -- see https://docs.readthedocs.io/en/stable/config-file/index.html

2. The version (as a .txt extension as GH doesn't support .yaml file attachment) I've attached worked fine for me as to shifting pip install (not sure Python version you want to run with) and directing rtd to a (new) requirements_docs.txt in the \doc sub-directory

3. I was able to get a successful build importing (only) the following in requirements_docs.txt.  (I didn't bother with version specs, not sure if you guys do/would.):
ipykernel
nbsphinx
nbsphinx_link
pypsa

4. This was with `nbsphinx_allow_errors = True` added to conf.py, which I noticed was recent change in main branch anyway.

[.readthedocs.txt](https://github.com/PyPSA/PyPSA/files/7403403/default.readthedocs.txt)

**Comment by fneum** [comment]
Thanks for the suggestions. It seems the memory errors have been solved by readthedocs by using mamba as drop-in replacement for conda: 1f886fc4da1562a1624c31f8a62fbf459180799b
