### ISSUE TITLE
Bus marginal prices incorrect?

### ISSUE THREAD

**Issue by dshen109** [PyPSA/PyPSA#311]
## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch

## Describe the Bug

I am testing a scenario where generators update their snapshots of their marginal prices to submit different bids as the simulation progresses. I have constructed a test case with two plants, one bus, and one load. One of the plants doubles its marginal price snapshots halfway through the simulation. The simulation seems to obey the ramp rate constraints and do dispatch correctly, but the marginal price predictions at the bus are very strange -- sometimes they're more than the marginal cost of any generator, and sometimes they're negative.

Also, in general, is directly modifying params using `network.pnl` the appropriate way to achieve this goal?

```python
import numpy as np
import pandas as pd
import pypsa

times = pd.date_range('2021-01-01 00:00', '2021-01-01 01:59', freq='5T')

loads = pd.DataFrame({'load': [240, 245, 250, 260, 270, 250] * (len(times) // 6)},
                     index=times)

coal_nominal = 350
gas_nominal = 20

coal_ramp_up = 140/coal_nominal/12
coal_ramp_down = 140/coal_nominal/12
gas_ramp_up = 90 / gas_nominal /12
gas_ramp_down = 100/ gas_nominal / 12

network = pypsa.Network(snapshots=times)
network.add('Bus', 'bus1')
network.add('Generator', 'gas1', bus='bus1', committable=False,
            marginal_cost=28.967, p_nom=20, ramp_limit_up=gas_ramp_up,
            ramp_limit_down=gas_ramp_down)
network.add('Generator', 'coal1', bus='bus1', committable=False,
            marginal_cost=[26.2131, 29] * (len(times) // 2), p_nom=350,
            ramp_limit_up=coal_ramp_up, ramp_limit_down=coal_ramp_down)
network.add('Load', 'load1', bus='bus1',
            p_set=loads.values.flatten().tolist())

overlap = 8
costs = []
for i in range(len(times) - overlap):
    print(f'running iteration {i}')
    # Double the cost of coal to test updating marginal prices halfway through
    if i == len(times) // 2:
        network.pnl('Generator')['marginal_cost']['coal1'].iloc[i:] *= 2
    costs.append(network.generators.marginal_cost)
    network.lopf(network.snapshots[i:i + overlap + 1], pyomo=True)


outputs = pd.concat({'Active':network.generators_t.status.astype(bool),
                     'Output': network.generators_t.p,
                     'Marginal Cost': network.generators_t.marginal_cost,
                     'Load': network.loads_t.p,
                     'Price': network.buses_t.marginal_price}, axis=1)

import matplotlib.pyplot as plt
plt.plot(outputs['Price'])
plt.legend(['marginal price, bus1'])
ylim = plt.ylim()
plt.twinx()
plt.plot(outputs['Marginal Cost'], 'r')
plt.ylim(ylim)
plt.legend(['marginal cost, coal'])
```

![image](https://user-images.githubusercontent.com/36486449/141344326-ff37440d-4b48-453a-887b-2bf1d84ff239.png)
![image](https://user-images.githubusercontent.com/36486449/141344342-a63699b1-b79b-4bd7-b792-3824ad210eda.png)

**Comment by Demcorazy** [comment]
This is not bug, and is caused by the specific data.
suppose that incresing one MW of load at 01:00, then the load can allow gas1 to produce one more MW, which will supply the sequent hours load, and coal1 may reduce its output.Since coal1 doubles its marginal cost and is more expensive than gas1, so the total system cost will be reduced, which cause a negtive marginal price at 01:00.

![image](https://user-images.githubusercontent.com/28104765/144432564-c3f95f2d-ec08-4e51-b7ed-fcad0b3b20af.png)

**Comment by FabianHofmann** [comment]
@Demcorazy thanks for clarifying. 
@dshen109 just to underline, the marginal prices are not something pypsa calculates, but are a direct result of the optimization (dual values).  Please reopen of things still remain unclear.
