### ISSUE TITLE
plot.py with bus_sizes as Series causes error if all components of bus_sizes at one bus are 0

### ISSUE THREAD

**Issue by jankaeh** [PyPSA/PyPSA#32]
I added 3 lines to avoid this:
https://github.com/PyPSA/PyPSA/compare/master...jankaeh:patch-1

By the way:
If I use network.plot() with MultiIndex bus_sizes, the circles at the buses are elliptic if the axes are not equal. With non-MultiIndex bus_sizes they are circles despite changed proportions. Is there a simple solution to create elliptic wedges dependent on the plot proportions or any other solution for this?

**Comment by coroa** [comment]
Thanks for the patch, we'll add it soon.

To comment on your "by the way": There does not appear to be a simple solution. The least intrusive one, i believe would be to build a [transformation](https://matplotlib.org/users/transforms_tutorial.html), that rescales the coordinates around the pie center-point to counter the axes ratio. This transformation would have to be updated, when the axes are rescaled.

Something along the following lines, but can't test now.

```python
def rescale_pie(pie, ax, x, y):
    def update_transform(event):
        dx, dy = np.diff(ax.transData.transform([(0, 0), (1, 1)]))
        t = IdentityTransform().translate(-x, -y).scale(1./dx, 1./dy).translate(+x, +y)
        pie.set_transform(ax.transData + t)

    update_transform(None)

    fig.canvas.mpl_connect('resize_event', update_transform)
    ax.callbacks.connect('xlim_changed', update_transform)
    ax.callbacks.connect('ylim_changed', update_transform)

pie = ax.pie(x, y, ...)
rescale_pie(pie, ax, x, y)
 ```
