### ISSUE TITLE
linopf doesn't report time-dependent optimisation results if components are added after an optimisation

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/PyPSA#331]
The `pyomo=False` version of LOPF in `linopf` has a small bug. If you:

- run an optimisation
- then add a generator/link/store
- rerun the optimisation
- then the time-dependent variables (p, p1) for the new components are not saved in `n.generators_t.p` etc

In the old code in `opf.py` a function called `allocate_series_dataframes` from `descriptors.py` was called before assigning results to avoid this behaviour. It essentially reindexes the dataframes with the latest component names.
Probably @FabianHofmann doesn't like this solution, otherwise I would add it myself :-).

**Comment by fneum** [comment]
@FabianHofmann this wasn't closed by https://github.com/PyPSA/PyPSA/commit/d391e2d5a73a2f6c1849642bd487f5bc2b7be781, right? Do you have suggested solution in `linopf` as well?
