### ISSUE TITLE
Is it possible to access admittance matrix?

### ISSUE THREAD

**Issue by Black-Web** [PyPSA/PyPSA#35]
I somehow want to view the admittance matrix of a constructed network, searched through the documentation and no answer found.

**Comment by nworbmot** [comment]
Please use our [forum](https://groups.google.com/forum/#!forum/pypsa) for questions.
You can access the admittance matrix after a load flow as the .Y attribute of sub_network objects, i.e. take an object, sn = network.sub_networks.obj.iloc[0] and access sn.Y.
