### ISSUE TITLE
Separate snapshot weighting from elapsed time

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/PyPSA#37]
It was discussed on the [PyPSA mailing list](https://groups.google.com/forum/#!topic/pypsa/oSKrOidIwBY) to separate the snapshot_weighting for each snapshot into two separate values, one that determines the prefactor for all snapshot-specific quantities in the objecting function, and one that corresponds to the snapshot duration, used e.g. by storage to determine how much energy is stored for a given power in each snapshot. This seems like a good idea. network.snapshot_weightings would then become a DataFrame rather than a series.

**Comment by FabianHofmann** [comment]
feature added in the current master
