### ISSUE TITLE
some problem in the example "power-to-gas-boiler-chp.ipynb"

### ISSUE THREAD

**Issue by breeze-zhaofei** [PyPSA/PyPSA#370]
Hi,

In the example "Power to Gas with Heat Coupling", there are some bugs in [7] cell of the jupyter notebook "**power-to-gas-boiler-chp.ipynb**". The part of error message are as follows.  They can also find in https://pypsa.readthedocs.io/en/latest/examples/power-to-gas-boiler-chp.html.

How can I fix it?
Thank you very much!

Input In [7], in <cell line: 1>()
----> 1 network.lopf(network.snapshots, extra_functionality=extra_functionality)
      2 network.objective

File ~/checkouts/readthedocs.org/user_builds/pypsa/conda/latest/lib/python3.10/site-packages/pypsa/components.py:658, in Network.lopf(self, snapshots, pyomo, solver_name, solver_options, solver_logfile, formulation, keep_files, extra_functionality, multi_investment_periods, **kwargs)
    653     logger.warning("You have defined one or more shunt impedances. "
    654                    "Shunt impedances are ignored by the linear optimal "
    655                    "power flow (LOPF).")
    657 if pyomo:
--> 658     return network_lopf(self, **args)
    659 else:
    660     return network_lopf_lowmem(self, **args)
... ...
    raise RuntimeError("Fatal error: cannot find the component data in "
RuntimeError: Fatal error: cannot find the component data in the owning component's _data dictionary.

**Comment by fneum** [comment]
Thanks for reporting. We indeed have to have a look at it. Likely this is a compatibility issue with the latest pyomo versions.

**Comment by breeze-zhaofei** [comment]
Yes, you are right. I try Pyomo 5.7.0, then it works. Before, I used Pyomo >6.0 maybe, and it reported the error as above. 

Thank you very much!

Tips: In Anaconda Prompt, "conda install -c conda-forge pypsa", then “pip install pyomo==5.7.0”.
