### ISSUE TITLE
Solver Options - uniform input

### ISSUE THREAD

**Issue by Cellophil** [PyPSA/PyPSA#373]
Hi everyone,

Excepted Solver options object (string or dict) differs between pyomo / no pyomo and the used solver. No Pyomo version (tested with cbc) seems to expect a string, something like "maxn 100 maxso 100 " works. In the pyomo version dicts are accepted. Maybe it would make sense to allow both, or at least allow dicts.

Best,
Andreas

Example:
n.lopf(
    pyomo=False,
    keep_files = False,
    solver_name = 'cbc',
    solver_options = 'maxso 100 maxn 1000 IntegerT 1e-3 RatioGap 1e-5 threads 6 '
)

**Comment by fneum** [comment]
@Cellophil I agree that some uniformity would be nice (although we will likely phase out pyomo in the future). A possible solution could look like this:

Allow dictionaries for solver_options always. If the solver expects a string and a dictionary is given, the dictionary is unpacked:

```py
" ".join(f"{k} {v}" for k, v in d.items())
```

Don't know how stable that would be. Would you create a PR?

**Comment by Cellophil** [comment]
Hi @fneum,

Sounds good, I can create a PR. I would assume that there is always a step on pypsa side involved that creates a final string, but I believe it's on solver wrapper level and specific to the solvers. Maybe that can be pulled out and put into a general solver option handler, I'll check that. I know of at least one solver option that does not follow the "key value" format but is just a value in cbc, but that can be done with an empty string as value I guess.

**Comment by fneum** [comment]
I think that option handling is all solver-specific at the moment because - as you say - the formats required vary. Open to suggestions how to unpack the options.
