### ISSUE TITLE
Unconnected buses

### ISSUE THREAD

**Issue by Cellophil** [PyPSA/PyPSA#374]
Hi everyone,

Unconnected buses (which may stem from importing networks) lead to somewhat cryptic error messages. I had "lhs of nodal constraint is not defined", and the following minimal example can't find component data.
Suggestion would be to add such a check to network's consistency check. Apart from that question would be whether a network with unconnected bus should be considered unsolvable or rather trivially solvable.

```
import pypsa
n = pypsa.Network()
n.add('Bus', 'Bus1')
n.add('Bus', 'Bus_out')
n.add('Load', 'Load1', bus='Bus1', p_set=10)
n.add('Generator', 'Gen1', bus='Bus1', p_nom=20)

n.consistency_check()
n.lopf()
```

Best,
Andreas

**Comment by fneum** [comment]
Good point. I can reproduce the error both for `pyomo=True` and `pyomo=False`. I think that definitely should raise a warning in the consistency check, maybe even be dealt with internally so it doesn't yield an error when `n.lopf()` is called.

The following actions seem sensible:

1. Add a check to `n.consistency_check()` that raises a warning in presence of a bus without any (supply) components connected to it. Maybe with a recommendation to remove it if it also has no load attached to it.
2. How to deal with the error when `n.lopf()` is called nonetheless. If it has neither supply nor demand components attached to it, can skip the nodal balance constraint which causes the trouble. If it has demand but no supply components, it is infeasible. The question is if it should raise an error when building the constraint already or whether we should just let the optimiser fail by passing a 0 term for the supply side if it is empty...

@Cellophil would you mind creating a PR for 1.?

**Comment by fneum** [comment]
xref #393
