### ISSUE TITLE
It is not possible to aggregate lines with different lifetime values

### ISSUE THREAD

**Issue by CarlosEpia** [PyPSA/PyPSA#376]
## Checklist

- [X] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

It is not possible to use the "get_clustering_from_busmap" function when there are lines with different lifetime values. It is due to the defined aggregation function, which is _make_consense. Probably assigning a mean value for lifetime in this dictionary https://github.com/PyPSA/PyPSA/blob/de183bd8044e3b5eb6352d39d4f509ef86a990c4/pypsa/networkclustering.py#L182-L199 could be reasonable. 

It should be considered that the default value for lines' lifetime is infinite. Therefore, in the case of using mean values, the resulting lifetime of a group with at least one infinite value will be infinite too, which could not be something desirable for the user. Probably a warning message in these cases could be useful.

**Comment by fneum** [comment]
@CarlosEpia this addition to also be able to aggregate lifetimes would be welcome. I would implement it as a capacity-weighted mean (similar to s_max_pu in line 188 using the _normed() function). Also a warning if mean over inf values would be ok. Would you be willing to prepare a small pull request?

**Comment by CarlosEpia** [comment]
@fneum Sure. I will create a short pull request for this.
