### ISSUE TITLE
Documentation rendering for Network Clustering seems broken

### ISSUE THREAD

**Issue by danielolsen** [PyPSA/PyPSA#383]
## Checklist

- [x] I am looking at the `latest` version of the documentation at https://pypsa.readthedocs.io/en/latest/examples/spatial-clustering.html

## Describe the Bug

The error seems to originate from calling a function that requires `sklearn` in an environment that doesn't have it. The downstream errors are based on this initial failure.

## Error Message

`ModuleNotFoundError: Optional dependency 'sklearn' not found.Install via 'conda install -c conda-forge scikit-learn' or 'pip install scikit-learn'`.

**Comment by fneum** [comment]
Ah, thanks for reporting @danielolsen. I'll push a fix soon.
