### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified in Non-linear power flow after LOPF 

### ISSUE THREAD

**Issue by hariom18** [PyPSA/PyPSA#388]
## Checklist

- [ ] I am using the current PYPSA v0.19.3 

## Describe the Bug
**Non-linear power flow after LOPF** (https://pypsa.readthedocs.io/en/latest/examples/scigrid-lopf-then-pf.html)

for i in range(int(24 / group_size)):
    # set the initial state of charge based on previous round
    if i:
        network.storage_units.state_of_charge_initial = (
            network.storage_units_t.state_of_charge.loc[
                network.snapshots[group_size * i - 1]
            ]
        )
    network.lopf(
        network.snapshots[group_size * i : group_size * i + group_size],
        solver_name="cbc",
        pyomo=False
    )

## Error Message

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by fneum** [comment]
Likely PyPSA can’t find the cbc solver on your system. You could try another solver like glpk which is easier to install on Windows.
