### ISSUE TITLE
"p_nom": pd.Series.min aggregation default reduces capacity

### ISSUE THREAD

**Issue by pz-max** [PyPSA/PyPSA#429]
## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

The default aggregation strategies are set in `networkclustering.py`
https://github.com/PyPSA/PyPSA/blob/daead70515d877fd273cc294ffa1734c218f2831/pypsa/networkclustering.py#L86-L98

We observed [here](https://github.com/pypsa-meets-africa/pypsa-africa/issues/431) the following behaviour using the PyPSA default aggregation strategies:

PyPSA-Africa: Powerplants in Nigeria **8GW**, after applying the aggregation strategy `p_nom: min` **5GW**, after fix `p_nom: sum` **8GW** 
PyPSA-Africa: Powerplants in Africa **121GW**, after applying the aggregation strategy `p_nom: min` **21GW**
PyPSA-Eur: Powerplant in Europe **476GW**, after applying the aggregation strategy `p_nom: min` **339GW**, after fix `p_nom: sum` **476GW**

I think the `"p_nom": pd.Series.sum` is an untended default setting introducing major capacity reductions. I would even argue that using `min` can be considered as bug. When clustering the powerplant capacities of e.g. 5 nodes, I want to have all 5 powerplants represented as `sum` in the resulting clustered node.  Therefore, I think we should make `"p_nom": pd.Series.sum` the default.

**Comment by coroa** [comment]
Indeed, that used to be sum. Got changed recently in https://github.com/PyPSA/PyPSA/pull/423 . Probably by mistake. @martacki

**Comment by martacki** [comment]
correct. i will fix it, thanks @pz-max @coroa
