### ISSUE TITLE
Pypsa-native constraints as class objects?

### ISSUE THREAD

**Issue by Cellophil** [PyPSA/PyPSA#437]
Hi all,

I've recently started the transition from pyomo to the pypsa way of defining constraints - it's definitely easier than what I first thought when I saw the linexpr tuple. I particularly like that get_var just gives me the identifier of the variables, that feels very clean.

Still, would it make sense to add a wrapper around linexpr, and try to replicate the pyomo way of writing constraints (as an additional option)? A base class could represent the tuple (prefactor, variable, constant), and \_\_add__, \_\_mul__ could be defined such that we can add them up, and multiply by prefactors. A step further a \_\_gt__ or \_\_eq__ could just yield an object that defines a whole constraint, and do the sorting of constants and variables.
I would give it a shot, but wanted to align if that makes sense.

Best,
Andreas

**Comment by Cellophil** [comment]
I tried it out and I'll add a little more context. I created a Linexpr class which is supposed to replicate the functionality of linexpr in all (most) regards. The following works:

`L1 = Linexpr((1, get_var(network, 'Generator', 'p')), (0.5, get_var(network, 'Generator', 'p')))`
The way of adding tuples is a bit complicated to understand at first I think. The return of get_var might be a 0-2 dimensional Pandas DataFrame as before.
`L2 = Linexpr(get_var(network, 'Generator', 'p')) + 3.`
I added the possibility to omit the prefactor. The added constant is stored.
`L3 = 0.2*L2`
The instance is copied, and constant and prefactors are multiplied by 0.2.
`L3 -= 0.7*L2 + L1*0.1`
Adding instances creates a new instance, tuples are added to the list, as well as the constant. "-=" works just as normal subtraction.
`define_constraints(network, l2.lhs, '>=', -l2.rhs+5, 'my_constraint')`
The property lhs wraps the output in a linexpr(instances tuples).
`c = l2 >= l`
Creates a constraint instance - only addition is basically having a sense. <=, =, >= would work.
`define_constraints(network, *c(), 'my_constraint_2')`
Calling the instance unpacks into lhs, sense, rhs.

Open question for me would be broadcasting - so far the instance asserts that all pandas DataFrame shapes are equal. Also, "as_pandas" and "return_axes", that behaviour could be replicated though.
The instances can have a nicely build representation that would state the constraints as plain text. Possibly even readable, using "generator_p" or something.
Finally, all of this works only within extra_functionality, is it planned to with the transition to pyomo=False to allow this while setting up a model? That would certainly be nice.

Best,
Andreas

**Comment by pz-max** [comment]
@Cellophil I am not really deeply involved in this, but some developments are going in the direction of [Linopy](https://linopy.readthedocs.io/en/latest/syntax.html). @FabianHofmann is working on this in [#PR336](https://github.com/PyPSA/PyPSA/pull/336) which will probably soon be the default. So maybe we can improve Linopy instead? Do you think that your raised enhancement can help `Linopy`?

**Comment by Cellophil** [comment]
@pz-max thanks for the hint - that looks good! Looking forward to the new version.

**Comment by FabianHofmann** [comment]
@Cellophil thanks for your comments! This is indeed in process through the outsourced linopy package. Let me allow to close this issue. We are just waiting for https://github.com/pydata/xarray/issues/6836 to be solved and then we can merge #324 in. Looking forward to your feedback.
