### ISSUE TITLE
Non-optimal solution not writing output

### ISSUE THREAD

**Issue by OriolRaventos** [PyPSA/PyPSA#44]
I am solving a lopf using the Barrier method from Gurobi (with the crossover turned off, since it takes too long otherwise) and I get just a sub-optimal solution. Then PyPSA prints:

WARNING:pypsa.opf:WARNING! Optimization might be sub-optimal. Writing output anyway

but it does not write any output. It seems to be problem with the format that the sub-optimal solution is given (maybe having some differences with the way an optimal solution is given).

Side note: I am using "extendable" storage and I am mainly interested in the "p_nom_opt" that the solver would give me.

**Comment by coroa** [comment]
Hi Oriol,
it's true, the warning message might be a bit misleading.
1. `PyPSA` the output is "written" into pypsa's internal data structures, i.e. the function extract_optimisation_results copies the variables of the sub-optimal solution into the static and time-dependent dataframes. n.storage_units.p_nom_opt is set to the found capacity. Can you please report back `n.storage_units.head()`, if that is not the case?

2. Sub-optimal solution states are often caused by numerical instabilities emanating from a wide range of matrix coefficients/objective coefficients (Usually the solver log contains hints about it). It often helps to zero small values in the renewable availability time-series `p_max_pu` or `inflow`.
(`n.generators_t.p_max_pu.where(lambda df: df>solve_opts['clip_p_max_pu'], other=0., inplace=True)`)

Best,
Jonas

**Comment by OriolRaventos** [comment]
Thank you for the quick answer. I'll try to make the changes you advice and report back (actually I would very much prefer to get an optimal solution). The columns of the network.storage_units are: 

name	
bus	
capital_cost	
carrier	
cyclic_state_of_charge	
efficiency_dispatch	
efficiency_store	
marginal_cost	max_hours	
p_nom_extendable	
p_nom_max	
p_nom_opt	
standing_loss

but the p_nom_opt column is empty, hence I get an optimal cost of "-inf" (as said all storage units are extendable). Looking at the code, it seems that PyPSA should be writing the output exactly as it was an optimal solution, but there may be some issue in the way Gurobi or Pyomo give the result.

**Comment by coroa** [comment]
I meant literally please execute `n.storage_units.head()` and share the storage configuration of the first few storage units.

What's the objective value gurobi reports? i found infs or nans there to be mostly indicative of a nan value at the wrong place. network.consistency_check() catches some of them.

**Comment by OriolRaventos** [comment]
Gurobi gives back:

Barrier performed 112 iterations in 880.35 seconds
Sub-optimal termination - objective 8.29486245e+07

And the complete head is:

INFO:pypsa.io:Imported network  has buses, carriers, generators, lines, loads, storage_units
     bus  capital_cost             carrier  cyclic_state_of_charge  \
name                                                                 
0      0       65822.0  extendable_storage                    True   
1      1       65822.0  extendable_storage                    True   
2     10       65822.0  extendable_storage                    True   
3     11       65822.0  extendable_storage                    True   
4     11       65402.0  extendable_storage                    True   

      efficiency_dispatch  efficiency_store  marginal_cost  max_hours  \
name                                                                    
0                  0.9327            0.9327           0.01        6.0   
1                  0.9327            0.9327           0.01        6.0   
2                  0.9327            0.9327           0.01        6.0   
3                  0.9327            0.9327           0.01        6.0   
4                  0.4250            0.7250           0.01      168.0   

      p_nom_extendable  p_nom_max   ...    p_nom  p_nom_min p_min_pu p_max_pu  \
name                                ...                                         
0                 True  1000000.0   ...      0.0        0.0     -1.0      1.0   
1                 True  2000000.0   ...      0.0        0.0     -1.0      1.0   
2                 True  2000000.0   ...      0.0        0.0     -1.0      1.0   
3                 True  2000000.0   ...      0.0        0.0     -1.0      1.0   
4                 True  1000000.0   ...      0.0        0.0     -1.0      1.0   

      p_set  q_set  sign  state_of_charge_initial  state_of_charge_set  inflow  
name                                                                            
0       0.0    0.0   1.0                      0.0                  NaN     0.0  
1       0.0    0.0   1.0                      0.0                  NaN     0.0  
2       0.0    0.0   1.0                      0.0                  NaN     0.0  
3       0.0    0.0   1.0                      0.0                  NaN     0.0  
4       0.0    0.0   1.0                      0.0                  NaN     0.0  

[5 rows x 24 columns]

**Comment by coroa** [comment]
We have too many columns, `p_nom_opt` got omitted. Do you have `nan` there? The rest looks fine.

**Comment by OriolRaventos** [comment]
Sorry. Yes, they are NaN as well

**Comment by OriolRaventos** [comment]
Here is the whole thing:

INFO:pypsa.io:Imported network k_means15 has buses, carriers, generators, lines, loads, storage_units
     bus  capital_cost             carrier  cyclic_state_of_charge  \
name                                                                 
0      0       65822.0  extendable_storage                    True   
1      1       65822.0  extendable_storage                    True   
2     10       65822.0  extendable_storage                    True   
3     11       65822.0  extendable_storage                    True   
4     11       65402.0  extendable_storage                    True   

      efficiency_dispatch  efficiency_store  marginal_cost  max_hours  \
name                                                                    
0                  0.9327            0.9327           0.01        6.0   
1                  0.9327            0.9327           0.01        6.0   
2                  0.9327            0.9327           0.01        6.0   
3                  0.9327            0.9327           0.01        6.0   
4                  0.4250            0.7250           0.01      168.0   

      p_nom_extendable  p_nom_max  p_nom_opt  standing_loss control type  \
name                                                                       
0                 True  1000000.0        NaN       0.006940      PQ        
1                 True  2000000.0        NaN       0.006940      PQ        
2                 True  2000000.0        NaN       0.006940      PQ        
3                 True  2000000.0        NaN       0.006940      PQ        
4                 True  1000000.0        NaN       0.000694      PQ        

      p_nom  p_nom_min  p_min_pu  p_max_pu  p_set  q_set  sign  \
name                                                             
0       0.0        0.0      -1.0       1.0    0.0    0.0   1.0   
1       0.0        0.0      -1.0       1.0    0.0    0.0   1.0   
2       0.0        0.0      -1.0       1.0    0.0    0.0   1.0   
3       0.0        0.0      -1.0       1.0    0.0    0.0   1.0   
4       0.0        0.0      -1.0       1.0    0.0    0.0   1.0   

      state_of_charge_initial  state_of_charge_set  inflow  
name                                                        
0                         0.0                  NaN     0.0  
1                         0.0                  NaN     0.0  
2                         0.0                  NaN     0.0  
3                         0.0                  NaN     0.0  
4                         0.0                  NaN     0.0

**Comment by coroa** [comment]
This all looks fine, except that obviously after the `lopf` you'd want to have `p_nom_opt` set properly. You can check that the read-out works correctly by inspecting `network.model.storage_p_nom.get_values()` after running the `lopf` (perhaps only work with a small subset of your network, i.e. the first day of it). If there are `nan` as well, you'd be looking at numerical problems, which depend on your input data; unsure how I could help there.

Again, make sure you don't have any `nan`s in your input data. `network.consistency_check()` is your friend (although not fully reliable).

**Comment by OriolRaventos** [comment]
Thank you again for your tips. Setting small values to zero really helps. Now most of my computations are already optimal before the crossover. 

I also used the consistency_check(). Really useful (and I didn't know about), but I believe the data is fine (I am quite confident that there is no NaN in the data). Here is the last past of the out put:

```
               '2011-02-12 14:00:00', '2011-02-20 14:00:00'],
              dtype='datetime64[ns]', name='name', freq=None)
WARNING:pypsa.components:The element 99 gas of generators has a smaller maximum than minimum operational limit which can lead to infeasibility for the following snapshots:
DatetimeIndex(['2011-01-06 07:00:00', '2011-01-06 10:00:00',
               '2011-01-06 13:00:00', '2011-01-06 14:00:00',
               '2011-01-07 01:00:00', '2011-01-07 02:00:00',
               '2011-01-25 13:00:00', '2011-01-25 14:00:00',
               '2011-02-07 23:00:00', '2011-04-28 14:00:00'],
              dtype='datetime64[ns]', name='name', freq=None)
WARNING:pypsa.components:The following attributes of the dataframe generators have the wrong dtype:
Index(['min_up_time', 'min_down_time', 'initial_status'], dtype='object', name='attribute')
They are:
attribute
min_up_time       int64
min_down_time     int64
initial_status    int64
dtype: object
but should be:
attribute
min_up_time       int32
min_down_time     int32
initial_status    int32
Name: dtype, dtype: object
```

What I didn't try to do yet is to get the variable values after lopf. If I understand this correctly, I would have to modify the file opf.py directly, since otherwise it gives me back just the network data.

**Comment by coroa** [comment]
On Tue, Sep 25 2018, OriolRaventos wrote:

```
> WARNING:pypsa.components:The element 99 gas of generators has a smaller maximum than minimum operational limit which can lead to infeasibility for the following snapshots:
> DatetimeIndex(['2011-01-06 07:00:00', '2011-01-06 10:00:00',
>                '2011-01-06 13:00:00', '2011-01-06 14:00:00',
>                '2011-01-07 01:00:00', '2011-01-07 02:00:00',
>                '2011-01-25 13:00:00', '2011-01-25 14:00:00',
>                '2011-02-07 23:00:00', '2011-04-28 14:00:00'],
>               dtype='datetime64[ns]', name='name', freq=None)
```

This Is critical unless the 99 gas generator is also unit committable!
(but then it must be or your model would be infeasible).

The `int64 <-> int32` dtype errors are a small bug in pypsa arising from
incompatibilities between python2 and 3 and can safely be ignored.

> What I didn't try to do yet is to get the variable values after lopf.
> If I understand this correctly, I would have to modify the file opf.py
> directly, since otherwise it gives me back just the network data.

No, it's not necessary to modify opf.py. The pyomo model is constructed
and stored as network.model and then solved "there". After running the
lopf it's fully accessible as network.model and only replaced by a
subsequent run of the lopf.

Best

**Comment by OriolRaventos** [comment]
Finally I found the time to look into the ```network.model.storage_p_nom.get_values()```. When I get a sub-optimal solution this function gives me an empty dictionary (of 151 variables in this case). If then I perform the crossover, it ends in an optimal solution and I get all the values of the variables.

Nevertheless, turning into zero the values that are very small makes that the solutions are optimal, which is a better outcome.
