### ISSUE TITLE
Cannot use pathlib.Path for opening with pypsa.Network(...)

### ISSUE THREAD

**Issue by euronion** [PyPSA/PyPSA#442]
Paths of networks need to be provided as `str` and `pathlib.Path` is not supported when trying to open Networks using `pypsa.Netowrk(...)`. See screenshot:

![image](https://user-images.githubusercontent.com/42553970/188843335-ab87a9c1-a186-4209-ae9b-a069733241d7.png)

## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

See above
## Error Message

See screenshot

**Comment by FabianHofmann** [comment]
upvoting to prioritize this issue
