### ISSUE TITLE
ValueError: negative column index found while load flow analysis

### ISSUE THREAD

**Issue by sahasubhajit** [PyPSA/PyPSA#445]
I have defined my system by introducing slack, generator buses, load buses and line parameters. Then I started to run Newton Raphson iteration by the command `network.pf()` but I got the error.

>  [/usr/local/lib/python3.7/dist-packages/scipy/sparse/coo.py](https://localhost:8080/#) in _check(self)
>     287             if self.row.min() < 0:
>     288                 raise ValueError('negative row index found')
> --> 289             if self.col.min() < 0:
>     290                 raise ValueError('negative column index found!')
>     291                 print(self.col.min())
> 
> ValueError: negative column index found

My system had total 32 buses with five generator buses.

**Comment by FabianHofmann** [comment]
@sahasubhajit thanks for reporting. The bug you raised is hard to understand. Could you provide a minimal reproducible example?
