### ISSUE TITLE
Highs solver interface update for MIP

### ISSUE THREAD

**Issue by Cellophil** [PyPSA/PyPSA#448]
Hi all,

As discussed @pz-max we should review once pull request #336 is done to check within the new interface.

First of all, the highs solver is amazing, it's speed in my problems is comparable to Gurobi :-). Thanks for adding the interface in the first place!
The highs solver command line interface has specific solver options (seemingly not extensively documented) which enforce linear problem solving. The doc explicitly states that the choices ipm (being the default choice within the current PyPSA highs interface) and simplex disregard integrality constraints. Minimal Example:

```
n = pypsa.Network()

n.add('Bus', name='bus1')
n.add('Load', name='load', bus='bus1')
n.add('Generator', name='generator_cheap', bus='bus1', p_nom=100, marginal_cost=1, p_min_pu=0.3, committable=True)
n.add('Generator', name='generator_expensive', bus='bus1', p_nom=1000, marginal_cost=5)

n.set_snapshots(np.arange(100))
n.loads_t['p_set'].loc[:, 'load'] = np.linspace(0,140,100)

n.lopf(pyomo=False, solver_name = 'highs')
```
The result will ignore p_min_pu basically; n.generators_t['status'] will be filled with float numbers. The interface should make the user aware of this, and maybe in addition a warning would be good whenever PyPSA sees results coming in that don't have the right type.

It is possible to run "choose" as solver method, it will solve MIP correctly, but then the output file is slightly different and the current interface can't read it in.
Additional minor enhancements: the options file should get a random tag to not collide within parallel runs; and suboptimal results (timelimit for instance) should optionally be accepted and be returned.

Best,
Andreas

![image](https://user-images.githubusercontent.com/58934815/190139768-f9341f05-7d38-4a93-b2f1-1849048ff747.png)

**Comment by FabianHofmann** [comment]
Hey @Cellophil, could you have a try with the updated master branch? 

Run 
```network.optimize(solver_name='highs')
```
