### ISSUE TITLE
The map outline cannot be displayed when drawing the power grid topology.

### ISSUE THREAD

**Issue by dange-academic** [PyPSA/PyPSA#458]
**pypsa==0.20.0, the example code is as follows:**
`import pypsa
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

network = pypsa.examples.scigrid_de(from_master=True)

fig, ax = plt.subplots(
    1, 1, subplot_kw={"projection": ccrs.EqualEarth()}, figsize=(8, 8)
)

load_distribution = (
    network.loads_t.p_set.loc[network.snapshots[0]].groupby(network.loads.bus).sum()
)
network.plot(bus_sizes=1e-5 * load_distribution, ax=ax, title="Load distribution")
plt.show()`

**with the following error message:**
`WARNING:pypsa.plot:Cartopy needs to be installed to use `geomap=True`.
Traceback (most recent call last):
  File "c:\Users\dange\Desktop\pypsa_example\example.py", line 18, in <module>
    network.plot(bus_sizes=1e-5 * load_distribution, ax=ax, title="Load distribution")
  File "D:\Miniconda3\envs\pypsa_example\lib\site-packages\pypsa\plot.py", line 215, in plot
    raise ValueError("Axis is a geo axis, but `geomap` is set to False")
ValueError: Axis is a geo axis, but `geomap` is set to False`

**When the penultimate line of code is changed to** 
`network.plot(bus_sizes=1e-5 * load_distribution, title="Load distribution")`
**the network topology is displayed normally, but the map outline is not displayed.**

![image](https://user-images.githubusercontent.com/110841103/193562499-aa0c43d7-caf6-42d6-89fd-20a08035cfa4.png)

**Comment by fneum** [comment]
Does it help if you add `geomap=True` to `n.plot(...)`? Does the import of `cartopy` work?

**Comment by fneum** [comment]
Cannot reproduce this behaviour. Check the newest versions of PyPSA and reopen if problem persists

**Comment by matteodefelice** [comment]
I had this problem, with pypsa 0.28. 
If I type:
```
fig, ax = plt.subplots(subplot_kw={"projection": ccrs.EqualEarth()}, figsize=(9, 9))
n.plot(
    ax=ax
)
```
I get:
```
WARNING:pypsa.plot:Cartopy needs to be installed to use `geomap=True`.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[20], line 2
      1 fig, ax = plt.subplots(subplot_kw={"projection": ccrs.EqualEarth()}, figsize=(9, 9))
----> 2 n.plot(
      3     ax=ax,
      4     # line_cmap=plt.cm.jet,
      5     # title="Line loading",
      6     # bus_sizes=1e-3,
      7     # bus_alpha=0.7,
      8     # geomap = False
      9 )
     10 # fig.tight_layout();

File [~\miniconda3\envs\pypsa\Lib\site-packages\pypsa\plot.py:245](http://localhost:8888/lab/tree/~/miniconda3/envs/pypsa/Lib/site-packages/pypsa/plot.py#line=244), in plot(n, margin, ax, geomap, projection, bus_colors, bus_alpha, bus_sizes, bus_cmap, bus_norm, bus_split_circles, line_colors, link_colors, transformer_colors, line_alpha, link_alpha, transformer_alpha, line_widths, link_widths, transformer_widths, line_cmap, link_cmap, transformer_cmap, line_norm, link_norm, transformer_norm, flow, branch_components, layouter, title, boundaries, geometry, jitter, color_geomap)
    243     ax = plt.gca()
    244 elif hasattr(ax, "projection"):
--> 245     raise ValueError("Axis is a geo axis, but `geomap` is set to False")
    246 if not geomap and boundaries:
    247     ax.axis(boundaries)

ValueError: Axis is a geo axis, but `geomap` is set to False
```

If I add `geomap = True` I get the same error.

**Comment by matteodefelice** [comment]
Update: I solved the issue re-installing cartopy (I didn't have any problem), I switched from anaconda to pip and now it works...
