### ISSUE TITLE
Nan Values for all Lines Power flow (network.lines_t.p0), without any warning regarding convergence failure

### ISSUE THREAD

**Issue by cosmerodolfo** [PyPSA/PyPSA#461]
pypsa==0.20.0, the example code is as follows:
`import pandas as pd
import warnings
import pypsa
import time
import numpy as np

warnings.filterwarnings('ignore')
def fluxocarga_PyPSA(bus, line, gen, load):
    """ Função que executa o Fluxo de Potência, a partir de Dataframes """
    ## Criação da Rede a Partir de Dataframes
    network = pypsa.Network()
    network.import_components_from_dataframe(bus, "Bus")
    network.import_components_from_dataframe(line, "Line")
    network.import_components_from_dataframe(gen, "Generator")
    network.import_components_from_dataframe(load, "Load")

    network.consistency_check()

    # Resolução do Fluxo de Potência pelo método Newton-Raphson
    network.pf()

    # Exteriorização dos principais resultados
    res_Pativa = network.lines_t.p0                                 # Resultado dos Fluxos de Potência
    res_Vmag = network.buses_t.v_mag_pu                             # Resultado das magnitudes da Tensão
    res_Vangles = network.buses_t.v_ang * 180/np.pi                 # Resultado dos angulos da Tensão

    return res_Pativa, res_Vmag, res_Vangles`

**# The result for the power flow after the convergence process is as below, for all lines:**
![image](https://user-images.githubusercontent.com/34916389/194384764-cd0a7290-34b3-4c83-b56a-8b5cb0098a09.png)

**# Part of lines config is:**
![image](https://user-images.githubusercontent.com/34916389/194385393-a306a00a-5c12-46b8-a909-84edc1c18748.png)

**# Part of generators config is:**
![image](https://user-images.githubusercontent.com/34916389/194385531-7c5027cc-662a-447f-8d15-c66ee8d8db1a.png)

**# Part of bus config is:**
![image](https://user-images.githubusercontent.com/34916389/194385769-3b7e271c-891c-4bed-8bc5-a93db23ba143.png)

**# Part of load config is:**
![image](https://user-images.githubusercontent.com/34916389/194385912-0476b345-ba05-4433-85c8-97866d64f413.png)

**# Consistency check result, with warning for dtypes:**

> WARNING:pypsa.components:The following attributes of the dataframe generators have the wrong dtype:

Index(['build_year', 'min_up_time', 'min_down_time', 'up_time_before',
       'down_time_before'],
      dtype='object', name='attribute')
They are:
attribute
build_year          int64
min_up_time         int64
min_down_time       int64
up_time_before      int64
down_time_before    int64
dtype: object
but should be:
attribute
build_year          int32
min_up_time         int32
min_down_time       int32
up_time_before      int32
down_time_before    int32
Name: dtype, dtype: object
WARNING:pypsa.components:The following attributes of the dataframe lines have the wrong dtype:
Index(['build_year'], dtype='object', name='attribute')
They are:
attribute
build_year    int64
dtype: object
but should be:
attribute
build_year    int32
Name: dtype, dtype: object

**Comment by fneum** [comment]
We need smaller examples to trace errors.
