### ISSUE TITLE
DC grid non linear power flow just works with AC carrier

### ISSUE THREAD

**Issue by Tomkelou** [PyPSA/PyPSA#467]
Hey, 

I just try to do a non linear power flow in a DC grid. The power flow works. But when I want to set the carrier at each bus to "DC", the pf doesn´t work and it says " "SubNetwork" object has no attribute "Y". 

In my understanding that should work. 

Here is the small example I tried.

import pypsa as ps
network = ps.Network()
n_buses= 3
for i in range (n_buses):
    network.add("Bus", "My bus {}".format(i), v_nom=20., carrier= "DC")
 
for i in range(n_buses):
    if i==1:
        network.add("Line", "My Line {}".format(i),
                bus0= "My bus {}".format(i),
                bus1="My bus {}".format((i+1)%3),
                x=0.0,
                r=0.03)
    else:          
        network.add("Line", "My Line {}".format(i),
                    bus0= "My bus {}".format(i),
                    bus1="My bus {}".format((i+1)%3),
                    x=0.0,
                    r=0.01)
network.add("Generator", "Slack gen",
            bus = "My bus 0",
            p_set= [100],
            control= "Slack")
network.add("Generator", "My gen",
            bus = "My bus 2",
            p_set= [100],
            control= "PQ")
 
network.add("Load","My load",
            bus = "My bus 1",
            p_set = [200],
            q_set = [0])
network.pf()

Maybe you have an idea what I did wrong, or you can fix it. 

Best regards, 
Tomke

**Comment by pz-max** [comment]
Just stumbled over a similar feature request in PyPSA : https://github.com/PyPSA/PyPSA/issues/40

**Comment by fneum** [comment]
closing this in favour of #40
