### ISSUE TITLE
implementation of asymmetric impedance

### ISSUE THREAD

**Issue by gvdwel** [PyPSA/PyPSA#49]
Hi,
I would like to use PyPSA with reduced networks, where the external network is represented by equivalent elements. One of these elements is an asymmetrical impedance. Here the impedance going from bus0 to bus1 differs from the impedance going from bus1 to bus0. 
This would be similar to the impedance element in pandapower.

Are there currently any plans in implementing this or am I overlooking something and is this currently already possible?

**Comment by miek770** [comment]
Hi @gvdwel,

There might be other (perhaps better) ways to do it, but I'd use unidirectional links in series with their respective impedance. See here: https://pypsa.org/doc/components.html#link

It's what I use to simulate asymmetrical energy costs in PyPSA.

Hope this helps,

Michel

**Comment by gvdwel** [comment]
Hi Michel,

Thank you for your suggestion. I tried it, but cannot get a power flow calculation to work. Could this be because the link is not a passive component? Have you used it with network.pf()?

Gerko

**Comment by miek770** [comment]
I think I've only used it for LOPF, but the link is a bit tricky to configure so you could try double checking your configuration vs the doc. Sorry if this doesn't work!

**Comment by nworbmot** [comment]
@gvdwel You could introduce a new SeriesImpedance passive branch component (i.e. in the same group as Lines and Transformers) with this property. It would however be hard to implement in the LOPF maybe. I'd suggest implementing it yourself and then we can see whether it is general enough to incorporate in the main code base.
