### ISSUE TITLE
Adding a custom constraint leads to AttributeError: 'Network' object has no attribute 'model'

### ISSUE THREAD

**Issue by oorishko** [PyPSA/PyPSA#498]
## Checklist

I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch.

## Describe the Bug

When running one of the provided examples on adding a custom constraint for pyomo=False on line 193 
https://github.com/PyPSA/PyPSA/blob/master/examples/sector-coupling/power-to-gas-boiler-chp.py#L193
you receive an Attribute error. 
This is also reflected in the documentation https://pypsa.readthedocs.io/en/latest/examples/power-to-gas-boiler-chp.html when the embedded notebook is being executed. 
Would you be able to describe the changes required to be made and update the example along with the documentation? 

## Error Message

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "...\PyPSA\pypsa\components.py", line 770, in lopf
    return network_lopf_lowmem(self, **args)
  File "...\PyPSA\pypsa\linopf.py", line 1456, in network_lopf
    fdp, problem_fn = prepare_lopf(
  File "...\PyPSA\pypsa\linopf.py", line 1125, in prepare_lopf
    extra_functionality(n, snapshots)
  File "...PyPSA/examples/sector-coupling/power-to-gas-boiler-chp.py", line 160, in extra_functionality
    network.model.chp_nom = Constraint(
AttributeError: 'Network' object has no attribute 'model'
`

**Comment by coroa** [comment]
The power-to-gas-boiler examples were still written for pyomo and `network.model` there referred to the pyomo `Model`, with `pyomo=False` optimisation you need to use the `get_var` and `define_variables` functions directly as described at https://pypsa.readthedocs.io/en/latest/examples/lopf_with_pyomo_False.html .

There is indeed a new `network.model` added back into `pypsa` through the use of the `linopy` optimisation package described at https://pypsa.readthedocs.io/en/latest/examples/optimization-with-linopy.html . For being to access this model you need to call `network.optimize.create_model()` first or use the `network.optimize(extra_functionality=extra_functionality)` methods.

**Comment by FabianHofmann** [comment]
solved in #504
