### ISSUE TITLE
Unjustified consistency check warnings with multi-input/-output links

### ISSUE THREAD

**Issue by euronion** [PyPSA/PyPSA#499]
In a network allowing for n:1 or 1:m links (links with multiple input or output buses) `network.consistency_check()` throws warnings if there exist links in the network which do not use all input/output buses.

E.g.:
* the `link` component is extended to support `bus0` to `bus2`
* if a link only uses `bus0` and `bus1`
* then `network.consistency_check()` throws the following warning:

```
2022-11-17 08:09:08 pypsa.components WARNING  The following links have bus2 which are not defined:
```

## Checklist

- [x] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

In earlier versions of `consistency_check()` only the correct setting of `bus0` and `bus1` was evaluated.
In the newer version there seems to be no way to suppress the warning despite the link having intentionally no `bus2` connection.

## Error Message

```
2022-11-17 08:09:08 pypsa.components WARNING  The following links have bus2 which are not defined:
```

**Comment by FabianHofmann** [comment]
I am wondering. The warning says only that the buses used in your `links` dataframe in the `bus2` column do not exist in `n.buses.index`.

**Comment by euronion** [comment]
No. Such a warning would make sense, but that's not how the warning is triggered and to be understood. Maybe it was meant to behave that way, but it doesn't.

Take https://pypsa.readthedocs.io/en/latest/examples/chp-fixed-heat-power-ratio.html as example. Running `network.consistency_check()` on the example results in

```
> network.consistency_check()
WARNING:pypsa.components:The following links have bus2 which are not defined:
Index(['OCGT'], dtype='object', name='Link')
```

The bus exists. It is just that the OCGT link only has `bus0` and `bus1` but no `bus2` defined:

```
> network.links[["bus0","bus1","bus2"]]
Out[5]:
attribute           bus0       bus1            bus2
Link
OCGT       Frankfurt gas  Frankfurt
CHP        Frankfurt gas  Frankfurt  Frankfurt heat
```

**Comment by FabianHofmann** [comment]
Ah it is because of the empty string! I'll make a fix :)
