### ISSUE TITLE
Idea? - implement __add__ for networks

### ISSUE THREAD

**Issue by Cellophil** [PyPSA/PyPSA#506]
Hi,

Occasionally we had the situation that there's subnetworks that could be defined separately, maybe we are also interested in solving those subnetwork separatly. Then we want to combine them into one big network.
Would it be an idea to implement the class method __add__ such that network1+network2 makes sense and gives you the combined network? Could make some workflows quite tidy. I guess there's a ton of things to consider there, overlapping buses for instance to have them connected after the merger. So at this stage just an idea.

Best,
Andreas

**Comment by fneum** [comment]
I'd support such a feature. It'll not be too difficult. You only want to check for any components occurring in each of the two networks that all their attributes match, otherwise the addition should fail.

**Comment by jessLryan** [comment]
I'm interested in working on this

**Comment by fneum** [comment]
It's actually very similar to a deep copy "into an existing network".

Sketch with no guarantee for completeness:

```
import pypsa

# take and solve and example network
n = pypsa.examples.ac_dc_meshed()
n.optimize()
print(n.objective)

# create an empty hull for a new network (maybe an existing network)
m = pypsa.Network()
m.snapshots = n.snapshots.copy()
m.snapshot_weightings = n.snapshot_weightings.copy()

# some components should not be added
to_skip = {"TransformerType", "LineType", "SubNetwork", "Network"}
components = n.components.keys() - to_skip
for c in n.iterate_components(components):
    m.import_components_from_dataframe(c.df, c.name)
    for k, v in c.pnl.items():
        m.import_series_from_dataframe(v, c.name, k)

# check that objective is identical
m.optimize()
print(m.objective)
```

**Comment by jessLryan** [comment]
Thanks for that Fabian :-) I got caught up working on something else in the last few months but I'm hoping to have this finished within the next week
