### ISSUE TITLE
Add examples and documentation for `n.statistics(...)`

### ISSUE THREAD

**Issue by euronion** [PyPSA/PyPSA#537]
## Describe the feature you'd like to see

`n.statistics` is nice and helpful, but a little bit hard to wrap the head around solely based on the doc strings which have a high information density and require pre-existing knowledge on pypsa. It would be great to have a few examples in the documentation on how to use the module.

**Comment by fneum** [comment]
e.g.
@lisazeyen 

> - add example how groupby can be used
> - add example how compscan be used
> - add marginal prices per carrier
