### ISSUE TITLE
Search broken on readthedocs

### ISSUE THREAD

**Issue by maurerle** [PyPSA/PyPSA#538]
## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

Searching for something in the upper left search field of the docs on https://pypsa.readthedocs.io/ 
does not terminate - it stays at "Searching ..."
In the Webconsole one can see:
```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://pypsa.readthedocs.io/en/latest/search.html?q=p_nom_extendabledf&check_keywords=yes&area=default#:338
search.html:338:5
```
which seems to be related to this issue

The issue happens on firefox and chromium equally, which make the docs only half useful

**Comment by fneum** [comment]
This is a problem occurring due to the new sphinx version 6.
