### ISSUE TITLE
Load Flow problem

### ISSUE THREAD

**Issue by rtguti** [PyPSA/PyPSA#55]
Hello.

I have problem with my code created in PyPSA. I want to do power flow of this 14 bus system. When I run this code I get an error: INFO:pypsa.pf:Newton-Raphson solved in 0 iterations with error of nan in 0.003990 seconds.
I am new in Python. I am student and I want to expand Python at our department. Where is problem, please? 
Thanks for reply.

################
import pypsa
import numpy as np
from pandas import DataFrame

#Vytvorenie siete
network = pypsa.Network()

#Vytvorenie zbernic a ich parametrizacia
network.add("Bus", "bus1", v_nom=69, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus2", v_nom=69, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus3", v_nom=69, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus4", v_nom=69, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus5", v_nom=69, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus6", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus7", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus8", v_nom=18, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus9", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus10", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus11", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus12", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus13", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)
network.add("Bus", "bus14", v_nom=13.8, v_mag_pu_min=0.94, v_mag_pu_max=1.06)

#vypis zbernic
print(network.buses)

#Vytvorenie generatorov a ich parametrizacia
network.add("Generator", "gen1", bus="bus1", control="Slack", p_set=232.4 ,p_max_pu=2, p_min_pu=0, marginal_cost=20)
network.add("Generator", "gen2", bus="bus2", control="PV", p_set=40, p_max_pu=1.4, p_min_pu=0, marginal_cost=20)
network.add("Generator", "gen3", bus="bus3", control="PV", p_set=0, p_max_pu=1, p_min_pu=0, marginal_cost=40)
network.add("Generator", "gen4", bus="bus6", control="PV", p_set=0, p_max_pu=1, p_min_pu=0, marginal_cost=40)
network.add("Generator", "gen5", bus="bus8", control="PV", p_set=0, p_max_pu=1, p_min_pu=0, marginal_cost=40)

#vypis generatorov
print(network.generators)

#Vytvorenie prenosovych vedeni a ich parametrizacia
network.add("Line", "line1", bus0="bus1", bus1="bus2", r=0.922488, x=2.816492, b=0.001109244,
             length=17,s_nom=120)
network.add("Line", "line2", bus0="bus1", bus1="bus5", r=2.571828, x=10.616704, b=0.001033613,
             length=52, s_nom=65)
network.add("Line", "line3", bus0="bus2", bus1="bus3", r=2.236724, x=9.423372, b=0.000920168,
             length=46, s_nom=36)
network.add("Line", "line4", bus0="bus2", bus1="bus4", r=2.766036, x=8.392832, b=0.000785714,
             length=50, s_nom=65)
network.add("Line", "line5", bus0="bus2", bus1="bus5", r=2.71082, x=8.276688, b=0.000714286,
             length=50, s_nom=50)
network.add("Line", "line6", bus0="bus3", bus1="bus4", r=3.189676, x=8.141028, b=0.000726891,
             length=56, s_nom=65)
network.add("Line", "line7", bus0="bus4", bus1="bus5", r=0.63546, x=2.004436, b=0.000268908,
             length=12, s_nom=45)
network.add("Line", "line11", bus0="bus6", bus1="bus11", r=4.521048, x=9.46764, b=0,
            length=16.5, s_nom=18)
network.add("Line", "line12", bus0="bus6", bus1="bus12", r=5.850516, x=11.996152, b=0,
           length=21, s_nom=32)
network.add("Line", "line13", bus0="bus6", bus1="bus13", r=3.14874, x=6.200852, b=0,
           length=11.5, s_nom=32)
network.add("Line", "line15", bus0="bus7", bus1="bus9", r=0, x=5.236476, b=0,
            length=1, s_nom=32)
network.add("Line", "line16", bus0="bus9", bus1="bus10", r=1.514156, x=4.0222, b=0,
            length=16, s_nom=32)
network.add("Line", "line17", bus0="bus9", bus1="bus14", r=6.050436, x=12.870088, b=0,
            length=22.5, s_nom=32)
network.add("Line", "line18", bus0="bus10", bus1="bus11", r=3.90558, x=9.142532, b=0,
            length=15.5, s_nom=12)
network.add("Line", "line19", bus0="bus12", bus1="bus13", r=10.515792, x=9.514288, b=0,
            length=21, s_nom=12)
network.add("Line", "line20", bus0="bus13", bus1="bus14", r=8.136268, x=16.565752, b=0,
            length=28, s_nom=12)

#vypis prenosovych vedeni
print(network.lines)

#Vytvorenie prenosovych transformatorov
network.add("Transformer","transformer 1",bus0="bus4",bus1="bus9", r=0, x=9.954112, b=0, tap_ratio=0.978, s_nom=32, tap_side=0)
network.add("Transformer","transformer 2",bus0="bus5",bus1="bus6", r=0, x=26.474168, b=0, tap_ratio=0.969, s_nom=45, tap_side=0)
network.add("Transformer","transformer 3",bus0="bus4",bus1="bus7", r=0, x=9.95, b=0, tap_ratio=0.932, s_nom=55, tap_side=0)
network.add("Transformer","transformer 4",bus0="bus4",bus1="bus8", r=0, x=8.38474, b=0, tap_ratio=0.932, tap_side=0)

#vypis prenosovych vedeni
print(network.transformers)

#Vytvorenie zatazi a ich parametrizacia
network.add("Load", "load 1", bus="bus2", p_set=21.7, q_set=12.7)
network.add("Load", "load 2", bus="bus3", p_set=94.2, q_set=19)
network.add("Load", "load 3", bus="bus4", p_set=47.8, q_set=-3.9)
network.add("Load", "load 4", bus="bus5", p_set=7.6, q_set=1.6)
network.add("Load", "load 5", bus="bus6", p_set=11.2, q_set=7.5)
network.add("Load", "load 6", bus="bus9", p_set=29.5, q_set=16.6)
network.add("Load", "load 7", bus="bus10", p_set=9, q_set=5.8)
network.add("Load", "load 8", bus="bus11", p_set=3.5, q_set=1.8)
network.add("Load", "load 9", bus="bus12", p_set=6.1, q_set=1.6)
network.add("Load", "load 10", bus="bus13", p_set=13.5, q_set=5.8)
network.add("Load", "load 11", bus="bus14", p_set=14.9, q_set=5)

#vypis zatazi
print(network.loads)

network.pf()

print(network.lines_t.p0)
print(network.buses_t.v_ang*180/np.pi)

**Comment by FabianHofmann** [comment]
Hey! Your transformer 'transfomer 4' does not have any s_nom argument given. It falls back (as a default) to zero, which leads to nan in r_pu as thus in the calculation. Please doublecheck the value.  (It might that the network does not converge, which is another question however)

**Comment by fneum** [comment]
Closing this issue for now. Please reopen if your problem persists.
