### ISSUE TITLE
Python 3.7 compatibility & low-voltage example

### ISSUE THREAD

**Issue by L-Piao** [PyPSA/PyPSA#56]
Dear all,

I've recently switched to python 3.7 and suddenly had some issues with PyPSA.

1. Does PyPSA 0.13.2 support python 3.7? Or will a later version be compatible with 3.7?

2. What are the fundamental obstacles for PyPSA to support python 3.7?

3. In case I use PyPSA after using other packages (like SPADE) that only runs in 3.7, how to switch  the environment back to 3.6 to run PyPSA codes? Especially, I'm using Jupyter Notebook and such changes of kernel becomes a problem.

A bonus question: I've been modeling a low-voltage distribution network with PyPSA. I think the model might interest other researchers who want to try PyPSA for medium or low-voltage applications. It's based on the "IEEE European low-voltage distribution test feeder" where the network and the load profiles are open source. Do you think it'll make sense if we include it as an example of PyPSA applications?

Thank you very much!

Best regards,
Piao

==========
update 28.03.2019

Issue solved. PyPSA supports python 3.7, but you need to upgrade the package PYOMO. Previous versions might contain a variable named "async" which is not allowed any more from python 3.7 on.

Thanks for the hints from Nis Martensen and Johannes Hampp (via google group) : )

**Comment by neunzehnachtneun** [comment]
Additional as reference i found this issue: https://github.com/Pyomo/pyomo/issues/645
So since pyomo 5.5.1 this bug is fixed.

**Comment by luidis2020** [comment]
@L-Piao  hello friend, I started using python and pyomo a week ago, I am just getting to know everything as much as I can. I will be working in MV-LV distribution network. I used AMPL and Maltab but I had an interesting conversation with a friend who suggested me to dive into Python, Pyomo, OpenDSS. So, I am really interested in this but I need help. I am interested in the modelling of distribution network that you developed in PyPSA and also wha you commented on IEEE profiles open source. Please, could you help me? this is my email. cordero.lg@gmail.com
btw. check my github, I am figure out how to solve a problem in the param syntax in Pyomo (original written in AMPL IEEE 13 bus MV). thanks.https://github.com/luidis2020/OPF-MV-Distribution-Network

**Comment by timebis** [comment]
hi @L-Piao,
I am really interested by your low-voltage model. Can you send it to me here : lesieurthomas@hotmail.fr ?
Thank you very much !
