### ISSUE TITLE
PyPSA Power Flow 0 Iterations Result

### ISSUE THREAD

**Issue by alexisisgit** [PyPSA/PyPSA#593]
Hello. I am graduate student learning how to use PyPSA and wanted to reproduce the IEEE 39-bus system on the open software. I think all my component parameters have the correct required input but my program runs 0 iterations. What am I missing to make my program system converge?

##########################################VSCode####################################################
import numpy as np
import pypsa

network = pypsa.Network()

# 39 Buses (bus0 - bus38)   
for i in range(1,30):
    network.add("Bus", "Bus {}".format(i))

network.add(class_name = "Bus", name = "Bus 30", v_mag_pu_set = 1.0475)
network.add(class_name = "Bus", name = "Bus 31")
network.add(class_name = "Bus", name = "Bus 32", v_mag_pu_set = 0.9831)
network.add(class_name = "Bus", name = "Bus 33", v_mag_pu_set = 0.9972)
network.add(class_name = "Bus", name = "Bus 34", v_mag_pu_set = 1.0123)
network.add(class_name = "Bus", name = "Bus 35", v_mag_pu_set = 1.0493)
network.add(class_name = "Bus", name = "Bus 36", v_mag_pu_set = 1.0635)
network.add(class_name = "Bus", name = "Bus 37", v_mag_pu_set = 1.0278)
network.add(class_name = "Bus", name = "Bus 38", v_mag_pu_set = 1.0265)
network.add(class_name = "Bus", name = "Bus 39", v_mag_pu_set = 1.0300)
print(network.buses)

# 32 Lines
network.add(class_name = "Line", name = "Line 1", bus0 = "Bus 10", bus1 = "Bus 11", r_pu = 0.0004, x_pu = 0.0043, b_pu = 0.0729)
network.add(class_name = "Line", name = "Line 2", bus0 = "Bus 22", bus1 = "Bus 23", r_pu = 0.0006, x_pu = 0.0096, b_pu = 0.1846)
network.add(class_name = "Line", name = "Line 3", bus0 = "Bus 26", bus1 = "Bus 29", r_pu = 0.0057, x_pu = 0.0625, b_pu = 1.0290)
network.add(class_name = "Line", name = "Line 4", bus0 = "Bus 23", bus1 = "Bus 24", r_pu = 0.0022, x_pu = 0.0350, b_pu = 0.3610)
network.add(class_name = "Line", name = "Line 5", bus0 = "Bus 3", bus1 = "Bus 4", r_pu = 0.0013, x_pu = 0.0213, b_pu = 0.2214)
network.add(class_name = "Line", name = "Line 6", bus0 = "Bus 28", bus1 = "Bus 29", r_pu = 0.0014, x_pu = 0.0151, b_pu = 0.2490)
network.add(class_name = "Line", name = "Line 7", bus0 = "Bus 5", bus1 = "Bus 6", r_pu = 0.0002, x_pu = 0.0026, b_pu = 0.0434)
network.add(class_name = "Line", name = "Line 8", bus0 = "Bus 10", bus1 = "Bus 13", r_pu = 0.0004, x_pu = 0.0043, b_pu = 0.0729)
network.add(class_name = "Line", name = "Line 9", bus0 = "Bus 6", bus1 = "Bus 7", r_pu = 0.0006, x_pu = 0.0092, b_pu = 0.1130)
network.add(class_name = "Line", name = "Line 10", bus0 = "Bus 6", bus1 = "Bus 11", r_pu = 0.0007, x_pu = 0.0082, b_pu = 0.1389)
network.add(class_name = "Line", name = "Line 11", bus0 = "Bus 3", bus1 = "Bus 18", r_pu = 0.0011, x_pu = 0.0133, b_pu = 0.2138)
network.add(class_name = "Line", name = "Line 12", bus0 = "Bus 7", bus1 = "Bus 8", r_pu = 0.0004, x_pu = 0.0046, b_pu = 0.0780)
network.add(class_name = "Line", name = "Line 13", bus0 = "Bus 2", bus1 = "Bus 25", r_pu = 0.0007, x_pu = 0.0086, b_pu = 0.0146)
network.add(class_name = "Line", name = "Line 14", bus0 = "Bus 1", bus1 = "Bus 39", r_pu = 0.0010, x_pu = 0.0250, b_pu = 0.7500)
network.add(class_name = "Line", name = "Line 15", bus0 = "Bus 4", bus1 = "Bus 14", r_pu = 0.0008, x_pu = 0.0129, b_pu = 0.1382)
network.add(class_name = "Line", name = "Line 16", bus0 = "Bus 13", bus1 = "Bus 14", r_pu = 0.0009, x_pu = 0.0101, b_pu = 0.1723)
network.add(class_name = "Line", name = "Line 17", bus0 = "Bus 26", bus1 = "Bus 28", r_pu = 0.0043, x_pu = 0.0474, b_pu = 0.7802)
network.add(class_name = "Line", name = "Line 18", bus0 = "Bus 26", bus1 = "Bus 27", r_pu = 0.0014, x_pu = 0.0147, b_pu = 0.2396)
network.add(class_name = "Line", name = "Line 19", bus0 = "Bus 5", bus1 = "Bus 8", r_pu = 0.0008, x_pu = 0.0112, b_pu = 0.1476)
network.add(class_name = "Line", name = "Line 20", bus0 = "Bus 25", bus1 = "Bus 26", r_pu = 0.0032, x_pu = 0.0323, b_pu = 0.5130)
network.add(class_name = "Line", name = "Line 21", bus0 = "Bus 14", bus1 = "Bus 15", r_pu = 0.0018, x_pu = 0.0217, b_pu = 0.3660)
network.add(class_name = "Line", name = "Line 22", bus0 = "Bus 15", bus1 = "Bus 16", r_pu = 0.0009, x_pu = 0.0094, b_pu = 0.1710)
network.add(class_name = "Line", name = "Line 23", bus0 = "Bus 16", bus1 = "Bus 17", r_pu = 0.0007, x_pu = 0.0089, b_pu = 0.1342)
network.add(class_name = "Line", name = "Line 24", bus0 = "Bus 16", bus1 = "Bus 19", r_pu = 0.0016, x_pu = 0.0195, b_pu = 0.3040)
network.add(class_name = "Line", name = "Line 25", bus0 = "Bus 16", bus1 = "Bus 21", r_pu = 0.0008, x_pu = 0.0135, b_pu = 0.2548)
network.add(class_name = "Line", name = "Line 26", bus0 = "Bus 16", bus1 = "Bus 24", r_pu = 0.0003, x_pu = 0.0059, b_pu = 0.0680)
network.add(class_name = "Line", name = "Line 27", bus0 = "Bus 17", bus1 = "Bus 18", r_pu = 0.0007, x_pu = 0.0082, b_pu = 0.1319)
network.add(class_name = "Line", name = "Line 28", bus0 = "Bus 17", bus1 = "Bus 27", r_pu = 0.0013, x_pu = 0.0173, b_pu = 0.3216)
network.add(class_name = "Line", name = "Line 29", bus0 = "Bus 8", bus1 = "Bus 9", r_pu = 0.0023, x_pu = 0.0363, b_pu = 0.3804)
network.add(class_name = "Line", name = "Line 30", bus0 = "Bus 4", bus1 = "Bus 5", r_pu = 0.0008, x_pu = 0.0128, b_pu = 0.1342)
network.add(class_name = "Line", name = "Line 31", bus0 = "Bus 9", bus1 = "Bus 39", r_pu = 0.0010, x_pu = 0.0250, b_pu = 1.2000)
network.add(class_name = "Line", name = "Line 32", bus0 = "Bus 21", bus1 = "Bus 22", r_pu = 0.0008, x_pu = 0.0140, b_pu = 0.2565)
print(network.lines)

# 12 Transformers
network.add(class_name = "Transformer", name = "Transformer 1", bus0 = "Bus 31", bus1 = "Bus 6", r_pu = 0.0000, x_pu = 0.0250)
network.add(class_name = "Transformer", name = "Transformer 2", bus0 = "Bus 29", bus1 = "Bus 38", r_pu = 0.0008, x_pu = 0.0156)
network.add(class_name = "Transformer", name = "Transformer 3", bus0 = "Bus 12", bus1 = "Bus 13", r_pu = 0.0016, x_pu = 0.0435)
network.add(class_name = "Transformer", name = "Transformer 4", bus0 = "Bus 12", bus1 = "Bus 11", r_pu = 0.0016, x_pu = 0.0435)
network.add(class_name = "Transformer", name = "Transformer 5", bus0 = "Bus 25", bus1 = "Bus 37", r_pu = 0.0006, x_pu = 0.0232)
network.add(class_name = "Transformer", name = "Transformer 6", bus0 = "Bus 10", bus1 = "Bus 32", r_pu = 0.0000, x_pu = 0.0200)
network.add(class_name = "Transformer", name = "Transformer 7", bus0 = "Bus 2", bus1 = "Bus 30", r_pu = 0.0000, x_pu = 0.0181)
network.add(class_name = "Transformer", name = "Transformer 8", bus0 = "Bus 23", bus1 = "Bus 36", r_pu = 0.0005, x_pu = 0.0272)
network.add(class_name = "Transformer", name = "Transformer 9", bus0 = "Bus 22", bus1 = "Bus 35", r_pu = 0.0000, x_pu = 0.0143)
network.add(class_name = "Transformer", name = "Transformer 10", bus0 = "Bus 20", bus1 = "Bus 34", r_pu = 0.0005, x_pu = 0.0272)
network.add(class_name = "Transformer", name = "Transformer 11", bus0 = "Bus 19", bus1 = "Bus 33", r_pu = 0.0007, x_pu = 0.0142)
network.add(class_name = "Transformer", name = "Transformer 12", bus0 = "Bus 19", bus1 = "Bus 20", r_pu = 0.0007, x_pu = 0.0138)
print(network.transformers)

# 10 Generators
network.add(class_name = "Generator", name = "Generator 1", bus = "Bus 30", control = "PV", p_set = 250)
network.add(class_name = "Generator", name = "Generator 2", bus = "Bus 31", control = "slack")
network.add(class_name = "Generator", name = "Generator 3", bus = "Bus 32", control = "PV", p_set = 650)
network.add(class_name = "Generator", name = "Generator 4", bus = "Bus 33", control = "PV", p_set = 632)
network.add(class_name = "Generator", name = "Generator 5", bus = "Bus 34", control = "PV", p_set = 508)
network.add(class_name = "Generator", name = "Generator 6", bus = "Bus 35", control = "PV", p_set = 650)
network.add(class_name = "Generator", name = "Generator 7", bus = "Bus 36", control = "PV", p_set = 560)
network.add(class_name = "Generator", name = "Generator 8", bus = "Bus 37", control = "PV", p_set = 540)
network.add(class_name = "Generator", name = "Generator 9", bus = "Bus 38", control = "PV", p_set = 830)
network.add(class_name = "Generator", name = "Generator 10", bus = "Bus 39", control = "PV", p_set = 1000)
print(network.generators)

# 31 Loads
network.add(class_name = "Load", name = "Load 1", bus = "Bus 1", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 2", bus = "Bus 2", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 3", bus = "Bus 3", p_set = 322, q_set = 2.4)
network.add(class_name = "Load", name = "Load 4", bus = "Bus 4", p_set = 500, q_set = 184)
network.add(class_name = "Load", name = "Load 5", bus = "Bus 5", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 6", bus = "Bus 6", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 7", bus = "Bus 7", p_set = 233.8, q_set = 84)
network.add(class_name = "Load", name = "Load 8", bus = "Bus 8", p_set = 522, q_set = 176)
network.add(class_name = "Load", name = "Load 9", bus = "Bus 9", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 10", bus = "Bus 10", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 11", bus = "Bus 11", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 12", bus = "Bus 12", p_set = 7.5, q_set = 88)
network.add(class_name = "Load", name = "Load 13", bus = "Bus 13", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 14", bus = "Bus 14", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 15", bus = "Bus 15", p_set = 320, q_set = 153)
network.add(class_name = "Load", name = "Load 16", bus = "Bus 16", p_set = 329.4, q_set = 32.3)
network.add(class_name = "Load", name = "Load 17", bus = "Bus 17", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 18", bus = "Bus 18", p_set = 158, q_set = 30)
network.add(class_name = "Load", name = "Load 19", bus = "Bus 19", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 20", bus = "Bus 20", p_set = 680, q_set = 103)
network.add(class_name = "Load", name = "Load 21", bus = "Bus 21", p_set = 274, q_set = 115)
network.add(class_name = "Load", name = "Load 22", bus = "Bus 22", p_set = 0, q_set = 0)
network.add(class_name = "Load", name = "Load 23", bus = "Bus 23", p_set = 247.5, q_set = 84.6)
network.add(class_name = "Load", name = "Load 24", bus = "Bus 24", p_set = 308.6, q_set = -92.2)
network.add(class_name = "Load", name = "Load 25", bus = "Bus 25", p_set = 224, q_set = 47.2)
network.add(class_name = "Load", name = "Load 26", bus = "Bus 26", p_set = 139, q_set = 17)
network.add(class_name = "Load", name = "Load 27", bus = "Bus 27", p_set = 281, q_set = 75.5)
network.add(class_name = "Load", name = "Load 28", bus = "Bus 28", p_set = 206, q_set = 27.6)
network.add(class_name = "Load", name = "Load 29", bus = "Bus 29", p_set = 283.5, q_set = 26.9)
network.add(class_name = "Load", name = "Load 31", bus = "Bus 31", p_set = 9.2, q_set = 4.6)
network.add(class_name = "Load", name = "Load 39", bus = "Bus 39", p_set = 1104, q_set = 250)
print(network.loads)

network.pf()

##########################################Output####################################################

$ C:/Users/alexi/anaconda3/envs/pypsa-earth/python.exe c:/Users/alexi/pypsa-earth-project/pypsa-earth/data/IEEE_39_bus_system.py
INFO: Could not find files for the given pattern(s).
attribute  v_nom type    x    y carrier  unit  v_mag_pu_set  v_mag_pu_min  v_mag_pu_max control sub_network
Bus
Bus 1        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 2        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 3        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 4        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 5        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 6        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 7        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 8        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 9        1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 10       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 11       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 12       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 13       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 14       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 15       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 16       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 17       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 18       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 19       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 20       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 21       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 22       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 23       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 24       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 25       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 26       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 27       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 28       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 29       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 30       1.0       0.0  0.0      AC  None        1.0475           0.0           inf      PQ
Bus 31       1.0       0.0  0.0      AC  None        1.0000           0.0           inf      PQ
Bus 32       1.0       0.0  0.0      AC  None        0.9831           0.0           inf      PQ
Bus 33       1.0       0.0  0.0      AC  None        0.9972           0.0           inf      PQ
Bus 34       1.0       0.0  0.0      AC  None        1.0123           0.0           inf      PQ
Bus 35       1.0       0.0  0.0      AC  None        1.0493           0.0           inf      PQ
Bus 36       1.0       0.0  0.0      AC  None        1.0635           0.0           inf      PQ
Bus 37       1.0       0.0  0.0      AC  None        1.0278           0.0           inf      PQ
Bus 38       1.0       0.0  0.0      AC  None        1.0265           0.0           inf      PQ
Bus 39       1.0       0.0  0.0      AC  None        1.0300           0.0           inf      PQ
attribute    bus0    bus1 type    x    r    g    b  s_nom  ...  sub_network    x_pu    r_pu  g_pu    b_pu  x_pu_eff  r_pu_eff  s_nom_opt
Line                                                       ...
Line 1     Bus 10  Bus 11       0.0  0.0  0.0  0.0    0.0  ...               0.0043  0.0004   0.0  0.0729       0.0       0.0        0.0
Line 2     Bus 22  Bus 23       0.0  0.0  0.0  0.0    0.0  ...               0.0096  0.0006   0.0  0.1846       0.0       0.0        0.0
Line 3     Bus 26  Bus 29       0.0  0.0  0.0  0.0    0.0  ...               0.0625  0.0057   0.0  1.0290       0.0       0.0        0.0
Line 4     Bus 23  Bus 24       0.0  0.0  0.0  0.0    0.0  ...               0.0350  0.0022   0.0  0.3610       0.0       0.0        0.0
Line 5      Bus 3   Bus 4       0.0  0.0  0.0  0.0    0.0  ...               0.0213  0.0013   0.0  0.2214       0.0       0.0        0.0
Line 6     Bus 28  Bus 29       0.0  0.0  0.0  0.0    0.0  ...               0.0151  0.0014   0.0  0.2490       0.0       0.0        0.0
Line 7      Bus 5   Bus 6       0.0  0.0  0.0  0.0    0.0  ...               0.0026  0.0002   0.0  0.0434       0.0       0.0        0.0
Line 8     Bus 10  Bus 13       0.0  0.0  0.0  0.0    0.0  ...               0.0043  0.0004   0.0  0.0729       0.0       0.0        0.0
Line 9      Bus 6   Bus 7       0.0  0.0  0.0  0.0    0.0  ...               0.0092  0.0006   0.0  0.1130       0.0       0.0        0.0
Line 10     Bus 6  Bus 11       0.0  0.0  0.0  0.0    0.0  ...               0.0082  0.0007   0.0  0.1389       0.0       0.0        0.0
Line 11     Bus 3  Bus 18       0.0  0.0  0.0  0.0    0.0  ...               0.0133  0.0011   0.0  0.2138       0.0       0.0        0.0
Line 12     Bus 7   Bus 8       0.0  0.0  0.0  0.0    0.0  ...               0.0046  0.0004   0.0  0.0780       0.0       0.0        0.0
Line 13     Bus 2  Bus 25       0.0  0.0  0.0  0.0    0.0  ...               0.0086  0.0007   0.0  0.0146       0.0       0.0        0.0
Line 14     Bus 1  Bus 39       0.0  0.0  0.0  0.0    0.0  ...               0.0250  0.0010   0.0  0.7500       0.0       0.0        0.0
Line 15     Bus 4  Bus 14       0.0  0.0  0.0  0.0    0.0  ...               0.0129  0.0008   0.0  0.1382       0.0       0.0        0.0
Line 16    Bus 13  Bus 14       0.0  0.0  0.0  0.0    0.0  ...               0.0101  0.0009   0.0  0.1723       0.0       0.0        0.0
Line 17    Bus 26  Bus 28       0.0  0.0  0.0  0.0    0.0  ...               0.0474  0.0043   0.0  0.7802       0.0       0.0        0.0
Line 18    Bus 26  Bus 27       0.0  0.0  0.0  0.0    0.0  ...               0.0147  0.0014   0.0  0.2396       0.0       0.0        0.0
Line 19     Bus 5   Bus 8       0.0  0.0  0.0  0.0    0.0  ...               0.0112  0.0008   0.0  0.1476       0.0       0.0        0.0
Line 20    Bus 25  Bus 26       0.0  0.0  0.0  0.0    0.0  ...               0.0323  0.0032   0.0  0.5130       0.0       0.0        0.0
Line 21    Bus 14  Bus 15       0.0  0.0  0.0  0.0    0.0  ...               0.0217  0.0018   0.0  0.3660       0.0       0.0        0.0
Line 22    Bus 15  Bus 16       0.0  0.0  0.0  0.0    0.0  ...               0.0094  0.0009   0.0  0.1710       0.0       0.0        0.0
Line 23    Bus 16  Bus 17       0.0  0.0  0.0  0.0    0.0  ...               0.0089  0.0007   0.0  0.1342       0.0       0.0        0.0
Line 24    Bus 16  Bus 19       0.0  0.0  0.0  0.0    0.0  ...               0.0195  0.0016   0.0  0.3040       0.0       0.0        0.0
Line 25    Bus 16  Bus 21       0.0  0.0  0.0  0.0    0.0  ...               0.0135  0.0008   0.0  0.2548       0.0       0.0        0.0
Line 26    Bus 16  Bus 24       0.0  0.0  0.0  0.0    0.0  ...               0.0059  0.0003   0.0  0.0680       0.0       0.0        0.0
Line 27    Bus 17  Bus 18       0.0  0.0  0.0  0.0    0.0  ...               0.0082  0.0007   0.0  0.1319       0.0       0.0        0.0
Line 28    Bus 17  Bus 27       0.0  0.0  0.0  0.0    0.0  ...               0.0173  0.0013   0.0  0.3216       0.0       0.0        0.0
Line 29     Bus 8   Bus 9       0.0  0.0  0.0  0.0    0.0  ...               0.0363  0.0023   0.0  0.3804       0.0       0.0        0.0
Line 30     Bus 4   Bus 5       0.0  0.0  0.0  0.0    0.0  ...               0.0128  0.0008   0.0  0.1342       0.0       0.0        0.0
Line 31     Bus 9  Bus 39       0.0  0.0  0.0  0.0    0.0  ...               0.0250  0.0010   0.0  1.2000       0.0       0.0        0.0
Line 32    Bus 21  Bus 22       0.0  0.0  0.0  0.0    0.0  ...               0.0140  0.0008   0.0  0.2565       0.0       0.0        0.0

[32 rows x 29 columns]
attribute         bus0    bus1 type model    x    r    g    b  ...  sub_network    x_pu    r_pu  g_pu  b_pu  x_pu_eff  r_pu_eff  s_nom_opt
Transformer                                                    ...
Transformer 1   Bus 31   Bus 6          t  0.0  0.0  0.0  0.0  ...               0.0250  0.0000   0.0   0.0       0.0       0.0        0.0
Transformer 2   Bus 29  Bus 38          t  0.0  0.0  0.0  0.0  ...               0.0156  0.0008   0.0   0.0       0.0       0.0        0.0
Transformer 3   Bus 12  Bus 13          t  0.0  0.0  0.0  0.0  ...               0.0435  0.0016   0.0   0.0       0.0       0.0        0.0
Transformer 4   Bus 12  Bus 11          t  0.0  0.0  0.0  0.0  ...               0.0435  0.0016   0.0   0.0       0.0       0.0        0.0
Transformer 5   Bus 25  Bus 37          t  0.0  0.0  0.0  0.0  ...               0.0232  0.0006   0.0   0.0       0.0       0.0        0.0
Transformer 6   Bus 10  Bus 32          t  0.0  0.0  0.0  0.0  ...               0.0200  0.0000   0.0   0.0       0.0       0.0        0.0
Transformer 7    Bus 2  Bus 30          t  0.0  0.0  0.0  0.0  ...               0.0181  0.0000   0.0   0.0       0.0       0.0        0.0
Transformer 8   Bus 23  Bus 36          t  0.0  0.0  0.0  0.0  ...               0.0272  0.0005   0.0   0.0       0.0       0.0        0.0
Transformer 9   Bus 22  Bus 35          t  0.0  0.0  0.0  0.0  ...               0.0143  0.0000   0.0   0.0       0.0       0.0        0.0
Transformer 10  Bus 20  Bus 34          t  0.0  0.0  0.0  0.0  ...               0.0272  0.0005   0.0   0.0       0.0       0.0        0.0
Transformer 11  Bus 19  Bus 33          t  0.0  0.0  0.0  0.0  ...               0.0142  0.0007   0.0   0.0       0.0       0.0        0.0
Transformer 12  Bus 19  Bus 20          t  0.0  0.0  0.0  0.0  ...               0.0138  0.0007   0.0   0.0       0.0       0.0        0.0

[12 rows x 31 columns]
attribute        bus control type  p_nom  p_nom_extendable  ...  ramp_limit_up  ramp_limit_down  ramp_limit_start_up  ramp_limit_shut_down  p_nom_opt
Generator                                                   ...
Generator 1   Bus 30      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 2   Bus 31   slack         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 3   Bus 32      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 4   Bus 33      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 5   Bus 34      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 6   Bus 35      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 7   Bus 36      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 8   Bus 37      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 9   Bus 38      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0
Generator 10  Bus 39      PV         0.0             False  ...            NaN              NaN                  1.0                   1.0        0.0

[10 rows x 30 columns]
attribute     bus carrier type   p_set  q_set  sign
Load
Load 1      Bus 1                  0.0    0.0  -1.0
Load 2      Bus 2                  0.0    0.0  -1.0
Load 3      Bus 3                322.0    2.4  -1.0
Load 4      Bus 4                500.0  184.0  -1.0
Load 5      Bus 5                  0.0    0.0  -1.0
Load 6      Bus 6                  0.0    0.0  -1.0
Load 7      Bus 7                233.8   84.0  -1.0
Load 8      Bus 8                522.0  176.0  -1.0
Load 9      Bus 9                  0.0    0.0  -1.0
Load 10    Bus 10                  0.0    0.0  -1.0
Load 11    Bus 11                  0.0    0.0  -1.0
Load 12    Bus 12                  7.5   88.0  -1.0
Load 13    Bus 13                  0.0    0.0  -1.0
Load 14    Bus 14                  0.0    0.0  -1.0
Load 15    Bus 15                320.0  153.0  -1.0
Load 16    Bus 16                329.4   32.3  -1.0
Load 17    Bus 17                  0.0    0.0  -1.0
Load 18    Bus 18                158.0   30.0  -1.0
Load 19    Bus 19                  0.0    0.0  -1.0
Load 20    Bus 20                680.0  103.0  -1.0
Load 21    Bus 21                274.0  115.0  -1.0
Load 22    Bus 22                  0.0    0.0  -1.0
Load 23    Bus 23                247.5   84.6  -1.0
Load 24    Bus 24                308.6  -92.2  -1.0
Load 25    Bus 25                224.0   47.2  -1.0
Load 26    Bus 26                139.0   17.0  -1.0
Load 27    Bus 27                281.0   75.5  -1.0
Load 28    Bus 28                206.0   27.6  -1.0
Load 29    Bus 29                283.5   26.9  -1.0
Load 31    Bus 31                  9.2    4.6  -1.0
Load 39    Bus 39               1104.0  250.0  -1.0
INFO:pypsa.pf:Performing non-linear load-flow on AC sub-network SubNetwork 0 for snapshots Index(['now'], dtype='object', name='snapshot')
INFO:pypsa.pf:Newton-Raphson solved in 0 iterations with error of nan in 0.001997 seconds

**Comment by fneum** [comment]
We can help you with specific error messages, but unfortunately, we cannot debug your code. Please feel free to reopen with a more specific description of the error.
