### ISSUE TITLE
Flows Not Matching

### ISSUE THREAD

**Issue by SYHaque** [PyPSA/PyPSA#601]
I have been trying to figure out the 2022 US OPF system for the US, and I have been faced with a couple of issues. to put stuff into context; I have used actual data for the year of 2022 for US, but for my results file, I have been getting a few errors. 
1. Firstly, my generation results file has a lot of 0, 
2. Secondly, the prices results sheet were also quite high. 
3. Finally, the flows do not match. The generation+imports does not equal the load+exports.

I have been trying to figure out where the error could be, so any help would be greatly appreciated.

**Comment by fneum** [comment]
Hi @SYHaque, please ask usage questions on the PyPSA mailing list or PyPSA-Earth discord server, as you are not describing a bug or feature request.

https://pypsa.readthedocs.io/en/latest/mailing_list.html

You will also need to be a little more specific with your project description for us to be able to help you.
