### ISSUE TITLE
set snapshots does not consider snapshot_weightings when combining two existing grids

### ISSUE THREAD

**Issue by IsGut** [PyPSA/PyPSA#619]
Hi all,

I am using the version '0.21.2'.

I have a network n with 35040 snapshots and specific n.snapshot_weightings.
I init another empty network n2.
Then: n2.set_snapshots(n.snapshots)

Now, n2 has snapshot_weightings of 1. n.snapshot_weightings are not considered.

How can n2 get snapshot_weightings of n in the appropriate way?

Thanks a lot!

**Comment by fneum** [comment]
```py
n2.snapshots = n.snapshots
n2.snapshot_weightings = n.snapshot_weightings
```

should work.
