### ISSUE TITLE
Unit commitment on a negative generator 

### ISSUE THREAD

**Issue by toby-coleman** [PyPSA/PyPSA#634]
## Checklist

- [x ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate: latest version `0.23.0`

## Describe the Bug

I'm building a model using negative generator components as flexible demand, and I would like to use unit commitment constraints. For example, in this example I have a normal generator that outputs 10MW, and a negative generator that switches on when demand drops.

```python
import pypsa
import pandas as pd
print(pypsa.__version__)

demand = pd.DataFrame({"demand": [10] * 48}, index=range(48))
demand.iloc[20:25] = 5

network = pypsa.Network()
network.set_snapshots(range(48))

network.add("Bus", "bus")
network.add("Load", "load", bus="bus", p_set=demand["demand"])

# Gen1 can only generate at 10MW
network.add("Generator", "gen1", bus="bus", p_nom=10, p_min_pu=1, p_max_pu=1, marginal_cost=10, committable=True)
# Gen2 can generate at between -5MW and -10MW
network.add("Generator", "gen2", bus="bus", p_nom=10, p_max_pu=-0.5, p_min_pu=-1, marginal_cost=10, committable=True, min_up_time=1, min_down_time=1)

network.optimize(solver_name="highs")
```

This works as expected. However if I set `min_up_time = 2` on `gen2` I would still expect the model to solve:
```python
network.add("Generator", "gen2", bus="bus", p_nom=10, p_max_pu=-0.5, p_min_pu=-1, marginal_cost=10, committable=True, min_up_time=2, min_down_time=1)
```

However I get
```
INFO:linopy.model: Solve linear problem using Highs solver
INFO:linopy.io: Writing time: 0.1s
INFO:linopy.solvers:Log file at /tmp/highs.log.
WARNING:linopy.constants:Optimization failed: 
Status: warning
Termination condition: infeasible
Solution: 0 primals, 0 duals
Objective: nan
Solver model: available
Solver message: infeasible
```

**Comment by FabianHofmann** [comment]
Hey @toby-coleman! Hard to say, from where exactly this is coming. Normally, when we model a flexible load as a generator, we use the sign attribute which is set to -1. 
```
network.add("Generator", "gen2", bus="bus", p_nom=10, p_max_pu=0.5, p_min_pu=1, marginal_cost=-10, committable=True, min_up_time=2, min_down_time=1, sign=-1)
```
Note that I reversed the sign of the p_max_pu/p_min_pu and costs. Could you try whether this breaks too?

**Comment by toby-coleman** [comment]
Actually I can get it to work by setting `up_time_before=2`, so it was the initial condition. I guess the default of `up_time_before=1` doesn't make sense in this scenario.

**Comment by toby-coleman** [comment]
Closing, as this was a case of 'user error' on my part!
