### ISSUE TITLE
Request to implement a Wideband Cable Model in the Phase Domain

### ISSUE THREAD

**Issue by shanks847** [PyPSA/PyPSA#651]
After research into simulating the response of power cables under fault conditions, it turns out I would require a Wideband Cable Model, in particular a Frequency Dependent Distributed Phase Model, similar to [Mouhaidali et. al. 2020](https://hal.science/hal-02995214/document). That seems to be an improvement on the existing wideband models commonly used. There's also an approach of a variant of my problem in EMTP-RV done by [NREL](https://www.nrel.gov/docs/fy21osti/78057.pdf)

I currently have access to EMTP-RV and I would like to develop a variant of the ULM model as shown in the first [Mouhaidali et. al. 2020](https://[hal.science/hal-02995214/document](https://hal.science/hal-02995214/document)), in PyPSA. 

Furthermore, due to the high use of underground transmission and distribution systems, I believe incorporating the frequency dependence of soil and building upon the model as discussed by [Xue et. al. 2020](https://doi.org/10.1016/j.ijepes.2020.106163)

**Comment by fneum** [comment]
Hi @shanks847, thanks for suggesting that feature, but PyPSA does not focus on fault conditions. Maybe pandapower would be an option for you.
