### ISSUE TITLE
Add stand-by cost for committable links and generators

### ISSUE THREAD

**Issue by davide-f** [PyPSA/PyPSA#657]
## Describe the feature you'd like to see

The current implementation of costs is a pure proportional function with respect to the energy produced.
In mathematical term, the following conceptual function applies:
$cost = weighting * marginalcost * power$

However, most fuel-fired generators may be better described by a piece-wise linear function, or quadratic function, especially when generators are committable.
In this issue, we propose the following revised function:
$cost = weighting * (standbycost * status + marginalcost * power)$

The above function remains linear and it extends the previous formulation without being braking.
Soon a PR by Enrico may be opened to include this draft.

**Comment by loongmxbt** [comment]
Relative: #496 
My solution using opf+pyomo extend original model.
```
sum_no_load_cost = sum(
            model.generator_status[g, t] * nu.generators.at[g, "no_load_cost"]
            for t in sub_snapshots
            for g in ucmr_name_list
        )
model.objective = model.objective + sum_no_load_cost
```
