### ISSUE TITLE
Package PyPSA for conda with conda-forge

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#70]
PyPSA should be installable not only via `pip` but also through `conda` and should be submitted to the `conda-forge` repository.

**Comment by coroa** [comment]
I added a [PR](https://github.com/conda-forge/staged-recipes/pull/8459) against conda-forge's staged-recipes as documented on the [conda-forge docs](https://conda-forge.readthedocs.io/en/latest/recipe.html).

**Comment by coroa** [comment]
Fixed by https://github.com/conda-forge/pypsa-feedstock .

**Comment by coroa** [comment]
Mention in the docs is already integrated in PR #71.
