### ISSUE TITLE
Ramp rate limits in combination with p_min_pu show unexpected result

### ISSUE THREAD

**Issue by SamuelGoodday** [PyPSA/PyPSA#705]
## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate: PyPSA 0.25.1

## Describe the Bug

When applying ramp_limits for generators as well as p_min_pu > 0, more costly generators are dispatched at p_min_pu for the entire snapshot horizon. Expected result: as soon as the ramping constraints of the cheaper generators are fullfilled, the expensive generators are shut down. 
I expanded the ramp rate limit example of the [PyPSA documentation](https://pypsa.readthedocs.io/en/latest/examples/unit-commitment.html#Ramp-rate-limits) with additional snapshots and p_min_pu > 0.

nu = pypsa.Network(snapshots=range(15))

nu.add("Bus", "bus")

nu.add(
    "Generator", "coal", bus="bus",
    marginal_cost=20,
    ramp_limit_up=0.1,
    ramp_limit_down=0.2,
    p_nom=10000,
    p_min_pu = 0.1
    )

nu.add("Generator", "gas", bus="bus", 
    marginal_cost=70,
    p_nom=4000,
    p_min_pu = 0.1,
    )

nu.add("Load", "load", bus="bus", p_set=[4000, 7000, 7000, 7000,7000,
                                         7000, 7000,  7000,7000, 7000,
                                         7000, 7000, 7000,  7000, 3000])
nu.optimize()

**Comment by euronion** [comment]
It should work if you include `commitable=True` for your generators as is done in the example? With your setup the model cannot turn of the two generators with `p_min_pu > 0`.

**Comment by SamuelGoodday** [comment]
Hi,

Indeed committable is by default = False. I somehow missed that. With your suggestion it works as expected.

**Comment by SamuelGoodday** [comment]
Hi,

Indeed committable is by default = False. I somehow missed that. With your suggestion it works as expected.
Thanks for the check.
BR. Samuel

**Comment by euronion** [comment]
👍  happy to help
