### ISSUE TITLE
Time dependent ramp rates

### ISSUE THREAD

**Issue by PeterKlein11** [PyPSA/PyPSA#717]
In cases where p_max_pu represents outages it would be helpful to also adjust ramp rates, by defining as a series instead of a static values.

Requires changing component_attrs csv files and linopy constraints.py. Happy to submit a pull request if not already in progress.

**Comment by fneum** [comment]
Great idea, I don't think anyone is working on this currently.

I did something similar for other parameters recently, which you could use as inspiration.

https://github.com/PyPSA/PyPSA/pull/572

**Comment by PeterKlein11** [comment]
HI Fabian. Apologies for the delay only recently got a gap to look at this. I have submitted a pull request (my first, so not sure if I did it correctly). I have a Jupyter notebook that tests the implementation for generators and links which I can share if needed.
