### ISSUE TITLE
KeyError when making new variables in extra_functionality

### ISSUE THREAD

**Issue by jonasghini** [PyPSA/PyPSA#718]
Hi,

I use the extra_functionality to add capacity charges to my system (assign a cost to importing power, not just energy from an external grid). To do so, I need to add a new variable to the pypsa network model `n.model.add_variables`. I give the new variable the name "Electric_grid_import-monthly_max_power". 

Then I run the model and everything works fine until pypsa gets to assigning the solution after the solver has finished its optimization. Now pypsa goes looking for a component named "Electric_grid_import" in the dictionary `n.components`. This component, of course, does not exist, since it isn't a component, it is just an intermediate variable needed to keep track of the monthly maximum imported power from the grid.

My solution so far is twofold.

In the function `pypsa.optimization.optimize.assign_solution()` I add the following, just below the check for `name == 'objective_constant`:

```python
if hasattr(n, 'skip_variables'):
    if name in n.skip_variables:
        continue
``` 

Back in the extra_functionality capacity charge function I have the following:

```python
if hasattr(EnergySystemNetwork, 'skipVariables'):
    EnergySystemNetwork.skipVariables.append(p_max_month.name)
else:
    EnergySystemNetwork.skipVariables = [p_max_month.name]
```

This adds the "Electric_grid_import" variable name to a list of variables to skip when assigning the solution. However, the manual change to  `pypsa.optimization.optimize.assign_solution()` is definitely a bit of a pain. 

Is there a smoother way to handle the addition of new variables to the model?

**Comment by fneum** [comment]
I think this is a specialty of PyPSA where it uses the "Component-attribute" naming convention for regular constraints to allocate them to the right dataframes. The solution might just be to choose a constraint name without a dash.

**Comment by jonasghini** [comment]
This was exactly it! Thank you! Removing the dash from the new variable's name solves the error.
