### ISSUE TITLE
Installation on Anaconda/Conda fails due to broken cartopy

### ISSUE THREAD

**Issue by KevinXo** [PyPSA/PyPSA#72]
When I install PyPSA with pip,this happened

 C:\Users\Kevin_xo>pip install pypsa
Collecting pypsa
  Using cached https://files.pythonhosted.org/packages/46/62/958b6dcc30531fd34cec8e3a85cdc3e4f010860198f5b1b82ee99cc87601/pypsa-0.14.0.tar.gz
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from pypsa) (1.15.4)
Collecting pyomo>=5.3 (from pypsa)
  Using cached https://files.pythonhosted.org/packages/bd/16/db99b5042af1697e1df61fee9b8a1b95b6e2bfb4f74968844f6b26d0468d/Pyomo-5.6.4-py3-none-any.whl
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from pypsa) (1.1.0)
Requirement already satisfied: pandas>=0.19.0 in c:\programdata\anaconda3\lib\site-packages (from pypsa) (0.23.4)
Requirement already satisfied: networkx>=1.10 in c:\programdata\anaconda3\lib\site-packages (from pypsa) (2.2)
Collecting cartopy>=0.16 (from pypsa)
  Using cached https://files.pythonhosted.org/packages/e5/92/fe8838fa8158931906dfc4f16c5c1436b3dd2daf83592645b179581403ad/Cartopy-0.17.0.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    C:\Users\Kevin_xo\AppData\Local\Temp\pip-install-mhc6osxg\cartopy\setup.py:171: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
      '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
    Proj 4.9.0 must be installed.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Kevin_xo\AppData\Local\Temp\pip-install-mhc6osxg\cartopy\

Please help me to solve the problem,thanks a lot.

**Comment by coroa** [comment]
Hi KevinXo,

when you install from within `conda` you must make sure to install the package `cartopy` directly using
```
conda install cartopy
```
since conda brings in an incompatible version of the `proj4` library, iotherwise.

We're about to add `pypsa` to `conda-forge` so you can use `conda install pypsa` within a couple of days to mitigate this (see #70).

Best

**Comment by KevinXo** [comment]
Sir,when I install the package cartopy this happened,
C:\Users\Kevin_xo>pip install cartopy
Collecting cartopy
  Using cached https://files.pythonhosted.org/packages/e5/92/fe8838fa8158931906dfc4f16c5c1436b3dd2daf83592645b179581403ad/Cartopy-0.17.0.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    C:\Users\Kevin_xo\AppData\Local\Temp\pip-install-cybjaovi\cartopy\setup.py:171: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
      '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
    Proj 4.9.0 must be installed.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Kevin_xo\AppData\Local\Temp\pip-install-cybjaovi\cartopy\

> Hi KevinXo,
> 
> when you install from within `conda` you must make sure to install the package `cartopy` directly using
> 
> ```
> conda install cartopy
> ```
> 
> since conda brings in an incompatible version of the `proj4` library, iotherwise.
> 
> We're about to add `pypsa` to `conda-forge` so you can use `conda install pypsa` within a couple of days to mitigate this (see #70).
> 
> Best

**Comment by KevinXo** [comment]
DEAR Sir,
Do you mean that Pypsa can't be installed  via anaconda at the moment?

**Comment by coroa** [comment]
Are you using Anaconda or miniconda?

If yes, please use
```
conda install cartopy
```
as I wrote above.

**Comment by KevinXo** [comment]
Dear sir,
(base) C:\Users\Kevin_xo>conda install cartopy
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - cartopy

What should I do?

**Comment by coroa** [comment]
You have to install the `conda-forge` channel as described in their [introduction](http://conda-forge.org/docs/user/introduction.html), ie.
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```

Then
```
conda install cartopy
```
then.

**Comment by KevinXo** [comment]
Thank you very much,sir. I have installed Pypsa successfully via running the anaconda prompt as an administrator 0o0

**Comment by coroa** [comment]
Note that you can from now also install PyPSA directly using: `conda install -c conda-forge pypsa` . I don't think Administrator rights should be necessary for that, but I don't know Windows well enough to be sure.
