### ISSUE TITLE
import_components_from_dataframe ignores default values

### ISSUE THREAD

**Issue by Irakli-D** [PyPSA/PyPSA#746]
## Checklist

- [ ] I am using the latest version of PyPSA available on the 4th of October 2023, without any modification.

## Describe the Bug

If some parameters in the dataframe are Nan, the `import_components_from_dataframe` does not take into consideration the default values. For example, if the `p_max_pu` and `p_min_pu` of Generators are not defined in an inputted data frame, the network does not consider the default values of the component parameters and `consistency_check()` shows them as warnings. This finally results in an infeasible solution.

**Comment by fneum** [comment]
Thanks for letting us know. In the meantime, you can do:

```py
n.madd(c, df.index, **df)
```

https://github.com/PyPSA/PyPSA/issues/341
