### ISSUE TITLE
voltage dependency of loads

### ISSUE THREAD

**Issue by jankaeh** [PyPSA/PyPSA#76]
I think it would be nice to add a dependency of loads_t.p and loads_t.q of the connected buses_t.v_mag_pu for power flow calculations. Did anyone already work on this?

My first idea would be to:
1. add two attributes to loads: ratio of p/q that is dependent on the voltage (default 0)
2. build loop around pf with p_set/q_set being recalculated from the pf-result for buses_t.v_mag_pu as long as they change significantly.

I could try to implement this, if you think it is useful. If so: Do you think the approach is suitable and are there any preliminary works that could help?

**Comment by nworbmot** [comment]
You can look how pandapower have implemented the ZIP load model, which is fairly standard:
https://pandapower.readthedocs.io/en/v1.4.1/elements/load.html
