### ISSUE TITLE
Allowing committable generators to be extended

### ISSUE THREAD

**Issue by PeterKlein11** [PyPSA/PyPSA#762]
Given the introduction of linearized unit commitment the computational demands are significantly reduced for committable generators. 

Apart from computational time, are there any other barriers to adding the option for the committable generators to be extended as well (if linearized unit com is active)? 

Although mostly used for system adequacy runs, having a committable unit as extendable helps to differentiate  between OCGT and CCGTs in expansion models.

**Comment by fneum** [comment]
I think you still have the problem with the constraints for the dispatch of committable generators that you have a product of two variables, namely `status * capacity`, which the linearisation does not solve.

**Comment by PeterKlein11** [comment]
Ah of course. Thanks. I guess we can close this.
