### ISSUE TITLE
Rolling horizon unit commitment not using end states of previous periods

### ISSUE THREAD

**Issue by sophie-pelland** [PyPSA/PyPSA#771]
## Checklist

- I am using the current pypsa v0.25.1

## Describe the Bug

We are running unit commitment over one year periods with a rolling horizon of 365 hours. Running code that is similar to the rolling unit commitment example given in PyPSA documentation example for rolling unit commitment: https://pypsa.readthedocs.io/en/latest/examples/unit-commitment.html 

overlap = 2
for i in range(sets_of_snapshots):
    nu.optimize(nu.snapshots[i * len(p_set) : (i + 1) * len(p_set) + overlap])

We would expect for expect that for each period/value of i, values such as up_time_before for the generators would be calculated using the generator status values from the previous periods. But instead, it seems that for each period, optimize uses the up_time_before initial values that were set in the generators file. 

Note: This is indicated in the PyPSA documentation:

"If snapshots falls in the middle of network.snapshots, then PyPSA assumes the statuses for hours before snapshots have been set by previous simulations, and reads back the previous up-time by examining the previous statuses. "
https://pypsa.readthedocs.io/en/latest/optimal_power_flow.html

**Comment by loongmxbt** [comment]
Same issue, we now manually add constraints to ensure constrains between each horizon. Mainly update `up_time_before` and `down_time_before` and ensure `ramp_limits`.
```python
# i is number of horizon
if i > 0:
            last_snapshots = nu.snapshots[i-1]
            first_snapshots = nu.snapshots[i]
            print(last_snapshots, first_snapshots)
            def ramp_limit_up_rule(m, g):
                p_last = nu.generators_t.p.loc[last_snapshots, g]
                p_first = m.generator_p[g, first_snapshots]
                return p_first - p_last <= nu.generators.loc[g, "ramp_limit_up_p"] 
            
            def ramp_limit_down_rule(m, g):
                p_last = nu.generators_t.p.loc[last_snapshots, g]
                p_first = m.generator_p[g, first_snapshots]
                return p_last - p_first <= nu.generators.loc[g, "ramp_limit_down_p"] 

            model.ramp_limit_up_cons = pyo.Constraint(
                ucmr_name_list, rule=ramp_limit_up_rule
            )
            model.ramp_limit_down_cons = pyo.Constraint(
                ucmr_name_list, rule=ramp_limit_down_rule
            )
```

```python
df_status_uc = nu.generators_t.status.iloc[0:i+NOS_ROLLING_STEP_DA, :]
for name in unit_name_list:
        nu.generators.loc[name, "up_time_before"] = get_max_consecutive_num_from_df(df_status=df_status_uc, col_name=name, num=1)
        nu.generators.loc[name, "down_time_before"] = get_max_consecutive_num_from_df(df_status=df_status_uc, col_name=name, num=0)
```

**Comment by p-glaum** [comment]
Hi! @sophie-pelland @loongmxbt could you check if this PR #780 fixes the bug?

**Comment by sophie-pelland** [comment]
Hi @p-glaum Thanks for looking into this. I tried testing your fix and, as far as I can tell, it does not seem to be working. For instance, if up_time_before is set to 1 in the generators.csv file, then generators with a min_up_time are always on at the beginning of each unit commitment period.

In case this is helpful,here are a few lines of code (outside pypsa itself) that I have been using to get the desired behaviour:

#Code snippet
import pandas as pd
from itertools import groupby, chain

for uc_period in range(settings.uc_periods_per_yr):
    
    snapshots = network.snapshots[a : b]    
    
    #For snapshots except the first one
    if a:

        #Compute up_time_before and down_time_before at a
        cumcount = pd.DataFrame(index=network.snapshots,columns=network.generators_t.status.columns)
        
        for col in network.generators_t.status.columns:
            cumcount[col] = list(chain(*(list(range(len(list(g)))) 
                                   for _,g in  groupby(network.generators_t.status[col])))) 
            
            #Add 1 since previous gives 1 for two consecutive values, 2 for 3 and so on
            cumcount[col] = cumcount[col] + 1
           
        #Calculate up time and down time at given time step, and then use time step before, for generators with status
        network.generators.loc[network.generators_t.status.columns,'up_time_before'] = (network.generators_t.status*cumcount).iloc[a-1,:] 
        network.generators.loc[network.generators_t.status.columns,'down_time_before'] = ((1-network.generators_t.status)*cumcount).iloc[a-1,:]

**Comment by p-glaum** [comment]
hi @sophie-pelland,

I looked for the bug inside the pypsa code, and it is the one I fixed yesterday. However, I forgot to change another parameter, so it still did not work. Now I fixed that as well, so for me now the entry "up_time_before" and "down_time_before" entry in n.generators is not taken if the previous snapshots' status has already been optimized. For the example in the PyPSA documentation for me, it is now working.

**Comment by sophie-pelland** [comment]
Hi @p-glaum,

I just tested your new version and it seems to be working well :) Thanks!

**Comment by PeterKlein11** [comment]
Hi @p-glaum. I tried this fix and it did seem to resolve the rolling horizon UC issue for my test case.

**Comment by p-glaum** [comment]
Hi @PeterKlein11, okay perfect, thanks for testing! I guess then we can merge this into the master. As soon as I can get a minimal example reproducing the bug from @sophie-pelland, I will also try to fix this.
