### ISSUE TITLE
cartopy dependency issues with pip

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#78]
Installing `pypsa` with `pip install pypsa` causes problems if the `cartopy` requirements `GEOS` and `PROJ` are not installed as reported on the mailing list.

`cartopy` was added to `setup.py` requirements in #59 to enforce a version of `cartopy>=0.16`.

**Two alternative ways to close this issue:**
1. Add to installation instructions with `pip` in the documentation to install `cartopy` requirements first (https://scitools.org.uk/cartopy/docs/latest/installing.html#requirements). This is easy for linux:
```bash
apt-get install libgeos++ proj-bin libproj-dev
```
(but presumably more difficult in windows)

2. Remove `cartopy` from requirements in `setup.py` and revert to alternative solution of issue #59. 

Opinions @FabianHofmann @coroa @nworbmot?

(installation via `conda` is unaffected by this)

**Comment by fneum** [comment]
Actually one can do both; remove requirement and add instructions how to add cartopy in the documentation (`apt-get ...` and then `pip install cartopy`)

**Comment by FabianHofmann** [comment]
Another way, if 1. causes difficulties (for windows user then), should be 

```bash 
pip install pypsa --no-deps
```
and work through remaining packages which are not installed but necessary for pypsa, mainly

```bash 
pip install six scipy pandas pyomo matplotlib  networkx
```
Then either figure out a way to install cartopy or use pypsa without being able of geoplotting.

**Comment by MinhHaDuong** [comment]
Affects me too.

**Comment by coroa** [comment]
@MinhHaDuong : I'd recommend to use `conda/anaconda`, instead, as described in the [installation docs](https://pypsa.readthedocs.io/en/latest/installation.html#installing-pypsa-with-conda).

As a solution to this issue, let's add `cartopy` and `basemap` as two separate `extras` to `setup.py` as described in the [setuptools docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#id16). Such features, are only installed with f.ex. `pip install pypsa[cartopy]`, for example.

In the plotting routines, we should then add a warning, if neither `cartopy` nor `basemap` are there, and link to some relevant section in the docs on how to get this working.
