### ISSUE TITLE
Unit testing for Python 2.7 with pandapower 2.1.0 fails

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#79]
Tests for Python 2.7 fail in 7038b76c751e211135a4a7f0aa74a3d13b69b4ee as it was the first CI run with the recent `pandapower v2.1.0` (https://travis-ci.org/PyPSA/PyPSA/jobs/557399790).

While `pandapower v2.0.0` already officially dropped Python 2.7 support, the unit tests of `pypsa` work with up to `pandapower v2.0.1` (https://github.com/e2nIEE/pandapower/releases and discussion in https://github.com/e2nIEE/pandapower/issues/224).

1. A proposal would be to fix the version in `environment_dev.yaml` to `pandapower==2.0.1` until the Python 2.7 countdown has run down (https://pythonclock.org/) on January 1, 2020. We make a final release tested for Python 2.7 then, and allow again to pull most recent `pandapower`.
2. An alternative is to create Python version specific `environment_dev.yaml` files; e.g. `environment_dev_python2.yaml` and `environment_dev_python3.yaml`.
3. Another option is to drop Python 2.7 support right now.

Other opinions/options?

**Comment by FabianHofmann** [comment]
I guess option 1. is the cleanest one, but I would not wait until the clock ran down but rather drop the support soonly and announcing it in the README.md beforehand.

**Comment by fneum** [comment]
Thanks, this is obviously very neat!
