### ISSUE TITLE
marginal_cost_quadratic does not affect buses_t.marginal_price

### ISSUE THREAD

**Issue by loongmxbt** [PyPSA/PyPSA#790]
Hi, I've tried the field `marginal_cost_quadratic` and seems does not affect the objective value. I assume the `marginal_cost_quadratic` turns the cost into `a*p^2 + b*p`, and if I randomly add the `marginal_cost_quadratic`column, the objective value and marginal_price will change.

BTW, is any example notebook of setting the `marginal_cost_quadratic`?

```python
import pypsa

n = pypsa.examples.ac_dc_meshed()


n.optimize(solver_name='highs')
print('First Result')
print(n.buses_t.marginal_price["London"])
print(n.generators_t.p)


print('Second Result')

# n.generators.loc["Manchester Wind","marginal_cost"] = 0.08
n.generators.loc["Manchester Wind","marginal_cost_quadratic"] = 0.02
# n.generators["marginal_cost_quadratic"] = 0.1

n.optimize(solver_name='highs')
print(n.generators_t.p)
print(n.buses_t.marginal_price["London"])
```

```
1st
Objective value     : -3.4742542914e+06
2nd
Objective value     : -3.4742542914e+06

**Comment by fneum** [comment]
Possibly related to https://github.com/PyPSA/linopy/issues/171

**Comment by fneum** [comment]
I have tried with a slightly different setup, and the quadratic cost terms definitely impacted prices and costs. Perhaps the marginal_cost_quadratic was too small here to have an effect?

I noticed that if you specify the solver in HiGHS (e.g. IPM), the quadratic terms are ignored.
