### ISSUE TITLE
Adding argument to l_objective

### ISSUE THREAD

**Issue by dcradu** [PyPSA/PyPSA#80]
We are currently looking into using some `pypsa` features in our planning tools and we came across an issue that could be interesting to tackle. More specifically, the `l_objective` function in the `opt.py` module takes as argument the `model` and the `objective`, but the `sense` is set as `minimize` within the function. Would it be possible to add an extra argument to the function so that the `sense` can be input by the user (in case we want to `maximize` certain objectives)?

**Comment by fneum** [comment]
Possible yes, however you could just as well multiply your expression with `-1`. Feel free to prepare a pull request. Important would be that the default behaviour remains to minimize the objective function.

```python
def l_objective(model, objective=None, sense=1):
    ...
```

where setting `sense=-1` will maximise. You may also use `maximize` and `minimize` from `pyomo`, but bare in mind you have to import them: `from pyomo.environ import maximize, minimize`.
