### ISSUE TITLE
CAPEX documentation issue

### ISSUE THREAD

**Issue by Alex-Neve** [PyPSA/PyPSA#817]
## Checklist

- [ X] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

* The CSV files of generators, lines, links, storage_units, stores and transformers stored under the "_component_attrs_" folder incorrectly state in the "_description_" column that the "_capital_cost_" attribute is the "_Capital cost of extending p_nom by 1 MW_."
* However, as pointed out in the PyPSA article "[Power System Optimization](https://pypsa.readthedocs.io/en/latest/optimal_power_flow.html)", "_the capital_cost of the assets is now the fixed annual costs, including annuity and FOM._"
* I suggest replacing the "_capital_cost_" attribute description with "_Fixed annual costs, including investment costs annuity and Fixed O&M costs._" (This is done in the attached CSV files) 
[transformers.csv](https://github.com/PyPSA/PyPSA/files/14015212/transformers.csv)
[generators.csv](https://github.com/PyPSA/PyPSA/files/14015213/generators.csv)
[lines.csv](https://github.com/PyPSA/PyPSA/files/14015214/lines.csv)
[links.csv](https://github.com/PyPSA/PyPSA/files/14015216/links.csv)
[storage_units.csv](https://github.com/PyPSA/PyPSA/files/14015217/storage_units.csv)
[stores.csv](https://github.com/PyPSA/PyPSA/files/14015218/stores.csv)

**Comment by FabianHofmann** [comment]
Hey @Alex-Neve, thank you for your suggestion. I am not sure whether the proposed description is general enough. Assume you have a time horizon of less or more than one year. Then the term `annualized costs` is not correct any more, right?

**Comment by Alex-Neve** [comment]
Hi @FabianHofmann ,

Would you prefer "periodized costs"? This would leave it to the user to pick his/her preferred time-scale.

In my sector of the industry we use annualized costs because the investment periods are so long that monthly discounting of the costs would not make sense, but other users may work at different time-scales.

If you prefer "periodized costs", I might leave an indication in the CSV files that if periods are defined as years, these periodized costs are identical to annualized costs.

Kr,
Alex

**Comment by Alex-Neve** [comment]
Here are the CSV files that I have reworded to avoid the terms "annual" and "annualized".
FYI, I cannot create a branch to propose this change myself in a pull request.

[generators.csv](https://github.com/PyPSA/PyPSA/files/14067496/generators.csv)
[lines.csv](https://github.com/PyPSA/PyPSA/files/14067497/lines.csv)
[links.csv](https://github.com/PyPSA/PyPSA/files/14067498/links.csv)
[storage_units.csv](https://github.com/PyPSA/PyPSA/files/14067499/storage_units.csv)
[stores.csv](https://github.com/PyPSA/PyPSA/files/14067500/stores.csv)
[transformers.csv](https://github.com/PyPSA/PyPSA/files/14067501/transformers.csv)

**Comment by fneum** [comment]
You can via a fork.

**Comment by fneum** [comment]
closed via #822
