### ISSUE TITLE
Limited Pyomo version

### ISSUE THREAD

**Issue by nick-harder** [PyPSA/PyPSA#829]
For python 3.12 the first pyomo release supported is 6.7 which is not installable with the latest pypsa version 0.26.3 - due to the pyomo version limit.

This results in conda installing an older pypsa version (0.25.1) which is unsupported in other ways (`pd.Dataframe does not have .map` and other things..)

So it would be good to have a pypsa release which supports pyomo 6.7 :blush:

_Originally posted by @maurerle in https://github.com/PyPSA/PyPSA/issues/726#issuecomment-1926773835_

**Comment by nick-harder** [comment]
maybe there is a way to make pyomo dependency optional since linopy is used by default?

**Comment by fneum** [comment]
One could do something like https://github.com/PyPSA/linopy/pull/223/files/7e52c2b446c6b41619efb01eeccda11d2d9e6116..97729210f66e304fa50c2996a2dc428ede407abb

Happy to review a PR if it has to happen soon.

**Comment by fneum** [comment]
Closed via #831
