### ISSUE TITLE
how to get network.generator_t.q??? i.e. reactive power output for the generators

### ISSUE THREAD

**Issue by Misbahrani** [PyPSA/PyPSA#84]
Hello!
I am implementing the RTS-96 system, with the following generator data:
![image](https://user-images.githubusercontent.com/52325843/62112779-da79d200-b2cc-11e9-920b-f5581b78fa3a.png)
How to get each generator's reactive power as output???
Currently, I am getting only real power, i.e. network.generator_t.p
![image](https://user-images.githubusercontent.com/52325843/62112923-190f8c80-b2cd-11e9-94f1-c08cc3ca4e9d.png)

**Comment by FabianHofmann** [comment]
Hello @Misbahrani, 

it depends which calculaction you want to perform. When solving the network to cost-optimality (which I suppose you want to do), then the network has to be solved linearly using [linear optimal power flow](https://pypsa.readthedocs.io/en/latest/optimal_power_flow.html). That is reactive parts of the power flows are neglected to keep the program linear. 
However, the full AC power flow can be calculated with the common [power flow](https://pypsa.readthedocs.io/en/latest/power_flow.html), there you get back reactive power dispatch and flow as well. 

So probably, if this is important for you, a good way to go might be first performing a lopf and then a pf (mind the bus control, I think one bus has to a slack bus, one other a PQ bus). An example can be found [here](https://www.pypsa.org/examples/scigrid-lopf-then-pf.html)

**Comment by Misbahrani** [comment]
Thank you so much Sir, for your quick response
I want to do cost-optimality along with full AC power flow.
& yes I have bus#113 as slack bus.
I have run that example, and exported output in csv format
![image](https://user-images.githubusercontent.com/52325843/62114513-41e55100-b2d0-11e9-9a4e-4bae72c861d4.png)

but there isnt generator's reactive power as output, then I checked the generator's input csv file and it didnt have any q_set info so I asked here
![image](https://user-images.githubusercontent.com/52325843/62114639-82dd6580-b2d0-11e9-9ddb-8d697c50a737.png)

**Comment by FabianHofmann** [comment]
Did you follow the steps in similarly to [this setup](https://www.pypsa.org/examples/scigrid-lopf-then-pf.html#Now-perform-a-full-Newton-Raphson-power-flow-on-the-first-hour)? The q_set defaults to 0, so there shouldn't be a problem

**Comment by Misbahrani** [comment]
Yes Sir
I have completely run this example everything is working fine except these two graphs:
![image](https://user-images.githubusercontent.com/52325843/62211522-2c4b5680-b3b8-11e9-834f-e071282a78be.png)
&
![image](https://user-images.githubusercontent.com/52325843/62211546-39684580-b3b8-11e9-9024-14025ad957e5.png)
I have also implemented this on RTS-96 system, I have obtained reactive power, but there is an issue.
The algorithm shows reactive power for those generators which have 0 real power output, my point is if a generator is OFF and not producing any real power then how can it generate or absorb reactive power??? this is shown in the screen shot(green tabs are real power, below them is corresponding reactive power for the specific hour:
![image](https://user-images.githubusercontent.com/52325843/62211937-3ae63d80-b3b9-11e9-9a73-33f731af1b09.png)
I thought there is something wrong with my data, but i have checked the given example data too. N same issue appears, as shown in the screen shot:
![image](https://user-images.githubusercontent.com/52325843/62212714-cad8b700-b3ba-11e9-8232-f278384940ec.png)
in the generator specs

**Comment by Misbahrani** [comment]
in the generator specs, one can enter specify P_min & P_max in both per unit and nominal MW values .
how can i implement the Q_min & Q_max so that there should be bound on the reactive power too

**Comment by fneum** [comment]
https://groups.google.com/forum/#!msg/pypsa/MsM47hXG8vg/JlzDA7M2CwAJ
