### ISSUE TITLE
linear power flow(lpf) considering transmission loss

### ISSUE THREAD

**Issue by 0wenwu** [PyPSA/PyPSA#845]
So far, function `lpf()` can not considering transmission line loss. Only `lopf()` can set `transmission_losses`.
Would you please add the param `transmission_losses` to lpf

**Comment by FabianHofmann** [comment]
@0wenwu this is not possible as the linear power flow approximation assumes lossless power transfers. The optimization however can handle this. Please reopen if I am missing some wisdom
