### ISSUE TITLE
n.add and n.madd different behaviour

### ISSUE THREAD

**Issue by lisazeyen** [PyPSA/PyPSA#867]
## Align `n.add` and `n.madd`

When adding a component with non-default attributes, `n.add`  would not add the attribute while `n.madd`  does, for example
`n.add("Bus", "co2 atmosphere", location="EU", carrier="co2", unit="t_co2")`
Does not add the attribute `location`, since it is not defined by default while
`n.madd("Bus", ["co2 atmosphere"], location=["EU"], carrier="co2", unit="t_co2")`
add the column location to the dataframe.

**Comment by lindnemi** [comment]
i ran into the same issue today, see https://github.com/PyPSA/pypsa-ariadne/issues/59
