### ISSUE TITLE
Time series consisting of constant values are dropped when exporting network

### ISSUE THREAD

**Issue by C-Krueger** [PyPSA/PyPSA#88]
Our network includes links that have timeseries for `p_max_pu`. In some cases it might be that the timeseries consists of static values. If we build the network, the according timeseries can be found in `n.links_t.p_max_pu`. But if we export the network to NetCDF and import it again, the timeseries in `links_t` disappeared. 
That would be ok, if the according value would instead be written into `n.links.p_max_pu` as static, but that does not happen. 
We found a work-around for our case, but report this issue though. It would be great if you could fix that, or include a warning that „constant timeseries“ are deleted when exporting a network.

**Comment by fneum** [comment]
Do you happen to have a minimal example? I tried to quickly reproduce this error (PyPSA 0.14.1), but did not find any problems:
https://gist.github.com/fneum/9a329778e4a182d8c968819ee2adc2f7
You can also check mine to see, if I understood your problem correctly.

**Comment by C-Krueger** [comment]
Thanks for the swift reply and for the example. You understood it right. It seems that the problem occurs only if the value is "1". 
I assume that this has got something to do with the fact that "1" is the default value for `p_max_pu` in `n.links`. 
In our case we use the entry `p_max_pu` in `n.links` when building the network to indicate that a corresponding time series should be read. We then overwrite this text entry with 0. Maybe the problem has got something to do with the fact that we overwrite the default?

**Comment by fneum** [comment]
> In our case we use the entry `p_max_pu` in `n.links` when building the network to indicate that a corresponding time series should be read.

Do you mean you set e.g. `n.links.p_max_pu.lk1=False` and `n.links.p_max_pu_lk2=True`? This will change the type from float to boolean, and it is probably best that this is not imported back (I can reproduce your issue then).

My suggestion would be -- instead of changing the meaning/use of `n.links.p_max_pu` -- to add a new column to `n.links` (e.g. `n.links['time_dependent', 'lk1'] = False`). PyPSA importers/exporters preserve additional columns you add to components' dataframes.

However, I am also not sure what you mean exactly by 

> to indicate that a corresponding time series should be read

**Comment by coroa** [comment]
@C-Krueger You identified the "problem" correctly we skip storing time dependent values which are equal with the default to save space:
https://github.com/PyPSA/PyPSA/blob/4d0a6a6cccd1d5d0de72118424a105d33a22777a/pypsa/io.py#L342-L345

You can either follow @fneum's proposal to use a new field or propose code yourself to, for instance, make skipping data conditional on an argument to the exporter or on a new field in the component_attrs table.

**Comment by C-Krueger** [comment]
Of course it makes perfect sense to save space by skipping these time-dependent values. To handle the problem going along with that, we will probably do something similar to @fneum's proposal. 
@fneum and @coroa, thanks for your support!
