### ISSUE TITLE
examples in readthedocs not working

### ISSUE THREAD

**Issue by WouterKoksNL** [PyPSA/PyPSA#888]
## Describe the Bug

Currently some of the examples in https://pypsa.readthedocs.io/ are not working because they were run with wrong input settings. At least, a solver is specified that is not installed. 
E.g. this example is not working: https://pypsa.readthedocs.io/en/latest/examples/scigrid-redispatch.html

AssertionError: Solver cbc not installed

**Comment by fneum** [comment]
Thanks, I changed the default solver yesterday and cleaned-up the environment (i.e. remove cbc) while missing the examples.
