### ISSUE TITLE
Problem with Optimal Power flow of 30 bus system

### ISSUE THREAD

**Issue by Misbahrani** [PyPSA/PyPSA#92]
Hello!
I am trying to implement 30 bus system, but OPF is infeasible, I have tried to play around transformer reactance'x' & Newton raphson converges for the reactance below 0.5 but OPF doesnt. I have attached csv files and jupyter notebook file.
Kindly guide me, where is the error?

[input_pypsa.zip](https://github.com/PyPSA/PyPSA/files/3511685/input_pypsa.zip)

**Comment by fneum** [comment]
**Please, in the futue ask general use questions in the forum: https://groups.google.com/forum/#!forum/pypsa**

Narrowing down infeasibilities can be a tedious task.

First try reducing the model (e.g. number of snapshots) to the minimum, such that the infeasibility still occurs.

You can also try relaxing the capacity limits of lines, links, generators, etc.

Alternatively, you can add load shedding "generators" to the network and try to understand why it may be dispatched. Follow previous discussions here: https://groups.google.com/forum/#!searchin/pypsa/load$20shedding%7Csort:date/pypsa/Q1PrUqmDrlQ/eG69AxYNBQAJ

Moreover, if you are using e.g. Gurobi, you can check the IIS (Irreducible Infeasible Subsystem) for infeasibilities. Follow also previous discussions here:
https://groups.google.com/forum/#!searchin/pypsa/iis%7Csort:date/pypsa/UDFnQAyILWg/cxk3bqqoCQAJ

**Comment by Misbahrani** [comment]
Okay sir Fabian thanks
I will post it in the group, I am checking one snapshot at a time, by changing the index 0~23:
solver_name = "glpk"
network.lopf(network.snapshots[0],
             solver_name=solver_name,
             keep_files=True)
