### ISSUE TITLE
Statistics module very slow in 0.28

### ISSUE THREAD

**Issue by PeterKlein11** [PyPSA/PyPSA#922]
## Checklist

- [x ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate:

## Describe the Bug

Running n.statistics() under the latest version is very slow on some multi horizon networks I tested, but quick in 0.27.

**Comment by PeterKlein11** [comment]
Sorry should have added a bit more info. Model is 8 investment periods with full chronology, but only 3 buses and a limited number of generators. 

Unfortunately model is confidential for a project so I can't share it. 

0.27 n.statistics() takes less than a second to load. With 0.28 didn't finish in over 10min.

**Comment by FabianHofmann** [comment]
Oh wow, there is definitively a bug, then. Could you run the thing again and break it after some time (30 sec perhaps) and send the error log, so we can see where exactly it stumbles?

**Comment by lkstrp** [comment]
I think this is a dependency issue. @PeterKlein11 Could you update your environment and see if the problem has already been solved?

And if not, in addition to what Fabian suggested, could you share your env infos:
For Conda: `conda list --explicit > specs.txt`
For Pip: `pip freeze > specs.txt`

**Comment by PeterKlein11** [comment]
@FabianHofmann  and @lkstrp apologies for the delayed reply, been a bit busy. Will try the environment update.

**Comment by PeterKlein11** [comment]
Hi @FabianHofmann and @lkstrp 

I have tried updating the packages and the issue with slow statistics remains in v0.28, with the multi-horizon network file.

See attached log file. I have also attached my env info.
[specs_pip.txt](https://github.com/user-attachments/files/16281933/specs_pip.txt)
[specs_conda.txt](https://github.com/user-attachments/files/16281934/specs_conda.txt)
[statistics_log.txt](https://github.com/user-attachments/files/16281935/statistics_log.txt)

See attached wetransfer link for a network to test against - in v0.27 statistics loads in 2.5s for reference
https://we.tl/t-cHVdElA4tX

**Comment by lkstrp** [comment]
Thank you @PeterKlein11 ! I will have a look.

**Comment by wiedeflo** [comment]
Hi @PeterKlein11, @lkstrp and @FabianHofmann

I have also noticed the slow working of the statistics module and found that for me it was mostly caused by the changes from #876. The looped over index contains duplicate values i.e. for each timestep per year, resulting in a lot of unnecessary computation. Adding `.drop_duplicates()` seems to have fixed the issue in my case. Since I am very new to working with PyPsa I wanted to confirm if this would fix your speed issues as well.
