### ISSUE TITLE
Calculate_PTDF() always gives zero for first bus, regardless which bus is slack

### ISSUE THREAD

**Issue by TomAdamsHET** [PyPSA/PyPSA#923]
Using pypsa 0.26.0 in python 3.11.6

When I use the function calculate_PTDF() on a subnetwork it returns a numpy array. Running a few tests, it looks like the dimensions are subnetwork.branches_i  () x  subnetwork.buses_i(). Can anyone confirm this?

However, the first column is always zero - regardless of whether the first bus is the slack bus or not. I would expect zeros for the slack bus, as an injection of power there would be taken up by the slack generator, but not for any other bus. Is the order of columns in the numpy array different to  subnetwork.buses_i(), or is there some other reason the first column is always zero?

Toy example, three buses with slack generator at Bus 2, and a load at Bus 1. 1MW at Bus 0 should increase flow along Line 01. 1MW at Bus1 should increase flow towards slack, on Line 12. 1MW at Bus2 should have no effect (slack). But this is not what you get!

``` python
import pypsa
import pandas as pd

n = pypsa.Network() 

n.add("Bus", "Bus 0")
n.add("Bus", "Bus 1")
n.add("Bus", "Bus 2")
n.add("Line","Line 01", bus0 = "Bus 0", bus1 = "Bus 1", x=0.1, s_nom=50)
n.add("Line","Line 12", bus0 = "Bus 1", bus1 = "Bus 2", x=0.1, s_nom=50)

n.add("Generator", "Gen 3",
            bus=f"Bus 2",
            p_nom=100,
            marginal_cost=10,
            control = 'Slack',
)

n.add("Load", "Load 1",
            bus="Bus 1",
            p_set=50,
            )
 
n.determine_network_topology()
sn = n.sub_networks.obj['0']
```
``` python
sn.slack_bus
> 'Bus 2'
```
``` python
sn.calculate_PTDF()
pd.DataFrame(sn.PTDF, index = sn.branches_i(), columns = sn.buses_i())
```
  Bus | Bus 0 | Bus 1 | Bus 2
-- | -- | -- | -- | --
0.0 | 1.0 | 0.0
0.0 | 1.0 | 1.0

**Comment by RobbieKiwi** [comment]
The slack bus is chosen as the reference node and moved to the first column.
To get the dataframe with the right labels you should use
`ptdf = pd.DataFrame(sn.PTDF, index=sn.branches_i(), columns=sn.buses_o)`

Which gives:

| Line | Bus 2 | Bus 0 | Bus 1 |
|--------|--------|--------|--------|
| Line 01 | 0.0 | 1.0 | 0.0 |
| Line 12 | 0.0 | 1.0 | 1.0 |

- 1MW from Bus2 to Bus2 does nothing
- 1MW from Bus0 to Bus2 increases flow in both lines by 1 MW
- 1MW from Bus1 to Bus2 increases flow in line 12 by 1 MW
