### ISSUE TITLE
Link length not considered in networkclustering

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#94]
When clustering the network, links will be aggregated but their length not recalculated. I am not sure whether this is intended. 
This leads to a distortion of the line extension volume limit in f.e. pypsa-eur which favours 'short' links which are in reality long.
 
@coroa can you help me here?

If it is not intended I would add some line in networkclustering to cover this.

**Comment by FabianHofmann** [comment]
Adding this 
```python
coords = network.buses[['x', 'y']].apply(list, axis=1)
new_links['length'] = (new_links[['bus0', 'bus1']]
                       .apply(lambda s: s.map(coords))
                       .apply(list, axis=1).apply(_haversine))
```
in [here](https://github.com/PyPSA/PyPSA/blob/621ddec8ccce361e074411764837df325ddb3319/pypsa/networkclustering.py#L298) should do it

**Comment by coroa** [comment]
Links are NOT aggregated by networkclustering. They are only reconnected to the new buses.

Therefore, I don't think they should receive any other length. On the other hand this leads, for example, for the HVDC link over the Pyrenees to an improbably cheap alternative to the AC lines for a 1-node per country clustering.

Which would also imply, that it would be not enough to update the `length` but one would also need to update `capital_cost` and `underwater_fraction`. There lies peril on that path.

@nworbmot : Any thoughts on this?

**Comment by nworbmot** [comment]
I agree with @coroa. This needs to be done properly, accounting for subsea and overland parts. Here's a suggestion: calculate the length underwater, save it, then work out the 1.25 crow flies distance for the total length. The new subsea length is the same as before, the new overland is the new total minus subsea. This can then be used to calculate the capital cost.

**Comment by coroa** [comment]
@FabianHofmann: Ok, I think that boils down to two things:

1. Yes, we should update the length to `line_length_factor * haversine` (i don't particularly like your three chained `apply`s, i'm pretty sure there is a simpler solution for this exact problem already in pypsa-eur (search for haversine there))
2. We have to change capital_cost (scale it linearly by default, but must be configurable)
3. In pypsa-eur, we have to add the logic to update underwater_fraction and capital_cost according to tom's suggestion.

**Comment by FabianHofmann** [comment]
@coroa, okay, do I get it correctly that point 1 and 2  
> 1. Yes, we should update the length to line_length_factor * haversine (i don't particularly like your three chained applys, i'm pretty sure there is a simpler solution for this exact problem already in pypsa-eur (search for haversine there))
> 2. We have to change capital_cost (scale it linearly by default, but must be configurable)

are going into the pypsa code? 
And with 'configurable' at point 2, you mean a flag which allows to enable/disable updating the capital_costs?
