### ISSUE TITLE
Incorporate nomopyomo as module

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#96]
I would advocate for including https://github.com/PyPSA/nomopyomo as a module of PyPSA.

This should also include extending the existing unit tests to the `nomopyomo.network_lopf(network, ...)` (plus those @FabianHofmann wrote in https://github.com/PyPSA/nomopyomo/blob/parallelised/nomopyomo/test.py)!

Would it make sense to attach it to the network object just as `opf.network_lopf(network, ...)`? E.g. `network.lopf_nopyomo()` or `network.lopf_lowmemory()`.

Probably something like `network.lopf(pyomo=False)` would turn out less clean in the code, I imagine.

How do others imagine the integration?

**Comment by FabianHofmann** [comment]
Hey @fneum, I think that is a good idea! In my opinion from a user's perspective the option 
```python 
network.lopf(pyomo=False)
```
or 
```python
network.lopf(lowmemory=True)
```
would the best. The issue that I am not sure of, is how to incorporate the nomopyomo 'package'. I see two options for the moment

1. Create two new modules in pypsa, such as opf_nopyomo.py and opt_nopyomo.py which include all the code needed. 
2. Keep the code in another package (on an interim basis), load necessary functions into pypsa (pip installation required) and use them there.
 
The first option would blow up the pypsa code a bit. On the other hand, it is easier and straight forward compared to option 2. 

I continued to work on the code in nomopyomo code, and listed the progress in this [Roadmap](https://github.com/PyPSA/nomopyomo/tree/parallelised#roadmap). There is still some parts which are not super pretty. But if you want (also @nworbmot and @coroa) I can try to summarize the main changes and setup a small example.
