### ISSUE TITLE
BUG: "dimensions are not aligned" error when snapshot DatetimeIndex has tz_info

### ISSUE THREAD

**Issue by connortann** [PyPSA/PyPSA#974]
### Version Checks (indicate both or one)

- [X] I have confirmed this bug exists on the lastest [release](https://github.com/pypsa/pypsa/releases) of PyPSA.
- [ ] I have confirmed this bug exists on the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch of PyPSA.

### Issue Description

PyPSA throws a warning that snapshot "dimensions are not aligned" when the snapshot DatetimeIndex has timezone info attached:

> UserWarning: coords for dimension(s) ['snapshot'] is not aligned with the pandas object. Previously, the indexes of the pandas were ignored and overwritten in these cases. Now, the pandas object's coordinates are taken considered for alignment.

### Reproducible Example

```python
import warnings
import pandas as pd
import pypsa

# Show the full traceback for this warning
warnings.filterwarnings("error", ".*not aligned with the pandas object.*")

n = pypsa.Network()
n.add("Bus", "bus")
n.add("Store", "store", bus="bus", e_nom=100, e_nom_extendable=True, capital_cost=1)

# Without time zone info: this works
index = pd.date_range("2020-01-01", periods=4, freq="h")
n.set_snapshots(index)
n.optimize.create_model()

# With time zone info: this raises the warning about non-aligned dimensions
index = pd.date_range("2020-01-01", periods=4, freq="h").tz_localize("UTC")
n.set_snapshots(index)
n.optimize.create_model()
```

Full traceback:

<details>

```python
Traceback (most recent call last):
  File "/home/connor/projects/HydrogenCOE-PyPSA/Local_scripts/pypsa_bug.py", line 21, in <module>
    n.optimize.create_model()  # Raises a warning about non-aligned dimensions
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/pypsa/optimization/optimize.py", line 609, in create_model
    return create_model(self._parent, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/pypsa/optimization/optimize.py", line 300, in create_model
    define_store_constraints(n, sns)
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/pypsa/optimization/constraints.py", line 906, in define_store_constraints
    m.add_constraints(lhs, "=", rhs, name=f"{c}-energy_balance", mask=active)
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/linopy/model.py", line 558, in add_constraints
    data = self.linexpr(*lhs).to_constraint(sign, rhs).data
           ^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/linopy/model.py", line 893, in linexpr
    return LinearExpression.from_tuples(*tuples, chunk=self.chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/linopy/expressions.py", line 962, in from_tuples
    expr = v.to_linexpr(c)
           ^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/linopy/variables.py", line 314, in to_linexpr
    coefficient = as_dataarray(coefficient, coords=self.coords, dims=self.dims)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/linopy/common.py", line 211, in as_dataarray
    arr = pandas_to_dataarray(arr, coords=coords, dims=dims, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/connor/miniforge3/envs/temp-pypsa-bug/lib/python3.11/site-packages/linopy/common.py", line 140, in pandas_to_dataarray
    warn(
UserWarning: coords for dimension(s) ['snapshot'] is not aligned with the pandas object. Previously, the indexes of the pandas were ignored and overwritten in these cases. Now, the pandas object's coordinates are taken considered for alignment.
```

</details>

### Expected Behavior

The model should not throw a warning about non-aligned indexes

### Discussion

I believe the root cause of this issue is when the dtype of the datetimeindex is converted here in `define_store_constraints()`:

https://github.com/PyPSA/PyPSA/blob/8275cc53f9838a1a198620eef9d3abfe58f10b3d/pypsa/optimization/constraints.py#L844

Initially the `sns` variable here is a DatetimeIndex, as expected:
```python
$ sns
DatetimeIndex(['2020-01-01 00:00:00+00:00', '2020-01-01 01:00:00+00:00',
               '2020-01-01 02:00:00+00:00', '2020-01-01 03:00:00+00:00'],
              dtype='datetime64[ns, UTC]', name='snapshot', freq='h'
```

But after being converted to a `DataArray`, the variable `active` is an array of dtype `object`:
```python
$ active.snapshot
<xarray.DataArray 'snapshot' (snapshot: 4)> Size: 32B
array([1577836800000000000, 1577840400000000000, 1577844000000000000,
       1577847600000000000], dtype=object)
Coordinates:
  * snapshot  (snapshot) object 32B 1577836800000000000 ... 1577847600000000000
  ```

This change leads to a warning from linopy, as the two indexes do not compare as equal:

https://github.com/PyPSA/linopy/blob/02d61f49db137e1f21992b4c6c88a7f9202d98b6/linopy/common.py#L141

### Installed Versions

A clean python 3.11 env with just the latest release of pypsa (& dependencies)

<details>

blosc2==2.7.0
Bottleneck==1.4.0
certifi==2024.7.4
cftime==1.6.4
click==8.1.7
cloudpickle==3.0.0
contourpy==1.2.1
cycler==0.12.1
dask==2024.7.0
deprecation==2.1.0
fonttools==4.53.1
fsspec==2024.6.1
geopandas==1.0.1
importlib_metadata==8.0.0
kiwisolver==1.4.5
linopy==0.3.13
locket==1.0.0
matplotlib==3.9.1
msgpack==1.0.8
ndindex==1.8
netCDF4==1.7.1.post1
networkx==3.3
numexpr==2.10.1
numpy==1.26.4
packaging==24.1
pandas==2.2.2
partd==1.4.2
pillow==10.4.0
ply==3.11
polars==1.1.0
py-cpuinfo==9.0.0
pyogrio==0.9.0
Pyomo==6.6.1
pyparsing==3.1.2
pyproj==3.6.1
pypsa==0.28.0
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
scipy==1.14.0
shapely==2.0.4
six==1.16.0
tables==3.9.2
toolz==0.12.1
tqdm==4.66.4
tzdata==2024.1
validators==0.31.0
xarray==2024.6.0
zipp==3.19.2

</details>

**Comment by fneum** [comment]
Thanks for the detailed bug report! Really something one can work with. I could reproduce the bug and we'll look into it soon!

**Comment by lkstrp** [comment]
Thanks for the details @connortann ! It was easy to track down.
Numpy does not support timezone information, but pandas does. This leads to issues when creating the model, which is based on xarray, which is based on numpy.

The PR will lead to a ValueError now, if you try to use snapshots with timezones.
You can just fix the issue with passing a numpy array instead via `.values`. It will transform the time (if not UTC) but you will lose the specific timezone.
