### ISSUE TITLE
Can PYPSA Build Thermal Network？

### ISSUE THREAD

**Issue by qingkai-sun** [PyPSA/PyPSA#98]
Hello, everyone. Now I need to build a thermal network on the CHP unit. Can PYPSA achieve this function?

**Comment by fneum** [comment]
Maybe the following examples are helpful to you:
- https://pypsa.org/examples/lopf-with-heating.html
- https://pypsa.org/examples/power-to-gas-boiler-chp.html
- https://pypsa.org/examples/chp-fixed-heat-power-ratio.html

**Comment by qingkai-sun** [comment]
First of all, thank you for your reply. But I want to know more about whether PYPSA can build a thermal network with a topology like a power grid.

**Comment by fneum** [comment]
You could introduce a couple of buses with a carrier called 'heat' and model the thermal network with links. You would assume your heat flows to be controllable.

**Comment by qingkai-sun** [comment]
Thank you very much for your careful answers. I will try to use the method you introduced. I hope to keep in touch with you in the future.

**Comment by fneum** [comment]
No worries!

Just a hint for next time: For this kind of questions we usually prefer the PyPSA mailing list (https://groups.google.com/group/pypsa) since there are more people reading the list than issues. We use issues for feature requests and bugs.
